// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_App from "./Tea_App.res.js";

let Cmd;

let Sub;

let Html;

let Svg;

let Vdom;

let App;

let Render;

let Http;

let Json;

let Time;

let Animationframe;

let Keyboard;

let Mouse;

let Window;

let Ssr;

let Debug;

let Test;

let standardProgram = Tea_App.standardProgram;

let simpleProgram = Tea_App.simpleProgram;

export {
  Cmd,
  Sub,
  Html,
  Svg,
  Vdom,
  App,
  Render,
  Http,
  Json,
  Time,
  Animationframe,
  Keyboard,
  Mouse,
  Window,
  Ssr,
  Debug,
  Test,
  standardProgram,
  simpleProgram,
}
/* No side effect */
