// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Vdom from "./Tea_Vdom.res.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function node(tag, attrs, children) {
  return {
    TAG: "Element",
    _0: tag,
    _1: Stdlib_List.toArray(attrs),
    _2: Stdlib_List.toArray(children)
  };
}

function svg(attrs, children) {
  return node("svg", attrs, children);
}

function g(attrs, children) {
  return node("g", attrs, children);
}

function defs(attrs, children) {
  return node("defs", attrs, children);
}

function symbol(attrs, children) {
  return node("symbol", attrs, children);
}

function use(attrs, children) {
  return node("use", attrs, children);
}

function foreignObject(attrs, children) {
  return node("foreignObject", attrs, children);
}

function circle(attrs, children) {
  return node("circle", attrs, children);
}

function ellipse(attrs, children) {
  return node("ellipse", attrs, children);
}

function line(attrs, children) {
  return node("line", attrs, children);
}

function path(attrs, children) {
  return node("path", attrs, children);
}

function polygon(attrs, children) {
  return node("polygon", attrs, children);
}

function polyline(attrs, children) {
  return node("polyline", attrs, children);
}

function rect(attrs, children) {
  return node("rect", attrs, children);
}

function text$p(attrs, children) {
  return node("text", attrs, children);
}

function tspan(attrs, children) {
  return node("tspan", attrs, children);
}

function textPath(attrs, children) {
  return node("textPath", attrs, children);
}

function linearGradient(attrs, children) {
  return node("linearGradient", attrs, children);
}

function radialGradient(attrs, children) {
  return node("radialGradient", attrs, children);
}

function stop(attrs, children) {
  return node("stop", attrs, children);
}

function clipPath(attrs, children) {
  return node("clipPath", attrs, children);
}

function mask(attrs, children) {
  return node("mask", attrs, children);
}

function pattern(attrs, children) {
  return node("pattern", attrs, children);
}

function marker(attrs, children) {
  return node("marker", attrs, children);
}

function filter(attrs, children) {
  return node("filter", attrs, children);
}

function feGaussianBlur(attrs, children) {
  return node("feGaussianBlur", attrs, children);
}

function feOffset(attrs, children) {
  return node("feOffset", attrs, children);
}

function feBlend(attrs, children) {
  return node("feBlend", attrs, children);
}

function feColorMatrix(attrs, children) {
  return node("feColorMatrix", attrs, children);
}

function feComposite(attrs, children) {
  return node("feComposite", attrs, children);
}

function feFlood(attrs, children) {
  return node("feFlood", attrs, children);
}

function feMerge(attrs, children) {
  return node("feMerge", attrs, children);
}

function feMergeNode(attrs, children) {
  return node("feMergeNode", attrs, children);
}

function animate(attrs, children) {
  return node("animate", attrs, children);
}

function animateTransform(attrs, children) {
  return node("animateTransform", attrs, children);
}

function set(attrs, children) {
  return node("set", attrs, children);
}

function desc(attrs, children) {
  return node("desc", attrs, children);
}

function title(attrs, children) {
  return node("title", attrs, children);
}

function metadata(attrs, children) {
  return node("metadata", attrs, children);
}

function image(attrs, children) {
  return node("image", attrs, children);
}

function viewBox(v) {
  return {
    TAG: "Property",
    _0: "viewBox",
    _1: v
  };
}

function fill(v) {
  return {
    TAG: "Property",
    _0: "fill",
    _1: v
  };
}

function stroke(v) {
  return {
    TAG: "Property",
    _0: "stroke",
    _1: v
  };
}

function strokeWidth(v) {
  return {
    TAG: "Property",
    _0: "stroke-width",
    _1: v
  };
}

function strokeLinecap(v) {
  return {
    TAG: "Property",
    _0: "stroke-linecap",
    _1: v
  };
}

function strokeLinejoin(v) {
  return {
    TAG: "Property",
    _0: "stroke-linejoin",
    _1: v
  };
}

function strokeDasharray(v) {
  return {
    TAG: "Property",
    _0: "stroke-dasharray",
    _1: v
  };
}

function strokeDashoffset(v) {
  return {
    TAG: "Property",
    _0: "stroke-dashoffset",
    _1: v
  };
}

function strokeOpacity(v) {
  return {
    TAG: "Property",
    _0: "stroke-opacity",
    _1: v
  };
}

function fillOpacity(v) {
  return {
    TAG: "Property",
    _0: "fill-opacity",
    _1: v
  };
}

function fillRule(v) {
  return {
    TAG: "Property",
    _0: "fill-rule",
    _1: v
  };
}

function opacity(v) {
  return {
    TAG: "Property",
    _0: "opacity",
    _1: v
  };
}

function transform(v) {
  return {
    TAG: "Property",
    _0: "transform",
    _1: v
  };
}

function d(v) {
  return {
    TAG: "Property",
    _0: "d",
    _1: v
  };
}

function x(v) {
  return {
    TAG: "Property",
    _0: "x",
    _1: v
  };
}

function y(v) {
  return {
    TAG: "Property",
    _0: "y",
    _1: v
  };
}

function x1(v) {
  return {
    TAG: "Property",
    _0: "x1",
    _1: v
  };
}

function y1(v) {
  return {
    TAG: "Property",
    _0: "y1",
    _1: v
  };
}

function x2(v) {
  return {
    TAG: "Property",
    _0: "x2",
    _1: v
  };
}

function y2(v) {
  return {
    TAG: "Property",
    _0: "y2",
    _1: v
  };
}

function cx(v) {
  return {
    TAG: "Property",
    _0: "cx",
    _1: v
  };
}

function cy(v) {
  return {
    TAG: "Property",
    _0: "cy",
    _1: v
  };
}

function r(v) {
  return {
    TAG: "Property",
    _0: "r",
    _1: v
  };
}

function rx(v) {
  return {
    TAG: "Property",
    _0: "rx",
    _1: v
  };
}

function ry(v) {
  return {
    TAG: "Property",
    _0: "ry",
    _1: v
  };
}

function width(v) {
  return {
    TAG: "Property",
    _0: "width",
    _1: v
  };
}

function height(v) {
  return {
    TAG: "Property",
    _0: "height",
    _1: v
  };
}

function points(v) {
  return {
    TAG: "Property",
    _0: "points",
    _1: v
  };
}

function offset(v) {
  return {
    TAG: "Property",
    _0: "offset",
    _1: v
  };
}

function stopColor(v) {
  return {
    TAG: "Property",
    _0: "stop-color",
    _1: v
  };
}

function stopOpacity(v) {
  return {
    TAG: "Property",
    _0: "stop-opacity",
    _1: v
  };
}

function gradientUnits(v) {
  return {
    TAG: "Property",
    _0: "gradientUnits",
    _1: v
  };
}

function textAnchor(v) {
  return {
    TAG: "Property",
    _0: "text-anchor",
    _1: v
  };
}

function dominantBaseline(v) {
  return {
    TAG: "Property",
    _0: "dominant-baseline",
    _1: v
  };
}

function fontSize(v) {
  return {
    TAG: "Property",
    _0: "font-size",
    _1: v
  };
}

function fontFamily(v) {
  return {
    TAG: "Property",
    _0: "font-family",
    _1: v
  };
}

function fontWeight(v) {
  return {
    TAG: "Property",
    _0: "font-weight",
    _1: v
  };
}

function in_(v) {
  return {
    TAG: "Property",
    _0: "in",
    _1: v
  };
}

function in2(v) {
  return {
    TAG: "Property",
    _0: "in2",
    _1: v
  };
}

function result(v) {
  return {
    TAG: "Property",
    _0: "result",
    _1: v
  };
}

function stdDeviation(v) {
  return {
    TAG: "Property",
    _0: "stdDeviation",
    _1: v
  };
}

function dx(v) {
  return {
    TAG: "Property",
    _0: "dx",
    _1: v
  };
}

function dy(v) {
  return {
    TAG: "Property",
    _0: "dy",
    _1: v
  };
}

function xlinkHref(v) {
  return {
    TAG: "Property",
    _0: "href",
    _1: v
  };
}

function clipPathRef(v) {
  return {
    TAG: "Property",
    _0: "clip-path",
    _1: v
  };
}

function maskRef(v) {
  return {
    TAG: "Property",
    _0: "mask",
    _1: v
  };
}

function filterRef(v) {
  return {
    TAG: "Property",
    _0: "filter",
    _1: v
  };
}

let Attrs = {
  viewBox: viewBox,
  fill: fill,
  stroke: stroke,
  strokeWidth: strokeWidth,
  strokeLinecap: strokeLinecap,
  strokeLinejoin: strokeLinejoin,
  strokeDasharray: strokeDasharray,
  strokeDashoffset: strokeDashoffset,
  strokeOpacity: strokeOpacity,
  fillOpacity: fillOpacity,
  fillRule: fillRule,
  opacity: opacity,
  transform: transform,
  d: d,
  x: x,
  y: y,
  x1: x1,
  y1: y1,
  x2: x2,
  y2: y2,
  cx: cx,
  cy: cy,
  r: r,
  rx: rx,
  ry: ry,
  width: width,
  height: height,
  points: points,
  offset: offset,
  stopColor: stopColor,
  stopOpacity: stopOpacity,
  gradientUnits: gradientUnits,
  textAnchor: textAnchor,
  dominantBaseline: dominantBaseline,
  fontSize: fontSize,
  fontFamily: fontFamily,
  fontWeight: fontWeight,
  in_: in_,
  in2: in2,
  result: result,
  stdDeviation: stdDeviation,
  dx: dx,
  dy: dy,
  xlinkHref: xlinkHref,
  clipPathRef: clipPathRef,
  maskRef: maskRef,
  filterRef: filterRef,
  class_: Tea_Vdom.class_,
  id: Tea_Vdom.id,
  style: Tea_Vdom.style
};

export {
  node,
  svg,
  g,
  defs,
  symbol,
  use,
  foreignObject,
  circle,
  ellipse,
  line,
  path,
  polygon,
  polyline,
  rect,
  text$p,
  tspan,
  textPath,
  linearGradient,
  radialGradient,
  stop,
  clipPath,
  mask,
  pattern,
  marker,
  filter,
  feGaussianBlur,
  feOffset,
  feBlend,
  feColorMatrix,
  feComposite,
  feFlood,
  feMerge,
  feMergeNode,
  animate,
  animateTransform,
  set,
  desc,
  title,
  metadata,
  image,
  Attrs,
}
/* No side effect */
