// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "./Tea_Sub.res.js";

function downs(tagger) {
  return Tea_Sub.registration("keyboard-downs", dispatch => {
    ((document.addEventListener("keydown", _handler)));
    return () => {
      ((document.removeEventListener("keydown", _handler)));
    };
  });
}

function ups(tagger) {
  return Tea_Sub.registration("keyboard-ups", dispatch => {
    ((document.addEventListener("keyup", _handler)));
    return () => {
      ((document.removeEventListener("keyup", _handler)));
    };
  });
}

function onKey(targetKey, msg) {
  return Tea_Sub.registration("keyboard-key-" + targetKey, dispatch => {
    ((document.addEventListener("keydown", _handler)));
    return () => {
      ((document.removeEventListener("keydown", _handler)));
    };
  });
}

function onShortcut(ctrlOpt, altOpt, shiftOpt, metaOpt, key, msg) {
  let ctrl = ctrlOpt !== undefined ? ctrlOpt : false;
  let alt = altOpt !== undefined ? altOpt : false;
  let shift = shiftOpt !== undefined ? shiftOpt : false;
  let meta = metaOpt !== undefined ? metaOpt : false;
  let id = `keyboard-shortcut-` + (
    ctrl ? "c" : ""
  ) + (
    alt ? "a" : ""
  ) + (
    shift ? "s" : ""
  ) + (
    meta ? "m" : ""
  ) + `-` + key;
  return Tea_Sub.registration(id, dispatch => {
    ((document.addEventListener("keydown", _handler)));
    return () => {
      ((document.removeEventListener("keydown", _handler)));
    };
  });
}

export {
  downs,
  ups,
  onKey,
  onShortcut,
}
/* No side effect */
