// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Vdom from "./Tea_Vdom.res.js";

function div(attrs, children) {
  return Tea_Vdom.node("div", attrs, children);
}

function span(attrs, children) {
  return Tea_Vdom.node("span", attrs, children);
}

function p(attrs, children) {
  return Tea_Vdom.node("p", attrs, children);
}

function br() {
  return {
    TAG: "Element",
    _0: "br",
    _1: [],
    _2: []
  };
}

function h1(attrs, children) {
  return Tea_Vdom.node("h1", attrs, children);
}

function h2(attrs, children) {
  return Tea_Vdom.node("h2", attrs, children);
}

function h3(attrs, children) {
  return Tea_Vdom.node("h3", attrs, children);
}

function h4(attrs, children) {
  return Tea_Vdom.node("h4", attrs, children);
}

function h5(attrs, children) {
  return Tea_Vdom.node("h5", attrs, children);
}

function h6(attrs, children) {
  return Tea_Vdom.node("h6", attrs, children);
}

function button(attrs, children) {
  return Tea_Vdom.node("button", attrs, children);
}

function input(attrs, children) {
  return Tea_Vdom.node("input", attrs, children);
}

function textarea(attrs, children) {
  return Tea_Vdom.node("textarea", attrs, children);
}

function label(attrs, children) {
  return Tea_Vdom.node("label", attrs, children);
}

function a(attrs, children) {
  return Tea_Vdom.node("a", attrs, children);
}

function img(attrs, children) {
  return Tea_Vdom.node("img", attrs, children);
}

function details(attrs, children) {
  return Tea_Vdom.node("details", attrs, children);
}

function summary(attrs, children) {
  return Tea_Vdom.node("summary", attrs, children);
}

function dialog(attrs, children) {
  return Tea_Vdom.node("dialog", attrs, children);
}

function ul(attrs, children) {
  return Tea_Vdom.node("ul", attrs, children);
}

function ol(attrs, children) {
  return Tea_Vdom.node("ol", attrs, children);
}

function li(attrs, children) {
  return Tea_Vdom.node("li", attrs, children);
}

function dl(attrs, children) {
  return Tea_Vdom.node("dl", attrs, children);
}

function dt(attrs, children) {
  return Tea_Vdom.node("dt", attrs, children);
}

function dd(attrs, children) {
  return Tea_Vdom.node("dd", attrs, children);
}

function form(attrs, children) {
  return Tea_Vdom.node("form", attrs, children);
}

function select(attrs, children) {
  return Tea_Vdom.node("select", attrs, children);
}

function option$p(attrs, children) {
  return Tea_Vdom.node("option", attrs, children);
}

function optgroup(attrs, children) {
  return Tea_Vdom.node("optgroup", attrs, children);
}

function fieldset(attrs, children) {
  return Tea_Vdom.node("fieldset", attrs, children);
}

function legend(attrs, children) {
  return Tea_Vdom.node("legend", attrs, children);
}

function datalist(attrs, children) {
  return Tea_Vdom.node("datalist", attrs, children);
}

function output(attrs, children) {
  return Tea_Vdom.node("output", attrs, children);
}

function progress(attrs, children) {
  return Tea_Vdom.node("progress", attrs, children);
}

function meter(attrs, children) {
  return Tea_Vdom.node("meter", attrs, children);
}

function header(attrs, children) {
  return Tea_Vdom.node("header", attrs, children);
}

function footer(attrs, children) {
  return Tea_Vdom.node("footer", attrs, children);
}

function main(attrs, children) {
  return Tea_Vdom.node("main", attrs, children);
}

function nav(attrs, children) {
  return Tea_Vdom.node("nav", attrs, children);
}

function section(attrs, children) {
  return Tea_Vdom.node("section", attrs, children);
}

function article(attrs, children) {
  return Tea_Vdom.node("article", attrs, children);
}

function aside(attrs, children) {
  return Tea_Vdom.node("aside", attrs, children);
}

function figure(attrs, children) {
  return Tea_Vdom.node("figure", attrs, children);
}

function figcaption(attrs, children) {
  return Tea_Vdom.node("figcaption", attrs, children);
}

function address(attrs, children) {
  return Tea_Vdom.node("address", attrs, children);
}

function time(attrs, children) {
  return Tea_Vdom.node("time", attrs, children);
}

function mark(attrs, children) {
  return Tea_Vdom.node("mark", attrs, children);
}

function table(attrs, children) {
  return Tea_Vdom.node("table", attrs, children);
}

function thead(attrs, children) {
  return Tea_Vdom.node("thead", attrs, children);
}

function tbody(attrs, children) {
  return Tea_Vdom.node("tbody", attrs, children);
}

function tfoot(attrs, children) {
  return Tea_Vdom.node("tfoot", attrs, children);
}

function tr(attrs, children) {
  return Tea_Vdom.node("tr", attrs, children);
}

function th(attrs, children) {
  return Tea_Vdom.node("th", attrs, children);
}

function td(attrs, children) {
  return Tea_Vdom.node("td", attrs, children);
}

function caption(attrs, children) {
  return Tea_Vdom.node("caption", attrs, children);
}

function colgroup(attrs, children) {
  return Tea_Vdom.node("colgroup", attrs, children);
}

function col(attrs, children) {
  return Tea_Vdom.node("col", attrs, children);
}

function pre(attrs, children) {
  return Tea_Vdom.node("pre", attrs, children);
}

function code(attrs, children) {
  return Tea_Vdom.node("code", attrs, children);
}

function strong(attrs, children) {
  return Tea_Vdom.node("strong", attrs, children);
}

function em(attrs, children) {
  return Tea_Vdom.node("em", attrs, children);
}

function small(attrs, children) {
  return Tea_Vdom.node("small", attrs, children);
}

function sub(attrs, children) {
  return Tea_Vdom.node("sub", attrs, children);
}

function sup(attrs, children) {
  return Tea_Vdom.node("sup", attrs, children);
}

function abbr(attrs, children) {
  return Tea_Vdom.node("abbr", attrs, children);
}

function blockquote(attrs, children) {
  return Tea_Vdom.node("blockquote", attrs, children);
}

function cite(attrs, children) {
  return Tea_Vdom.node("cite", attrs, children);
}

function del(attrs, children) {
  return Tea_Vdom.node("del", attrs, children);
}

function ins(attrs, children) {
  return Tea_Vdom.node("ins", attrs, children);
}

function kbd(attrs, children) {
  return Tea_Vdom.node("kbd", attrs, children);
}

function samp(attrs, children) {
  return Tea_Vdom.node("samp", attrs, children);
}

function $$var(attrs, children) {
  return Tea_Vdom.node("var", attrs, children);
}

function hr() {
  return {
    TAG: "Element",
    _0: "hr",
    _1: [],
    _2: []
  };
}

function audio(attrs, children) {
  return Tea_Vdom.node("audio", attrs, children);
}

function video(attrs, children) {
  return Tea_Vdom.node("video", attrs, children);
}

function source(attrs, children) {
  return Tea_Vdom.node("source", attrs, children);
}

function canvas(attrs, children) {
  return Tea_Vdom.node("canvas", attrs, children);
}

function picture(attrs, children) {
  return Tea_Vdom.node("picture", attrs, children);
}

function iframe(attrs, children) {
  return Tea_Vdom.node("iframe", attrs, children);
}

let Attrs = {
  class_: Tea_Vdom.class_,
  id: Tea_Vdom.id,
  style: Tea_Vdom.style,
  placeholder: Tea_Vdom.placeholder,
  value: Tea_Vdom.value,
  title: Tea_Vdom.title,
  href: Tea_Vdom.href,
  src: Tea_Vdom.src,
  alt: Tea_Vdom.alt,
  disabled: Tea_Vdom.disabled,
  checked: Tea_Vdom.checked,
  type_: Tea_Vdom.type_,
  name: Tea_Vdom.name,
  tabIndex: Tea_Vdom.tabIndex,
  noProp: Tea_Vdom.noProp,
  prop: Tea_Vdom.prop,
  for_: Tea_Vdom.for_,
  required: Tea_Vdom.required,
  readonly: Tea_Vdom.readonly,
  autofocus: Tea_Vdom.autofocus,
  autocomplete: Tea_Vdom.autocomplete,
  pattern: Tea_Vdom.pattern,
  multiple: Tea_Vdom.multiple,
  accept: Tea_Vdom.accept,
  min: Tea_Vdom.min,
  max: Tea_Vdom.max,
  step: Tea_Vdom.step,
  maxLength: Tea_Vdom.maxLength,
  minLength: Tea_Vdom.minLength,
  action: Tea_Vdom.action,
  method: Tea_Vdom.method,
  cols: Tea_Vdom.cols,
  rows: Tea_Vdom.rows,
  noValidate: Tea_Vdom.noValidate,
  width: Tea_Vdom.width,
  height: Tea_Vdom.height,
  target: Tea_Vdom.target,
  download: Tea_Vdom.download,
  rel: Tea_Vdom.rel,
  hidden: Tea_Vdom.hidden,
  draggable: Tea_Vdom.draggable,
  contentEditable: Tea_Vdom.contentEditable,
  spellCheck: Tea_Vdom.spellCheck,
  colspan: Tea_Vdom.colspan,
  rowspan: Tea_Vdom.rowspan,
  data_: Tea_Vdom.data_,
  ariaLabel: Tea_Vdom.ariaLabel,
  ariaLive: Tea_Vdom.ariaLive,
  ariaExpanded: Tea_Vdom.ariaExpanded,
  ariaHidden: Tea_Vdom.ariaHidden,
  ariaPressed: Tea_Vdom.ariaPressed,
  ariaCurrent: Tea_Vdom.ariaCurrent,
  ariaValueNow: Tea_Vdom.ariaValueNow,
  ariaValueMin: Tea_Vdom.ariaValueMin,
  ariaValueMax: Tea_Vdom.ariaValueMax,
  ariaDescribedBy: Tea_Vdom.ariaDescribedBy,
  ariaChecked: Tea_Vdom.ariaChecked,
  ariaSelected: Tea_Vdom.ariaSelected,
  ariaControls: Tea_Vdom.ariaControls,
  ariaLabelledBy: Tea_Vdom.ariaLabelledBy,
  ariaRequired: Tea_Vdom.ariaRequired,
  ariaInvalid: Tea_Vdom.ariaInvalid,
  ariaDisabled: Tea_Vdom.ariaDisabled,
  ariaSort: Tea_Vdom.ariaSort,
  ariaOrientation: Tea_Vdom.ariaOrientation,
  ariaModal: Tea_Vdom.ariaModal,
  role: Tea_Vdom.role,
  selected: Tea_Vdom.selected
};

let Events = {
  onClick: Tea_Vdom.onClick,
  onDoubleClick: Tea_Vdom.onDoubleClick,
  onContextMenu: Tea_Vdom.onContextMenu,
  onMouseDown: Tea_Vdom.onMouseDown,
  onMouseUp: Tea_Vdom.onMouseUp,
  onMouseEnter: Tea_Vdom.onMouseEnter,
  onMouseLeave: Tea_Vdom.onMouseLeave,
  onMouseOver: Tea_Vdom.onMouseOver,
  onMouseOut: Tea_Vdom.onMouseOut,
  onPointerDown: Tea_Vdom.onPointerDown,
  onPointerUp: Tea_Vdom.onPointerUp,
  onPointerMove: Tea_Vdom.onPointerMove,
  onPointerEnter: Tea_Vdom.onPointerEnter,
  onPointerLeave: Tea_Vdom.onPointerLeave,
  onPointerCancel: Tea_Vdom.onPointerCancel,
  onTouchStart: Tea_Vdom.onTouchStart,
  onTouchEnd: Tea_Vdom.onTouchEnd,
  onTouchMove: Tea_Vdom.onTouchMove,
  onTouchCancel: Tea_Vdom.onTouchCancel,
  onInput: Tea_Vdom.onInput,
  onChange: Tea_Vdom.onChange,
  onSubmit: Tea_Vdom.onSubmit,
  onReset: Tea_Vdom.onReset,
  onFocus: Tea_Vdom.onFocus,
  onBlur: Tea_Vdom.onBlur,
  onKeyDown: Tea_Vdom.onKeyDown,
  onKeyUp: Tea_Vdom.onKeyUp,
  onKeyPress: Tea_Vdom.onKeyPress,
  onDragStart: Tea_Vdom.onDragStart,
  onDrag: Tea_Vdom.onDrag,
  onDragEnd: Tea_Vdom.onDragEnd,
  onDragEnter: Tea_Vdom.onDragEnter,
  onDragLeave: Tea_Vdom.onDragLeave,
  onDragOver: Tea_Vdom.onDragOver,
  onDrop: Tea_Vdom.onDrop,
  onScroll: Tea_Vdom.onScroll,
  onAnimationEnd: Tea_Vdom.onAnimationEnd,
  onAnimationStart: Tea_Vdom.onAnimationStart,
  onTransitionEnd: Tea_Vdom.onTransitionEnd,
  onCopy: Tea_Vdom.onCopy,
  onCut: Tea_Vdom.onCut,
  onPaste: Tea_Vdom.onPaste,
  onWheel: Tea_Vdom.onWheel
};

let text = Tea_Vdom.text;

let node = Tea_Vdom.node;

let nodeA = Tea_Vdom.nodeA;

let keyed = Tea_Vdom.keyed;

let keyedA = Tea_Vdom.keyedA;

let fragment = Tea_Vdom.fragment;

let fragmentA = Tea_Vdom.fragmentA;

let noNode = {
  TAG: "Text",
  _0: ""
};

let map = Tea_Vdom.map;

export {
  text,
  node,
  nodeA,
  keyed,
  keyedA,
  fragment,
  fragmentA,
  noNode,
  div,
  span,
  p,
  br,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  button,
  input,
  textarea,
  label,
  a,
  img,
  details,
  summary,
  dialog,
  ul,
  ol,
  li,
  dl,
  dt,
  dd,
  form,
  select,
  option$p,
  optgroup,
  fieldset,
  legend,
  datalist,
  output,
  progress,
  meter,
  header,
  footer,
  main,
  nav,
  section,
  article,
  aside,
  figure,
  figcaption,
  address,
  time,
  mark,
  table,
  thead,
  tbody,
  tfoot,
  tr,
  th,
  td,
  caption,
  colgroup,
  col,
  pre,
  code,
  strong,
  em,
  small,
  sub,
  sup,
  abbr,
  blockquote,
  cite,
  del,
  ins,
  kbd,
  samp,
  $$var,
  hr,
  audio,
  video,
  source,
  canvas,
  picture,
  iframe,
  Attrs,
  Events,
  map,
}
/* No side effect */
