// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Cmd from "./Tea_Cmd.res.js";
import * as Tea_Sub from "./Tea_Sub.res.js";

function onResize(tagger) {
  return Tea_Sub.registration("window-resize", dispatch => {
    ((window.addEventListener("resize", _handler)));
    return () => {
      ((window.removeEventListener("resize", _handler)));
    };
  });
}

function onVisibilityChange(tagger) {
  return Tea_Sub.registration("window-visibility", dispatch => {
    ((document.addEventListener("visibilitychange", _handler)));
    return () => {
      ((document.removeEventListener("visibilitychange", _handler)));
    };
  });
}

function onFocus(msg) {
  return Tea_Sub.registration("window-focus", dispatch => {
    ((window.addEventListener("focus", _handler)));
    return () => {
      ((window.removeEventListener("focus", _handler)));
    };
  });
}

function onBlur(msg) {
  return Tea_Sub.registration("window-blur", dispatch => {
    ((window.addEventListener("blur", _handler)));
    return () => {
      ((window.removeEventListener("blur", _handler)));
    };
  });
}

function onScroll(tagger) {
  return Tea_Sub.registration("window-scroll", dispatch => {
    ((window.addEventListener("scroll", _handler, { passive: true })));
    return () => {
      ((window.removeEventListener("scroll", _handler)));
    };
  });
}

function onOnline(tagger) {
  return Tea_Sub.registration("window-online", dispatch => {
    ((window.addEventListener("online", _onlineHandler)));
    ((window.addEventListener("offline", _offlineHandler)));
    return () => {
      ((window.removeEventListener("online", _onlineHandler)));
      ((window.removeEventListener("offline", _offlineHandler)));
    };
  });
}

function onHashChange(tagger) {
  return Tea_Sub.registration("window-hashchange", dispatch => {
    ((window.addEventListener("hashchange", _handler)));
    return () => {
      ((window.removeEventListener("hashchange", _handler)));
    };
  });
}

function onPopState(msg) {
  return Tea_Sub.registration("window-popstate", dispatch => {
    ((window.addEventListener("popstate", _handler)));
    return () => {
      ((window.removeEventListener("popstate", _handler)));
    };
  });
}

function getSize(tagger) {
  return Tea_Cmd.call(callbacks => {
    let w = window.innerWidth;
    let h = window.innerHeight;
    callbacks.enqueue(tagger({
      width: w,
      height: h
    }));
  });
}

export {
  onResize,
  onVisibilityChange,
  onFocus,
  onBlur,
  onScroll,
  onOnline,
  onHashChange,
  onPopState,
  getSize,
}
/* No side effect */
