// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "./Tea_Sub.res.js";

function onAnimationFrame(tagger) {
  return Tea_Sub.registration("animation-frame", dispatch => {
    let id = {
      contents: 0
    };
    let callback = time => {
      dispatch(tagger(time));
      id.contents = requestAnimationFrame(callback);
    };
    id.contents = requestAnimationFrame(callback);
    return () => {
      cancelAnimationFrame(id.contents);
    };
  });
}

export {
  onAnimationFrame,
}
/* No side effect */
