// Generated by ReScript, PLEASE EDIT WITH CARE


function isVoidElement(tag) {
  switch (tag) {
    case "area" :
    case "base" :
    case "br" :
    case "col" :
    case "embed" :
    case "hr" :
    case "img" :
    case "input" :
    case "link" :
    case "meta" :
    case "param" :
    case "source" :
    case "track" :
    case "wbr" :
      return true;
    default:
      return false;
  }
}

function escapeHtml(s) {
  let r = s;
  r = r.replaceAll("&", "&amp;");
  r = r.replaceAll("<", "&lt;");
  r = r.replaceAll(">", "&gt;");
  r = r.replaceAll("\"", "&quot;");
  r = r.replaceAll("'", "&#x27;");
  return r;
}

function escapeAttr(s) {
  let r = s;
  r = r.replaceAll("&", "&amp;");
  r = r.replaceAll("\"", "&quot;");
  return r;
}

function renderAttr(attr) {
  switch (attr.TAG) {
    case "Property" :
      let key = attr._0;
      if (key === "") {
        return "";
      }
      let value = attr._1;
      if (key === "checked" || key === "disabled" || key === "readonly" || key === "required" || key === "autofocus" || key === "multiple" || key === "selected" || key === "hidden" || key === "novalidate") {
        if (value === "true") {
          return ` ` + key;
        } else {
          return "";
        }
      } else {
        return ` ` + key + `="` + escapeAttr(value) + `"`;
      }
    default:
      return "";
  }
}

function renderAttrs(attrs) {
  let propAttrs = {
    contents: ""
  };
  let styles = {
    contents: ""
  };
  attrs.forEach(attr => {
    if (attr.TAG !== "Style") {
      propAttrs.contents = propAttrs.contents + renderAttr(attr);
      return;
    }
    if (styles.contents.length > 0) {
      styles.contents = styles.contents + "; ";
    }
    styles.contents = styles.contents + attr._0 + ": " + attr._1;
  });
  if (styles.contents.length > 0) {
    return propAttrs.contents + (` style="` + escapeAttr(styles.contents) + `"`);
  } else {
    return propAttrs.contents;
  }
}

function toString(vdom) {
  switch (vdom.TAG) {
    case "Text" :
      return escapeHtml(vdom._0);
    case "Element" :
      let tag = vdom._0;
      let attrStr = renderAttrs(vdom._1);
      if (isVoidElement(tag)) {
        return `<` + tag + attrStr + ` />`;
      }
      let childrenStr = vdom._2.map(toString).join("");
      return `<` + tag + attrStr + `>` + childrenStr + `</` + tag + `>`;
    case "KeyedElement" :
      let tag$1 = vdom._0;
      let attrStr$1 = renderAttrs(vdom._1);
      if (isVoidElement(tag$1)) {
        return `<` + tag$1 + attrStr$1 + ` />`;
      }
      let childrenStr$1 = vdom._2.map(param => toString(param[1])).join("");
      return `<` + tag$1 + attrStr$1 + `>` + childrenStr$1 + `</` + tag$1 + `>`;
    case "Fragment" :
      return vdom._0.map(toString).join("");
  }
}

function toStringPretty(vdom, indentOpt) {
  let indent = indentOpt !== undefined ? indentOpt : 2;
  let indentStr = level => " ".repeat(level * indent | 0);
  let go = (v, level) => {
    switch (v.TAG) {
      case "Text" :
        return indentStr(level) + escapeHtml(v._0);
      case "Element" :
        let children = v._2;
        let tag = v._0;
        let attrStr = renderAttrs(v._1);
        let pad = indentStr(level);
        if (isVoidElement(tag)) {
          return pad + `<` + tag + attrStr + ` />`;
        }
        if (children.length === 0) {
          return pad + `<` + tag + attrStr + `></` + tag + `>`;
        }
        if (children.length === 1) {
          let s = children[0];
          if (s.TAG === "Text") {
            return pad + `<` + tag + attrStr + `>` + escapeHtml(s._0) + `</` + tag + `>`;
          }
          let childStr = go(s, level + 1 | 0);
          return pad + `<` + tag + attrStr + `>\n` + childStr + `\n` + pad + `</` + tag + `>`;
        }
        let childrenStr = children.map(c => go(c, level + 1 | 0)).join("\n");
        return pad + `<` + tag + attrStr + `>\n` + childrenStr + `\n` + pad + `</` + tag + `>`;
      case "KeyedElement" :
        let keyedChildren = v._2;
        let tag$1 = v._0;
        let attrStr$1 = renderAttrs(v._1);
        let pad$1 = indentStr(level);
        if (keyedChildren.length === 0) {
          return pad$1 + `<` + tag$1 + attrStr$1 + `></` + tag$1 + `>`;
        }
        let childrenStr$1 = keyedChildren.map(param => go(param[1], level + 1 | 0)).join("\n");
        return pad$1 + `<` + tag$1 + attrStr$1 + `>\n` + childrenStr$1 + `\n` + pad$1 + `</` + tag$1 + `>`;
      case "Fragment" :
        return v._0.map(c => go(c, level)).join("\n");
    }
  };
  return go(vdom, 0);
}

function toDocument(title, headOpt, vdom) {
  let head = headOpt !== undefined ? headOpt : "";
  let body = toString(vdom);
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>` + escapeHtml(title) + `</title>
  ` + head + `
</head>
<body>
  <div id="app">` + body + `</div>
</body>
</html>`;
}

export {
  isVoidElement,
  escapeHtml,
  escapeAttr,
  renderAttr,
  renderAttrs,
  toString,
  toStringPretty,
  toDocument,
}
/* No side effect */
