// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function text(s) {
  return {
    TAG: "Text",
    _0: s
  };
}

function node(tag, attrs, children) {
  return {
    TAG: "Element",
    _0: tag,
    _1: Stdlib_List.toArray(attrs),
    _2: Stdlib_List.toArray(children)
  };
}

function nodeA(tag, attrs, children) {
  return {
    TAG: "Element",
    _0: tag,
    _1: attrs,
    _2: children
  };
}

function keyed(tag, attrs, children) {
  return {
    TAG: "KeyedElement",
    _0: tag,
    _1: Stdlib_List.toArray(attrs),
    _2: Stdlib_List.toArray(children)
  };
}

function keyedA(tag, attrs, children) {
  return {
    TAG: "KeyedElement",
    _0: tag,
    _1: attrs,
    _2: children
  };
}

function fragment(children) {
  return {
    TAG: "Fragment",
    _0: Stdlib_List.toArray(children)
  };
}

function fragmentA(children) {
  return {
    TAG: "Fragment",
    _0: children
  };
}

function prop(key, value) {
  return {
    TAG: "Property",
    _0: key,
    _1: value
  };
}

function class_(name) {
  return {
    TAG: "Property",
    _0: "class",
    _1: name
  };
}

function id(name) {
  return {
    TAG: "Property",
    _0: "id",
    _1: name
  };
}

function style(prop, value) {
  return {
    TAG: "Style",
    _0: prop,
    _1: value
  };
}

function placeholder(text) {
  return {
    TAG: "Property",
    _0: "placeholder",
    _1: text
  };
}

function value(v) {
  return {
    TAG: "Property",
    _0: "value",
    _1: v
  };
}

function title(t) {
  return {
    TAG: "Property",
    _0: "title",
    _1: t
  };
}

function href(url) {
  return {
    TAG: "Property",
    _0: "href",
    _1: url
  };
}

function src(url) {
  return {
    TAG: "Property",
    _0: "src",
    _1: url
  };
}

function alt(text) {
  return {
    TAG: "Property",
    _0: "alt",
    _1: text
  };
}

function disabled(b) {
  return {
    TAG: "Property",
    _0: "disabled",
    _1: b ? "true" : "false"
  };
}

function checked(b) {
  return {
    TAG: "Property",
    _0: "checked",
    _1: b ? "true" : "false"
  };
}

function type_(t) {
  return {
    TAG: "Property",
    _0: "type",
    _1: t
  };
}

function name(n) {
  return {
    TAG: "Property",
    _0: "name",
    _1: n
  };
}

function tabIndex(i) {
  return {
    TAG: "Property",
    _0: "tabindex",
    _1: i.toString()
  };
}

function for_(id) {
  return {
    TAG: "Property",
    _0: "for",
    _1: id
  };
}

function required(b) {
  return {
    TAG: "Property",
    _0: "required",
    _1: b ? "true" : "false"
  };
}

function readonly(b) {
  return {
    TAG: "Property",
    _0: "readonly",
    _1: b ? "true" : "false"
  };
}

function autofocus(b) {
  return {
    TAG: "Property",
    _0: "autofocus",
    _1: b ? "true" : "false"
  };
}

function autocomplete(v) {
  return {
    TAG: "Property",
    _0: "autocomplete",
    _1: v
  };
}

function pattern(p) {
  return {
    TAG: "Property",
    _0: "pattern",
    _1: p
  };
}

function multiple(b) {
  return {
    TAG: "Property",
    _0: "multiple",
    _1: b ? "true" : "false"
  };
}

function accept(v) {
  return {
    TAG: "Property",
    _0: "accept",
    _1: v
  };
}

function min(v) {
  return {
    TAG: "Property",
    _0: "min",
    _1: v
  };
}

function max(v) {
  return {
    TAG: "Property",
    _0: "max",
    _1: v
  };
}

function step(v) {
  return {
    TAG: "Property",
    _0: "step",
    _1: v
  };
}

function maxLength(n) {
  return {
    TAG: "Property",
    _0: "maxlength",
    _1: n.toString()
  };
}

function minLength(n) {
  return {
    TAG: "Property",
    _0: "minlength",
    _1: n.toString()
  };
}

function action(url) {
  return {
    TAG: "Property",
    _0: "action",
    _1: url
  };
}

function method(m) {
  return {
    TAG: "Property",
    _0: "method",
    _1: m
  };
}

function cols(n) {
  return {
    TAG: "Property",
    _0: "cols",
    _1: n.toString()
  };
}

function rows(n) {
  return {
    TAG: "Property",
    _0: "rows",
    _1: n.toString()
  };
}

function noValidate(b) {
  return {
    TAG: "Property",
    _0: "novalidate",
    _1: b ? "true" : "false"
  };
}

function width(v) {
  return {
    TAG: "Property",
    _0: "width",
    _1: v
  };
}

function height(v) {
  return {
    TAG: "Property",
    _0: "height",
    _1: v
  };
}

function target(t) {
  return {
    TAG: "Property",
    _0: "target",
    _1: t
  };
}

function download(v) {
  return {
    TAG: "Property",
    _0: "download",
    _1: v
  };
}

function rel(r) {
  return {
    TAG: "Property",
    _0: "rel",
    _1: r
  };
}

function hidden(b) {
  return {
    TAG: "Property",
    _0: "hidden",
    _1: b ? "true" : "false"
  };
}

function draggable(b) {
  return {
    TAG: "Property",
    _0: "draggable",
    _1: b ? "true" : "false"
  };
}

function contentEditable(b) {
  return {
    TAG: "Property",
    _0: "contenteditable",
    _1: b ? "true" : "false"
  };
}

function spellCheck(b) {
  return {
    TAG: "Property",
    _0: "spellcheck",
    _1: b ? "true" : "false"
  };
}

function colspan(n) {
  return {
    TAG: "Property",
    _0: "colspan",
    _1: n.toString()
  };
}

function rowspan(n) {
  return {
    TAG: "Property",
    _0: "rowspan",
    _1: n.toString()
  };
}

function data_(key, value) {
  return {
    TAG: "Property",
    _0: "data-" + key,
    _1: value
  };
}

function ariaLabel(label) {
  return {
    TAG: "Property",
    _0: "aria-label",
    _1: label
  };
}

function ariaLive(mode) {
  return {
    TAG: "Property",
    _0: "aria-live",
    _1: mode
  };
}

function ariaExpanded(b) {
  return {
    TAG: "Property",
    _0: "aria-expanded",
    _1: b ? "true" : "false"
  };
}

function ariaHidden(b) {
  return {
    TAG: "Property",
    _0: "aria-hidden",
    _1: b ? "true" : "false"
  };
}

function ariaPressed(b) {
  return {
    TAG: "Property",
    _0: "aria-pressed",
    _1: b ? "true" : "false"
  };
}

function ariaCurrent(v) {
  return {
    TAG: "Property",
    _0: "aria-current",
    _1: v
  };
}

function ariaValueNow(v) {
  return {
    TAG: "Property",
    _0: "aria-valuenow",
    _1: v.toString()
  };
}

function ariaValueMin(v) {
  return {
    TAG: "Property",
    _0: "aria-valuemin",
    _1: v.toString()
  };
}

function ariaValueMax(v) {
  return {
    TAG: "Property",
    _0: "aria-valuemax",
    _1: v.toString()
  };
}

function ariaDescribedBy(id) {
  return {
    TAG: "Property",
    _0: "aria-describedby",
    _1: id
  };
}

function ariaChecked(b) {
  return {
    TAG: "Property",
    _0: "aria-checked",
    _1: b ? "true" : "false"
  };
}

function ariaSelected(b) {
  return {
    TAG: "Property",
    _0: "aria-selected",
    _1: b ? "true" : "false"
  };
}

function ariaControls(id) {
  return {
    TAG: "Property",
    _0: "aria-controls",
    _1: id
  };
}

function ariaLabelledBy(id) {
  return {
    TAG: "Property",
    _0: "aria-labelledby",
    _1: id
  };
}

function ariaRequired(b) {
  return {
    TAG: "Property",
    _0: "aria-required",
    _1: b ? "true" : "false"
  };
}

function ariaInvalid(b) {
  return {
    TAG: "Property",
    _0: "aria-invalid",
    _1: b ? "true" : "false"
  };
}

function ariaDisabled(b) {
  return {
    TAG: "Property",
    _0: "aria-disabled",
    _1: b ? "true" : "false"
  };
}

function ariaSort(v) {
  return {
    TAG: "Property",
    _0: "aria-sort",
    _1: v
  };
}

function ariaOrientation(v) {
  return {
    TAG: "Property",
    _0: "aria-orientation",
    _1: v
  };
}

function ariaModal(b) {
  return {
    TAG: "Property",
    _0: "aria-modal",
    _1: b ? "true" : "false"
  };
}

function role(r) {
  return {
    TAG: "Property",
    _0: "role",
    _1: r
  };
}

function selected(b) {
  return {
    TAG: "Property",
    _0: "selected",
    _1: b ? "true" : "false"
  };
}

function onClick(msg) {
  return {
    TAG: "Event",
    _0: "click",
    _1: () => msg
  };
}

function onDoubleClick(msg) {
  return {
    TAG: "Event",
    _0: "dblclick",
    _1: () => msg
  };
}

function onContextMenu(msg) {
  return {
    TAG: "EventPreventDefault",
    _0: "contextmenu",
    _1: () => msg
  };
}

function onMouseDown(msg) {
  return {
    TAG: "Event",
    _0: "mousedown",
    _1: () => msg
  };
}

function onMouseUp(msg) {
  return {
    TAG: "Event",
    _0: "mouseup",
    _1: () => msg
  };
}

function onMouseEnter(msg) {
  return {
    TAG: "Event",
    _0: "mouseenter",
    _1: () => msg
  };
}

function onMouseLeave(msg) {
  return {
    TAG: "Event",
    _0: "mouseleave",
    _1: () => msg
  };
}

function onMouseOver(msg) {
  return {
    TAG: "Event",
    _0: "mouseover",
    _1: () => msg
  };
}

function onMouseOut(msg) {
  return {
    TAG: "Event",
    _0: "mouseout",
    _1: () => msg
  };
}

function onPointerDown(msg) {
  return {
    TAG: "Event",
    _0: "pointerdown",
    _1: () => msg
  };
}

function onPointerUp(msg) {
  return {
    TAG: "Event",
    _0: "pointerup",
    _1: () => msg
  };
}

function onPointerMove(msg) {
  return {
    TAG: "Event",
    _0: "pointermove",
    _1: () => msg
  };
}

function onPointerEnter(msg) {
  return {
    TAG: "Event",
    _0: "pointerenter",
    _1: () => msg
  };
}

function onPointerLeave(msg) {
  return {
    TAG: "Event",
    _0: "pointerleave",
    _1: () => msg
  };
}

function onPointerCancel(msg) {
  return {
    TAG: "Event",
    _0: "pointercancel",
    _1: () => msg
  };
}

function onTouchStart(msg) {
  return {
    TAG: "Event",
    _0: "touchstart",
    _1: () => msg
  };
}

function onTouchEnd(msg) {
  return {
    TAG: "Event",
    _0: "touchend",
    _1: () => msg
  };
}

function onTouchMove(msg) {
  return {
    TAG: "Event",
    _0: "touchmove",
    _1: () => msg
  };
}

function onTouchCancel(msg) {
  return {
    TAG: "Event",
    _0: "touchcancel",
    _1: () => msg
  };
}

function onInput(handler) {
  return {
    TAG: "EventWithValue",
    _0: "input",
    _1: handler
  };
}

function onChange(handler) {
  return {
    TAG: "EventWithValue",
    _0: "change",
    _1: handler
  };
}

function onSubmit(msg) {
  return {
    TAG: "EventPreventDefault",
    _0: "submit",
    _1: () => msg
  };
}

function onReset(msg) {
  return {
    TAG: "Event",
    _0: "reset",
    _1: () => msg
  };
}

function onFocus(msg) {
  return {
    TAG: "Event",
    _0: "focus",
    _1: () => msg
  };
}

function onBlur(msg) {
  return {
    TAG: "Event",
    _0: "blur",
    _1: () => msg
  };
}

function onKeyDown(handler) {
  return {
    TAG: "EventWithKey",
    _0: "keydown",
    _1: handler
  };
}

function onKeyUp(handler) {
  return {
    TAG: "EventWithKey",
    _0: "keyup",
    _1: handler
  };
}

function onKeyPress(handler) {
  return {
    TAG: "EventWithKey",
    _0: "keypress",
    _1: handler
  };
}

function onDragStart(msg) {
  return {
    TAG: "Event",
    _0: "dragstart",
    _1: () => msg
  };
}

function onDrag(msg) {
  return {
    TAG: "Event",
    _0: "drag",
    _1: () => msg
  };
}

function onDragEnd(msg) {
  return {
    TAG: "Event",
    _0: "dragend",
    _1: () => msg
  };
}

function onDragEnter(msg) {
  return {
    TAG: "Event",
    _0: "dragenter",
    _1: () => msg
  };
}

function onDragLeave(msg) {
  return {
    TAG: "Event",
    _0: "dragleave",
    _1: () => msg
  };
}

function onDragOver(msg) {
  return {
    TAG: "EventPreventDefault",
    _0: "dragover",
    _1: () => msg
  };
}

function onDrop(msg) {
  return {
    TAG: "EventPreventDefault",
    _0: "drop",
    _1: () => msg
  };
}

function onScroll(msg) {
  return {
    TAG: "Event",
    _0: "scroll",
    _1: () => msg
  };
}

function onAnimationEnd(msg) {
  return {
    TAG: "Event",
    _0: "animationend",
    _1: () => msg
  };
}

function onAnimationStart(msg) {
  return {
    TAG: "Event",
    _0: "animationstart",
    _1: () => msg
  };
}

function onTransitionEnd(msg) {
  return {
    TAG: "Event",
    _0: "transitionend",
    _1: () => msg
  };
}

function onCopy(msg) {
  return {
    TAG: "Event",
    _0: "copy",
    _1: () => msg
  };
}

function onCut(msg) {
  return {
    TAG: "Event",
    _0: "cut",
    _1: () => msg
  };
}

function onPaste(msg) {
  return {
    TAG: "Event",
    _0: "paste",
    _1: () => msg
  };
}

function onWheel(msg) {
  return {
    TAG: "Event",
    _0: "wheel",
    _1: () => msg
  };
}

function map(vdom, f) {
  switch (vdom.TAG) {
    case "Text" :
      return {
        TAG: "Text",
        _0: vdom._0
      };
    case "Element" :
      return {
        TAG: "Element",
        _0: vdom._0,
        _1: vdom._1.map(attr => mapAttr(attr, f)),
        _2: vdom._2.map(child => map(child, f))
      };
    case "KeyedElement" :
      return {
        TAG: "KeyedElement",
        _0: vdom._0,
        _1: vdom._1.map(attr => mapAttr(attr, f)),
        _2: vdom._2.map(param => [
          param[0],
          map(param[1], f)
        ])
      };
    case "Fragment" :
      return {
        TAG: "Fragment",
        _0: vdom._0.map(child => map(child, f))
      };
  }
}

function mapAttr(attr, f) {
  switch (attr.TAG) {
    case "Property" :
      return {
        TAG: "Property",
        _0: attr._0,
        _1: attr._1
      };
    case "Style" :
      return {
        TAG: "Style",
        _0: attr._0,
        _1: attr._1
      };
    case "Event" :
      let handler = attr._1;
      return {
        TAG: "Event",
        _0: attr._0,
        _1: () => f(handler())
      };
    case "EventWithValue" :
      let handler$1 = attr._1;
      return {
        TAG: "EventWithValue",
        _0: attr._0,
        _1: v => f(handler$1(v))
      };
    case "EventWithKey" :
      let handler$2 = attr._1;
      return {
        TAG: "EventWithKey",
        _0: attr._0,
        _1: key => {
          let msg = handler$2(key);
          if (msg !== undefined) {
            return Primitive_option.some(f(Primitive_option.valFromOption(msg)));
          }
        }
      };
    case "EventPreventDefault" :
      let handler$3 = attr._1;
      return {
        TAG: "EventPreventDefault",
        _0: attr._0,
        _1: () => f(handler$3())
      };
    case "EventStopPropagation" :
      let handler$4 = attr._1;
      return {
        TAG: "EventStopPropagation",
        _0: attr._0,
        _1: () => f(handler$4())
      };
  }
}

let noProp = {
  TAG: "Property",
  _0: "",
  _1: ""
};

export {
  text,
  node,
  nodeA,
  keyed,
  keyedA,
  fragment,
  fragmentA,
  noProp,
  prop,
  class_,
  id,
  style,
  placeholder,
  value,
  title,
  href,
  src,
  alt,
  disabled,
  checked,
  type_,
  name,
  tabIndex,
  for_,
  required,
  readonly,
  autofocus,
  autocomplete,
  pattern,
  multiple,
  accept,
  min,
  max,
  step,
  maxLength,
  minLength,
  action,
  method,
  cols,
  rows,
  noValidate,
  width,
  height,
  target,
  download,
  rel,
  hidden,
  draggable,
  contentEditable,
  spellCheck,
  colspan,
  rowspan,
  data_,
  ariaLabel,
  ariaLive,
  ariaExpanded,
  ariaHidden,
  ariaPressed,
  ariaCurrent,
  ariaValueNow,
  ariaValueMin,
  ariaValueMax,
  ariaDescribedBy,
  ariaChecked,
  ariaSelected,
  ariaControls,
  ariaLabelledBy,
  ariaRequired,
  ariaInvalid,
  ariaDisabled,
  ariaSort,
  ariaOrientation,
  ariaModal,
  role,
  selected,
  onClick,
  onDoubleClick,
  onContextMenu,
  onMouseDown,
  onMouseUp,
  onMouseEnter,
  onMouseLeave,
  onMouseOver,
  onMouseOut,
  onPointerDown,
  onPointerUp,
  onPointerMove,
  onPointerEnter,
  onPointerLeave,
  onPointerCancel,
  onTouchStart,
  onTouchEnd,
  onTouchMove,
  onTouchCancel,
  onInput,
  onChange,
  onSubmit,
  onReset,
  onFocus,
  onBlur,
  onKeyDown,
  onKeyUp,
  onKeyPress,
  onDragStart,
  onDrag,
  onDragEnd,
  onDragEnter,
  onDragLeave,
  onDragOver,
  onDrop,
  onScroll,
  onAnimationEnd,
  onAnimationStart,
  onTransitionEnd,
  onCopy,
  onCut,
  onPaste,
  onWheel,
  map,
  mapAttr,
}
/* No side effect */
