// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "./Tea_Sub.res.js";

function every(intervalMs, tagger) {
  return Tea_Sub.registration("time-interval-" + intervalMs.toString(), dispatch => {
    let intervalId = setInterval(() => dispatch(tagger(Date.now())), intervalMs | 0);
    return () => {
      clearInterval(intervalId);
    };
  });
}

function after(delayMs, msg) {
  return Tea_Sub.registration("time-timeout-" + delayMs.toString(), dispatch => {
    let timeoutId = setTimeout(() => dispatch(msg), delayMs | 0);
    return () => {
      clearTimeout(timeoutId);
    };
  });
}

export {
  every,
  after,
}
/* No side effect */
