// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function msg(m) {
  return {
    TAG: "Msg",
    _0: m
  };
}

function batch(cmds) {
  let cmdArray = Stdlib_List.toArray(cmds);
  let match = cmdArray.length;
  if (match !== 0) {
    if (match !== 1) {
      return {
        TAG: "Batch",
        _0: cmdArray
      };
    } else {
      return cmdArray[0];
    }
  } else {
    return "None";
  }
}

function call(f) {
  return {
    TAG: "Call",
    _0: f
  };
}

function map(cmd, f) {
  if (typeof cmd !== "object") {
    return "None";
  }
  switch (cmd.TAG) {
    case "Msg" :
      return {
        TAG: "Msg",
        _0: f(cmd._0)
      };
    case "Batch" :
      return {
        TAG: "Batch",
        _0: cmd._0.map(c => map(c, f))
      };
    case "Call" :
      let callback = cmd._0;
      return {
        TAG: "Call",
        _0: callbacks => callback({
          enqueue: a => callbacks.enqueue(f(a))
        })
      };
  }
}

function execute(cmd, dispatch) {
  if (typeof cmd !== "object") {
    return;
  }
  switch (cmd.TAG) {
    case "Msg" :
      return dispatch(cmd._0);
    case "Batch" :
      cmd._0.forEach(c => execute(c, dispatch));
      return;
    case "Call" :
      return cmd._0({
        enqueue: dispatch
      });
  }
}

let none = "None";

export {
  none,
  msg,
  batch,
  call,
  map,
  execute,
}
/* No side effect */
