// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_App from "./Tea_App.res.js";
import * as Tea_Cmd from "./Tea_Cmd.res.js";

function program(init, update, view, subscriptions, msgToString, param) {
  let debugState = {
    history: [],
    currentIndex: -1,
    isTimeTravelling: false,
    msgToString: msgToString
  };
  let debugInit = () => {
    let match = init();
    debugState.currentIndex = 0;
    return [
      match[0],
      match[1]
    ];
  };
  let debugUpdate = (model, msg) => {
    if (debugState.isTimeTravelling) {
      return [
        model,
        Tea_Cmd.none
      ];
    }
    let match = update(model, msg);
    let newModel = match[0];
    if (debugState.currentIndex < (debugState.history.length - 1 | 0)) {
      debugState.history = debugState.history.slice(0, debugState.currentIndex + 1 | 0);
    }
    let entry_index = debugState.history.length;
    let entry_msgString = msgToString(msg);
    let entry_timestamp = Date.now();
    let entry = {
      index: entry_index,
      msg: msg,
      msgString: entry_msgString,
      model: newModel,
      timestamp: entry_timestamp
    };
    debugState.history.push(entry);
    debugState.currentIndex = debugState.history.length - 1 | 0;
    return [
      newModel,
      match[1]
    ];
  };
  let _program = Tea_App.standardProgram(debugInit, debugUpdate, view, subscriptions, undefined, undefined);
  ((globalThis.__tea_debug = {
      history: function() {
        var h = _debugState.history;
        console.group("TEA Debug History (" + h.length + " entries)");
        for (var i = 0; i < h.length; i++) {
          var marker = i === _debugState.currentIndex ? " <-- current" : "";
          console.log("#" + i + ": " + h[i].msgString + marker);
        }
        console.groupEnd();
        return h.length;
      },
      back: function() {
        if (_debugState.currentIndex > 0) {
          _debugState.isTimeTravelling = true;
          _debugState.currentIndex--;
          console.log("Back to #" + _debugState.currentIndex);
          _debugState.isTimeTravelling = false;
        }
      },
      forward: function() {
        if (_debugState.currentIndex < _debugState.history.length - 1) {
          _debugState.isTimeTravelling = true;
          _debugState.currentIndex++;
          console.log("Forward to #" + _debugState.currentIndex);
          _debugState.isTimeTravelling = false;
        }
      },
      goto: function(index) {
        if (index >= 0 && index < _debugState.history.length) {
          _debugState.isTimeTravelling = true;
          _debugState.currentIndex = index;
          console.log("Jumped to #" + index);
          _debugState.isTimeTravelling = false;
        }
      },
      model: function() {
        if (_debugState.currentIndex >= 0 && _debugState.currentIndex < _debugState.history.length) {
          return _debugState.history[_debugState.currentIndex].model;
        }
        return _program.getModel();
      },
      export: function() {
        return JSON.stringify(_debugState.history.map(function(e) {
          return { index: e.index, msg: e.msgString, timestamp: e.timestamp };
        }), null, 2);
      }
    }));
  console.log("TEA Debug enabled. Access via window.__tea_debug");
  return _program;
}

export {
  program,
}
/* No side effect */
