// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Sub from "./Tea_Sub.res.js";

function clicks(tagger) {
  return Tea_Sub.registration("mouse-clicks", dispatch => {
    ((document.addEventListener("click", _handler)));
    return () => {
      ((document.removeEventListener("click", _handler)));
    };
  });
}

function moves(tagger) {
  return Tea_Sub.registration("mouse-moves", dispatch => {
    ((document.addEventListener("mousemove", _handler)));
    return () => {
      ((document.removeEventListener("mousemove", _handler)));
    };
  });
}

function downs(tagger) {
  return Tea_Sub.registration("mouse-downs", dispatch => {
    ((document.addEventListener("mousedown", _handler)));
    return () => {
      ((document.removeEventListener("mousedown", _handler)));
    };
  });
}

function ups(tagger) {
  return Tea_Sub.registration("mouse-ups", dispatch => {
    ((document.addEventListener("mouseup", _handler)));
    return () => {
      ((document.removeEventListener("mouseup", _handler)));
    };
  });
}

export {
  clicks,
  moves,
  downs,
  ups,
}
/* No side effect */
