// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Cmd from "./Tea_Cmd.res.js";

function header(name, value) {
  return {
    name: name,
    value: value
  };
}

function errorToString(err) {
  if (typeof err !== "object") {
    if (err === "Timeout") {
      return "Request timed out";
    } else {
      return "Network error";
    }
  }
  switch (err.TAG) {
    case "BadUrl" :
      return `Bad URL: ` + err._0;
    case "BadStatus" :
      return `Bad status ` + err._0.toString() + `: ` + err._1.slice(0, 200);
    case "BadBody" :
      return `Bad body: ` + err._0;
  }
}

function sendFetch(method, url, headers, body, timeout, onResponse, onError) {
  return Tea_Cmd.call(callbacks => {
    (((function() {
        var init = { method: _method, headers: {} };
        for (var i = 0; i < _headers.length; i++) {
          init.headers[_headers[i].name] = _headers[i].value;
        }
        if (_body !== undefined) init.body = _body;

        var controller = new AbortController();
        init.signal = controller.signal;

        var timeoutId;
        if (_timeout !== undefined) {
          timeoutId = setTimeout(function() {
            controller.abort();
            _enqueue(_onError("timeout"));
          }, _timeout);
        }

        fetch(_url, init)
          .then(function(response) {
            if (timeoutId) clearTimeout(timeoutId);
            return response.text().then(function(text) {
              _enqueue(_onResponse(response.status, text));
            });
          })
          .catch(function(err) {
            if (timeoutId) clearTimeout(timeoutId);
            if (err.name !== 'AbortError') {
              _enqueue(_onError("network"));
            }
          });
      })()));
  });
}

function getString(url, headersOpt, timeout, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("GET", url, headers, undefined, timeout, (status, body) => {
    if (status >= 200 && status < 300) {
      return toMsg({
        TAG: "Ok",
        _0: body
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: body
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

function getJson(url, headersOpt, timeout, decoder, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("GET", url, headers, undefined, timeout, (status, body) => {
    if (!(status >= 200 && status < 300)) {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: body
        }
      });
    }
    let value = decoder(body);
    if (value.TAG === "Ok") {
      return toMsg({
        TAG: "Ok",
        _0: value._0
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadBody",
          _0: value._0
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

function postJson(url, headersOpt, body, timeout, decoder, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("POST", url, headers.concat([{
      name: "Content-Type",
      value: "application/json"
    }]), body, timeout, (status, responseBody) => {
    if (!(status >= 200 && status < 300)) {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: responseBody
        }
      });
    }
    let value = decoder(responseBody);
    if (value.TAG === "Ok") {
      return toMsg({
        TAG: "Ok",
        _0: value._0
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadBody",
          _0: value._0
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

function putJson(url, headersOpt, body, timeout, decoder, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("PUT", url, headers.concat([{
      name: "Content-Type",
      value: "application/json"
    }]), body, timeout, (status, responseBody) => {
    if (!(status >= 200 && status < 300)) {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: responseBody
        }
      });
    }
    let value = decoder(responseBody);
    if (value.TAG === "Ok") {
      return toMsg({
        TAG: "Ok",
        _0: value._0
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadBody",
          _0: value._0
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

function $$delete(url, headersOpt, timeout, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("DELETE", url, headers, undefined, timeout, (status, body) => {
    if (status >= 200 && status < 300) {
      return toMsg({
        TAG: "Ok",
        _0: body
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: body
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

function patchJson(url, headersOpt, body, timeout, decoder, toMsg) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return sendFetch("PATCH", url, headers.concat([{
      name: "Content-Type",
      value: "application/json"
    }]), body, timeout, (status, responseBody) => {
    if (!(status >= 200 && status < 300)) {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadStatus",
          _0: status,
          _1: responseBody
        }
      });
    }
    let value = decoder(responseBody);
    if (value.TAG === "Ok") {
      return toMsg({
        TAG: "Ok",
        _0: value._0
      });
    } else {
      return toMsg({
        TAG: "Error",
        _0: {
          TAG: "BadBody",
          _0: value._0
        }
      });
    }
  }, err => toMsg({
    TAG: "Error",
    _0: err === "timeout" ? "Timeout" : "NetworkError"
  }));
}

export {
  header,
  errorToString,
  sendFetch,
  getString,
  getJson,
  postJson,
  putJson,
  $$delete,
  patchJson,
}
/* No side effect */
