// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Cmd from "./Tea_Cmd.res.js";
import * as Tea_Sub from "./Tea_Sub.res.js";
import * as Tea_Render from "./Tea_Render.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let defaultSelector = "#app";

function standardProgram(init, update, view, subscriptions, mountSelectorOpt, param) {
  let mountSelector = mountSelectorOpt !== undefined ? mountSelectorOpt : defaultSelector;
  let match = init();
  let state = {
    model: match[0],
    currentSub: Tea_Sub.none,
    subscriptionCleanup: () => {},
    isDispatching: false,
    messageQueue: [],
    renderState: undefined,
    container: undefined
  };
  let dispatch = msg => {
    if (state.isDispatching) {
      state.messageQueue.push(msg);
      return;
    }
    state.isDispatching = true;
    processMessage(msg);
    while (state.messageQueue.length !== 0) {
      let queuedMsg = state.messageQueue.shift();
      if (queuedMsg !== undefined) {
        processMessage(Primitive_option.valFromOption(queuedMsg));
      }
    };
    state.isDispatching = false;
  };
  let processMessage = msg => {
    let match = update(state.model, msg);
    state.model = match[0];
    render();
    updateSubscriptions();
    Tea_Cmd.execute(match[1], dispatch);
  };
  let render = () => {
    let vdom = view(state.model);
    let match = state.container;
    let match$1 = state.renderState;
    if (match !== undefined) {
      let container = Primitive_option.valFromOption(match);
      if (match$1 !== undefined) {
        return Tea_Render.update(container, vdom, match$1);
      }
      let renderState = Tea_Render.createState(dispatch);
      Tea_Render.render(container, vdom, renderState);
      state.renderState = renderState;
      return;
    }
    let container$1 = Tea_Render.querySelector(mountSelector);
    if (container$1 !== undefined) {
      let container$2 = Primitive_option.valFromOption(container$1);
      let renderState$1 = Tea_Render.createState(dispatch);
      Tea_Render.render(container$2, vdom, renderState$1);
      state.renderState = renderState$1;
      state.container = Primitive_option.some(container$2);
      return;
    }
    console.warn(`Mount point not found: ` + mountSelector);
  };
  let updateSubscriptions = () => {
    let newSub = subscriptions(state.model);
    let oldKeys = Tea_Sub.getKeys(state.currentSub);
    let newKeys = Tea_Sub.getKeys(newSub);
    let changed = oldKeys.length !== newKeys.length || oldKeys.some(key => !newKeys.includes(key));
    if (changed) {
      state.subscriptionCleanup();
      state.currentSub = newSub;
      state.subscriptionCleanup = Tea_Sub.enable(newSub, dispatch);
      return;
    }
  };
  render();
  let initialSub = subscriptions(state.model);
  state.currentSub = initialSub;
  state.subscriptionCleanup = Tea_Sub.enable(initialSub, dispatch);
  Tea_Cmd.execute(match[1], dispatch);
  return {
    shutdown: () => state.subscriptionCleanup(),
    getModel: () => state.model
  };
}

function simpleProgram(init, update, view, mountSelectorOpt, param) {
  let mountSelector = mountSelectorOpt !== undefined ? mountSelectorOpt : defaultSelector;
  return standardProgram(init, update, view, param => Tea_Sub.none, mountSelector, undefined);
}

export {
  defaultSelector,
  standardProgram,
  simpleProgram,
}
/* No side effect */
