# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Joshua B. Jewell and Jonathan D.A. Jewell
# IDApTIK Sync Server Justfile

set shell := ["bash", "-uc"]

# Run the server
run:
    mix run --no-halt

# Build the project
build:
    mix compile

# Run tests
test:
    mix test

# Install dependencies
deps:
    mix deps.get

secret-scan-trufflehog:
    @command -v trufflehog >/dev/null && trufflehog filesystem . --only-verified || true
