// Generated by ReScript, PLEASE EDIT WITH CARE


function log(prim) {
  console.log(prim);
}

function error(prim) {
  console.error(prim);
}

function warn(prim) {
  console.warn(prim);
}

function info(prim) {
  console.info(prim);
}

var Env = {};

var Fs = {};

function now(prim) {
  return Date.now();
}

function createServer(portOpt, hostnameOpt, developmentOpt, handler) {
  var port = portOpt !== undefined ? portOpt : 8000;
  var hostname = hostnameOpt !== undefined ? hostnameOpt : "127.0.0.1";
  var development = developmentOpt !== undefined ? developmentOpt : false;
  return Bun.serve({
              port: port,
              hostname: hostname,
              fetch: handler,
              development: development
            });
}

var $$Request;

var $$Response;

var Url;

export {
  $$Request ,
  $$Response ,
  log ,
  error ,
  warn ,
  info ,
  Env ,
  Fs ,
  now ,
  Url ,
  createServer ,
}
/* No side effect */
