// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";

function make() {
  return {
          nodes: {},
          order: []
        };
}

function addNode(graph, id, name, param) {
  var nodeName = name !== undefined ? name : id;
  var match = Js_dict.get(graph.nodes, id);
  if (match !== undefined) {
    return ;
  } else {
    graph.nodes[id] = {
      id: id,
      name: nodeName,
      dependencies: undefined
    };
    return ;
  }
}

function addDependency(graph, fromId, toId) {
  var node = Js_dict.get(graph.nodes, fromId);
  if (node === undefined) {
    return ;
  }
  var newDeps = Belt_SetString.add(node.dependencies, toId);
  graph.nodes[fromId] = {
    id: node.id,
    name: node.name,
    dependencies: newDeps
  };
}

function resolveOrder(graph) {
  var visited = {
    contents: undefined
  };
  var order = [];
  var nodes = Js_dict.values(graph.nodes);
  var visit = function (nodeId) {
    if (Belt_SetString.has(visited.contents, nodeId)) {
      return ;
    }
    var node = graph.nodes[nodeId];
    visited.contents = Belt_SetString.add(visited.contents, nodeId);
    Belt_SetString.forEach(node.dependencies, (function (dep) {
            visit(dep);
          }));
    Js_array.push(nodeId, order);
  };
  Belt_Array.forEach(nodes, (function (node) {
          visit(node.id);
        }));
  return order;
}

export {
  make ,
  addNode ,
  addDependency ,
  resolveOrder ,
}
/* No side effect */
