// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "./Deno.res.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function cors(originOpt, methodsOpt, headersOpt, credentialsOpt, param) {
  var origin = originOpt !== undefined ? originOpt : "*";
  var methods = methodsOpt !== undefined ? methodsOpt : [
      "GET",
      "POST",
      "PUT",
      "DELETE",
      "PATCH",
      "OPTIONS"
    ];
  var headers = headersOpt !== undefined ? headersOpt : [
      "Content-Type",
      "Authorization"
    ];
  var credentials = credentialsOpt !== undefined ? credentialsOpt : false;
  return function (req, next) {
    var requestMethod = req.method;
    if (requestMethod !== "OPTIONS") {
      return next(req).then(function (response) {
                  return response;
                });
    }
    var headersDict = {};
    headersDict["Access-Control-Allow-Origin"] = origin;
    headersDict["Access-Control-Allow-Methods"] = methods.join(", ");
    headersDict["Access-Control-Allow-Headers"] = headers.join(", ");
    if (credentials) {
      headersDict["Access-Control-Allow-Credentials"] = "true";
    }
    return Promise.resolve($$Deno.$$Response.text("", 204, headersDict, undefined));
  };
}

function logger() {
  return function (req, next) {
    var method = req.method;
    var url = req.url;
    var start = Date.now();
    return next(req).then(function (response) {
                var duration = Date.now() - start;
                console.log(method + " " + url + " - " + duration.toString() + "ms");
                return response;
              });
  };
}

function jsonParser() {
  return function (req, next) {
    var method = req.method;
    if (method === "POST" || method === "PUT" || method === "PATCH") {
      return Core__Promise.$$catch(req.json().then(function (body) {
                      return next(req);
                    }), (function (param) {
                    return Promise.resolve($$Deno.$$Response.json(Js_dict.fromArray([[
                                          "error",
                                          "Invalid JSON"
                                        ]]), 400, undefined, undefined));
                  }));
    } else {
      return next(req);
    }
  };
}

function rateLimit(maxRequestsOpt, windowMsOpt, param) {
  var maxRequests = maxRequestsOpt !== undefined ? maxRequestsOpt : 100;
  var windowMs = windowMsOpt !== undefined ? windowMsOpt : 60000.0;
  var state = {
    requests: {},
    maxRequests: maxRequests,
    windowMs: windowMs
  };
  return function (req, next) {
    var url = req.url;
    var urlObj = new URL(url);
    var clientId = urlObj.pathname;
    var now = Date.now();
    var ts = Js_dict.get(state.requests, clientId);
    var timestamps = ts !== undefined ? Belt_Array.keep(ts, (function (t) {
              return now - t < state.windowMs;
            })) : [];
    if (timestamps.length >= state.maxRequests) {
      return Promise.resolve($$Deno.$$Response.json(Js_dict.fromArray([[
                            "error",
                            "Too many requests"
                          ]]), 429, undefined, undefined));
    } else {
      timestamps.push(now);
      state.requests[clientId] = timestamps;
      return next(req);
    }
  };
}

function auth(secret) {
  return function (req, next) {
    var headers = req.headers;
    var authHeader = Js_dict.get(headers, "authorization");
    if (authHeader !== undefined) {
      if (authHeader.startsWith("Bearer ")) {
        authHeader.slice(7);
        return next(req);
      } else {
        return Promise.resolve($$Deno.$$Response.json(Js_dict.fromArray([[
                              "error",
                              "Invalid authorization format"
                            ]]), 401, undefined, undefined));
      }
    } else {
      return Promise.resolve($$Deno.$$Response.json(Js_dict.fromArray([[
                            "error",
                            "No authorization header"
                          ]]), 401, undefined, undefined));
    }
  };
}

function compress() {
  return function (req, next) {
    return next(req);
  };
}

function errorHandler() {
  return function (req, next) {
    return Core__Promise.$$catch(next(req), (function (error) {
                  console.error(error);
                  return Promise.resolve($$Deno.$$Response.json(Js_dict.fromArray([
                                      [
                                        "error",
                                        "Internal server error"
                                      ],
                                      [
                                        "message",
                                        Belt_Option.getWithDefault(Belt_Option.flatMap(Caml_js_exceptions.as_js_exn(error), (function (prim) {
                                                    return prim.message;
                                                  })), "Unknown error")
                                      ]
                                    ]), 500, undefined, undefined));
                }));
  };
}

export {
  cors ,
  logger ,
  jsonParser ,
  rateLimit ,
  auth ,
  compress ,
  errorHandler ,
}
/* No side effect */
