// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "./Deno.res.mjs";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function make(notFoundHandler, param) {
  return {
          routes: [],
          notFoundHandler: notFoundHandler !== undefined ? notFoundHandler : (function (req) {
                return Promise.resolve($$Deno.$$Response.text("Not Found", 404, undefined, undefined));
              })
        };
}

function addRoute(router, method, pattern, handler) {
  Js_array.push({
        method: method,
        pattern: pattern,
        handler: handler
      }, router.routes);
}

function matchPath(pattern, path) {
  var patternParts = Belt_Array.keep(pattern.split("/"), (function (p) {
          return p !== "";
        }));
  var pathParts = Belt_Array.keep(path.split("/"), (function (p) {
          return p !== "";
        }));
  if (patternParts.length !== pathParts.length) {
    return ;
  }
  var params = {};
  var matches = true;
  for(var i = 0 ,i_finish = patternParts.length; i < i_finish; ++i){
    var patternPart = Belt_Array.getExn(patternParts, i);
    var pathPart = Belt_Array.getExn(pathParts, i);
    if (patternPart.startsWith(":")) {
      var key = patternPart.slice(1);
      params[key] = pathPart;
    } else if (patternPart !== pathPart) {
      matches = false;
    }
    
  }
  if (matches) {
    return params;
  }
  
}

async function handleRequest(router, request) {
  var url = new URL(request.url);
  var path = url.pathname;
  var methodStr = request.method;
  var methodEnum;
  switch (methodStr) {
    case "DELETE" :
        methodEnum = "DELETE";
        break;
    case "GET" :
        methodEnum = "GET";
        break;
    case "PATCH" :
        methodEnum = "PATCH";
        break;
    case "POST" :
        methodEnum = "POST";
        break;
    case "PUT" :
        methodEnum = "PUT";
        break;
    default:
      methodEnum = undefined;
  }
  if (methodEnum === undefined) {
    return Promise.resolve($$Deno.$$Response.text("Method not allowed", 405, undefined, undefined));
  }
  var _idx = 0;
  while(true) {
    var idx = _idx;
    if (idx >= router.routes.length) {
      return router.notFoundHandler(request);
    }
    var route = Belt_Array.getExn(router.routes, idx);
    if (route.method === methodEnum) {
      var params = matchPath(route.pattern, path);
      if (params !== undefined) {
        return route.handler(request, params);
      }
      _idx = idx + 1 | 0;
      continue ;
    }
    _idx = idx + 1 | 0;
    continue ;
  };
}

export {
  make ,
  addRoute ,
  matchPath ,
  handleRequest ,
}
/* No side effect */
