// Generated by ReScript, PLEASE EDIT WITH CARE


function start(handler, config) {
  var options_hostname = config.host;
  var options_port = config.port;
  var options_onListen = function (addr) {
    config.onListen({
          hostname: addr.hostname,
          port: addr.port
        });
  };
  var options = {
    hostname: options_hostname,
    port: options_port,
    onListen: options_onListen
  };
  Deno.serve(handler, options);
}

export {
  start ,
}
/* No side effect */
