// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function createStore(ttlOpt) {
  var ttl = ttlOpt !== undefined ? ttlOpt : 3600000.0;
  return {
          sessions: {
            contents: {}
          },
          ttl: ttl
        };
}

function generateSessionId() {
  var timestamp = Date.now().toString();
  var random = Math.random().toString();
  var random2 = Math.random().toString();
  return "sess_" + timestamp + "_" + random + "_" + random2;
}

function createSession(store) {
  var now = Date.now();
  var session_id = generateSessionId();
  var session_data = {};
  var session_expiresAt = now + store.ttl;
  var session = {
    id: session_id,
    data: session_data,
    createdAt: now,
    expiresAt: session_expiresAt
  };
  store.sessions.contents[session_id] = session;
  return session;
}

function getSession(store, id) {
  var session = Js_dict.get(store.sessions.contents, id);
  if (session === undefined) {
    return ;
  }
  var now = Date.now();
  if (now > session.expiresAt) {
    store.sessions.contents[id] = session;
    return ;
  } else {
    return session;
  }
}

function setSessionData(session, key, value) {
  session.data[key] = value;
}

function getSessionData(session, key) {
  return Js_dict.get(session.data, key);
}

function destroySession(store, id) {
  var newSessions = {};
  Js_dict.entries(store.sessions.contents).forEach(function (param) {
        var sessionId = param[0];
        if (sessionId !== id) {
          newSessions[sessionId] = param[1];
          return ;
        }
        
      });
  store.sessions.contents = newSessions;
}

function cleanupExpiredSessions(store) {
  var now = Date.now();
  var initialCount = Object.keys(store.sessions.contents).length;
  var newSessions = {};
  Js_dict.entries(store.sessions.contents).forEach(function (param) {
        var session = param[1];
        if (now <= session.expiresAt) {
          newSessions[param[0]] = session;
          return ;
        }
        
      });
  store.sessions.contents = newSessions;
  var finalCount = Object.keys(newSessions).length;
  return initialCount - finalCount | 0;
}

function extractSessionIdFromCookie(req) {
  var headers = req.headers;
  var cookieHeader = Js_dict.get(headers, "cookie");
  if (cookieHeader === undefined) {
    return ;
  }
  var cookies = cookieHeader.split(";");
  return Core__Array.findMap(cookies, (function (cookie) {
                var trimmed = cookie.trim();
                if (trimmed.startsWith("sessionId=")) {
                  return trimmed.slice(10);
                }
                
              }));
}

function sessionMiddleware(store) {
  return function (req, next) {
    var sessionId = extractSessionIdFromCookie(req);
    var session;
    if (sessionId !== undefined) {
      var s = getSession(store, sessionId);
      session = s !== undefined ? s : createSession(store);
    } else {
      session = createSession(store);
    }
    console.log("Session: " + session.id);
    return next(req).then(function (response) {
                return response;
              });
  };
}

function startCleanupInterval(store, intervalMsOpt) {
  var intervalMs = intervalMsOpt !== undefined ? intervalMsOpt : 300000.0;
  console.log("Session cleanup would run every " + intervalMs.toString() + "ms");
}

export {
  createStore ,
  generateSessionId ,
  createSession ,
  getSession ,
  setSessionData ,
  getSessionData ,
  destroySession ,
  cleanupExpiredSessions ,
  extractSessionIdFromCookie ,
  sessionMiddleware ,
  startCleanupInterval ,
}
/* No side effect */
