// Generated by ReScript, PLEASE EDIT WITH CARE


async function handleStream(_request) {
  var headersDict = {};
  headersDict["content-type"] = "application/octet-stream";
  var init = {
    status: 200,
    statusText: "OK",
    headers: headersDict
  };
  return Promise.resolve(new Response("", init));
}

async function handleSSE(_request) {
  var headersDict = {};
  headersDict["content-type"] = "text/event-stream";
  headersDict["cache-control"] = "no-cache";
  headersDict["connection"] = "keep-alive";
  var init = {
    status: 200,
    statusText: "OK",
    headers: headersDict
  };
  return Promise.resolve(new Response("", init));
}

export {
  handleStream ,
  handleSSE ,
}
/* No side effect */
