// Generated by ReScript, PLEASE EDIT WITH CARE


function cmd(f) {
  return {
          TAG: "Cmd",
          _0: f
        };
}

function batch(cmds) {
  return {
          TAG: "BatchCmd",
          _0: cmds
        };
}

function sub(key, subscribe) {
  return {
          TAG: "Sub",
          key: key,
          subscribe: subscribe
        };
}

function batchSub(subs) {
  return {
          TAG: "BatchSub",
          _0: subs
        };
}

function after(_ms, _msg) {
  return "NoCmd";
}

function random(_min, _max, _toMsg) {
  return "NoCmd";
}

function focus(_id) {
  return "NoCmd";
}

function every(_ms, _toMsg) {
  return "NoSub";
}

function onResize(_toMsg) {
  return "NoSub";
}

function onKeyDown(_toMsg) {
  return "NoSub";
}

function run(_program, _flags) {
  
}

function simple(init, update, view) {
  return {
          init: (function () {
              return [
                      init(),
                      "NoCmd"
                    ];
            }),
          update: (function (msg, model) {
              return [
                      update(msg, model),
                      "NoCmd"
                    ];
            }),
          view: view,
          subscriptions: (function (param) {
              return "NoSub";
            })
        };
}

var none = "NoCmd";

var noSub = "NoSub";

var Effect = {
  after: after,
  random: random,
  focus: focus
};

var Subscriptions = {
  every: every,
  onResize: onResize,
  onKeyDown: onKeyDown
};

export {
  none ,
  cmd ,
  batch ,
  noSub ,
  sub ,
  batchSub ,
  Effect ,
  Subscriptions ,
  run ,
  simple ,
}
/* No side effect */
