// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function attr(name, value) {
  return [
          name,
          value
        ];
}

function class_(value) {
  return [
          "class",
          value
        ];
}

function id(value) {
  return [
          "id",
          value
        ];
}

function style(value) {
  return [
          "style",
          value
        ];
}

function onClick(handler) {
  return [
          "click",
          handler
        ];
}

function onInput(handler) {
  return [
          "input",
          handler
        ];
}

function onSubmit(handler) {
  return [
          "submit",
          handler
        ];
}

function onChange(handler) {
  return [
          "change",
          handler
        ];
}

function onKeyDown(handler) {
  return [
          "keydown",
          handler
        ];
}

function onKeyUp(handler) {
  return [
          "keyup",
          handler
        ];
}

function text(s) {
  return {
          TAG: "Text",
          _0: s
        };
}

function el(tag, attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return {
          TAG: "Element",
          tag: tag,
          attrs: attrs,
          events: events,
          children: children
        };
}

function div(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("div", attrs, events, children);
}

function span(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("span", attrs, events, children);
}

function p(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("p", attrs, events, children);
}

function h1(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("h1", attrs, events, children);
}

function h2(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("h2", attrs, events, children);
}

function h3(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("h3", attrs, events, children);
}

function button(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("button", attrs, events, children);
}

function input(attrsOpt, eventsOpt) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("input", attrs, events, []);
}

function form(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("form", attrs, events, children);
}

function ul(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("ul", attrs, events, children);
}

function ol(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("ol", attrs, events, children);
}

function li(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("li", attrs, events, children);
}

function a(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("a", attrs, events, children);
}

function img(attrsOpt, eventsOpt) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("img", attrs, events, []);
}

function nav(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("nav", attrs, events, children);
}

function header(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("header", attrs, events, children);
}

function footer(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("footer", attrs, events, children);
}

function main(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("main", attrs, events, children);
}

function section(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("section", attrs, events, children);
}

function article(attrsOpt, eventsOpt, children) {
  var attrs = attrsOpt !== undefined ? attrsOpt : [];
  var events = eventsOpt !== undefined ? eventsOpt : [];
  return el("article", attrs, events, children);
}

function fragment(children) {
  return {
          TAG: "Fragment",
          _0: children
        };
}

function keyed(key, node) {
  return {
          TAG: "Keyed",
          _0: key,
          _1: node
        };
}

function render(_vnode) {
  while(true) {
    var vnode = _vnode;
    switch (vnode.TAG) {
      case "Text" :
          return document.createTextNode(vnode._0);
      case "Element" :
          var el = document.createElement(vnode.tag);
          vnode.attrs.forEach((function(el){
              return function (param) {
                el.setAttribute(param[0], param[1]);
              }
              }(el)));
          vnode.events.forEach((function(el){
              return function (param) {
                el.addEventListener(param[0], param[1]);
              }
              }(el)));
          vnode.children.forEach((function(el){
              return function (child) {
                el.appendChild(render(child));
              }
              }(el)));
          return el;
      case "Fragment" :
          var container = document.createElement("div");
          vnode._0.forEach((function(container){
              return function (child) {
                container.appendChild(render(child));
              }
              }(container)));
          return container;
      case "Keyed" :
          _vnode = vnode._1;
          continue ;
      
    }
  };
}

function mount(root, vnode) {
  var child = root.firstChild;
  if (!(child == null)) {
    root.removeChild(child);
  }
  root.appendChild(render(vnode));
}

function diff(oldNode, newNode) {
  switch (oldNode.TAG) {
    case "Text" :
        if (newNode.TAG === "Text" && oldNode._0 === newNode._0) {
          return "NoOp";
        } else {
          return {
                  TAG: "Replace",
                  _0: newNode
                };
        }
    case "Element" :
        if (newNode.TAG === "Element" && oldNode.tag === newNode.tag) {
          if (Caml_obj.notequal(oldNode.attrs, newNode.attrs)) {
            return {
                    TAG: "UpdateAttrs",
                    _0: newNode.attrs
                  };
          } else {
            return "NoOp";
          }
        } else {
          return {
                  TAG: "Replace",
                  _0: newNode
                };
        }
    case "Fragment" :
    case "Keyed" :
        return {
                TAG: "Replace",
                _0: newNode
              };
    
  }
}

function applyPatch(node, patch, newVnode) {
  if (typeof patch !== "object") {
    return node;
  }
  switch (patch.TAG) {
    case "Replace" :
        return render(newVnode);
    case "UpdateAttrs" :
        patch._0.forEach(function (param) {
              node.setAttribute(param[0], param[1]);
            });
        return node;
    case "Insert" :
        return render(patch._0);
    default:
      return node;
  }
}

export {
  attr ,
  class_ ,
  id ,
  style ,
  onClick ,
  onInput ,
  onSubmit ,
  onChange ,
  onKeyDown ,
  onKeyUp ,
  text ,
  el ,
  div ,
  span ,
  p ,
  h1 ,
  h2 ,
  h3 ,
  button ,
  input ,
  form ,
  ul ,
  ol ,
  li ,
  a ,
  img ,
  nav ,
  header ,
  footer ,
  main ,
  section ,
  article ,
  fragment ,
  keyed ,
  render ,
  mount ,
  diff ,
  applyPatch ,
}
/* No side effect */
