// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_typed_array from "rescript/lib/es6/js_typed_array.js";

function asUint8Array(memory) {
  return new Uint8Array(memory.buffer);
}

function copyToWasm(memory, offset, data) {
  var view = new Uint8Array(memory.buffer);
  var len = data.length;
  for(var i = 0; i < len; ++i){
    var $$byte = data[i];
    view[offset + i | 0] = $$byte;
  }
}

function copyFromWasm(memory, offset, len) {
  var view = new Uint8Array(memory.buffer);
  return Js_typed_array.$$Uint8Array.subarray(offset, offset + len | 0, view);
}

var Memory = {
  asUint8Array: asUint8Array,
  copyToWasm: copyToWasm,
  copyFromWasm: copyFromWasm
};

var Instance = {};

function fromExports($$exports) {
  var allocFn = exports.alloc;
  var freeFn = exports.free;
  var reallocFn = (exports.realloc ? exports.realloc : undefined);
  return {
          alloc: allocFn,
          free: freeFn,
          realloc: reallocFn
        };
}

var Allocator = {
  fromExports: fromExports
};

var Table = {};

var Module = {};

async function loadModule(path, imports, param) {
  var bytes = await Deno.readFile(path);
  var buffer = bytes.buffer;
  var module_ = await WebAssembly.compile(buffer);
  var importsObj = imports !== undefined ? Caml_option.valFromOption(imports) : ({});
  return Promise.resolve(await WebAssembly.instantiate(module_, importsObj));
}

export {
  Memory ,
  Instance ,
  Allocator ,
  Table ,
  Module ,
  loadModule ,
}
/* No side effect */
