// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tauri_Core from "./bindings/Tauri_Core.res.js";
import * as Tauri_Event from "./bindings/Tauri_Event.res.js";
import * as Tauri_Window from "./bindings/Tauri_Window.res.js";

var Core;

var $$Event;

var $$Window;

var Command;

var Fs;

var Dialog;

var Shell;

var $$Notification;

var Clipboard;

var invoke = Tauri_Core.invoke;

var listen = Tauri_Event.listen;

var emit = Tauri_Event.emit;

var getCurrentWindow = Tauri_Window.getCurrentWindow;

export {
  Core ,
  $$Event ,
  $$Window ,
  Command ,
  Fs ,
  Dialog ,
  Shell ,
  $$Notification ,
  Clipboard ,
  invoke ,
  listen ,
  emit ,
  getCurrentWindow ,
}
/* Tauri_Core Not a pure module */
