// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "/node_modules/@rescript/core/src/Core__Option.res.mjs";

function parse(url) {
  var match = url.split("#");
  var len = match.length;
  var match$1;
  if (len >= 3) {
    match$1 = [
      url,
      undefined
    ];
  } else {
    switch (len) {
      case 0 :
          match$1 = [
            url,
            undefined
          ];
          break;
      case 1 :
          var pq = match[0];
          match$1 = [
            pq,
            undefined
          ];
          break;
      case 2 :
          var pq$1 = match[0];
          var f = match[1];
          match$1 = [
            pq$1,
            f
          ];
          break;
      
    }
  }
  var pathAndQuery = match$1[0];
  var match$2 = pathAndQuery.split("?");
  var len$1 = match$2.length;
  var match$3;
  if (len$1 >= 3) {
    match$3 = [
      pathAndQuery,
      undefined
    ];
  } else {
    switch (len$1) {
      case 0 :
          match$3 = [
            pathAndQuery,
            undefined
          ];
          break;
      case 1 :
          var p = match$2[0];
          match$3 = [
            p,
            undefined
          ];
          break;
      case 2 :
          var p$1 = match$2[0];
          var q = match$2[1];
          match$3 = [
            p$1,
            q
          ];
          break;
      
    }
  }
  var path = match$3[0];
  var normalizedPath = path === "" ? "/" : (
      path.startsWith("/") ? (
          path.length > 1 && path.endsWith("/") ? path.slice(0, path.length - 1 | 0) : path
        ) : "/" + path
    );
  return {
          path: normalizedPath,
          query: match$3[1],
          fragment: match$1[1]
        };
}

function toString(param) {
  var queryPart = Core__Option.mapWithDefault(param.query, "", (function (q) {
          return "?" + q;
        }));
  var fragmentPart = Core__Option.mapWithDefault(param.fragment, "", (function (f) {
          return "#" + f;
        }));
  return param.path + queryPart + fragmentPart;
}

function current() {
  var match = typeof __unsafe_window === "undefined" ? undefined : __unsafe_window;
  if (match !== undefined) {
    return parse((window.location.pathname + window.location.search + window.location.hash));
  } else {
    return {
            path: "/",
            query: undefined,
            fragment: undefined
          };
  }
}

export {
  parse ,
  toString ,
  current ,
}
/* No side effect */
