// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Tauri_Core from "../bindings/Tauri_Core.res.js";
import * as Tauri_Event from "../bindings/Tauri_Event.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var internalError = "INTERNAL_ERROR";

var timeout = "TIMEOUT";

var serializationError = "SERIALIZATION_ERROR";

function make(code, message, details) {
  return {
          code: code,
          message: message,
          details: details
        };
}

function toString(err) {
  return "[" + err.code + "] " + err.message;
}

function isCode(err, code) {
  return err.code === code;
}

function fromExn(exn) {
  if (exn.RE_EXN_ID !== Js_exn.$$Error) {
    return {
            code: internalError,
            message: "Unknown exception",
            details: undefined
          };
  }
  var msg = Core__Option.getOr(exn._1.message, "Unknown error");
  return {
          code: internalError,
          message: msg,
          details: undefined
        };
}

var CommandError = {
  notFound: "NOT_FOUND",
  permissionDenied: "PERMISSION_DENIED",
  invalidInput: "INVALID_INPUT",
  internalError: internalError,
  timeout: timeout,
  networkError: "NETWORK_ERROR",
  serializationError: serializationError,
  make: make,
  toString: toString,
  isCode: isCode,
  fromExn: fromExn
};

function defineCommand(name, encode, decode) {
  return {
          name: name,
          encode: (function (args) {
              return encode(args);
            }),
          decode: decode
        };
}

function defineNoArgsCommand(name, decode) {
  return {
          name: name,
          encode: (function () {
              return {};
            }),
          decode: decode
        };
}

function defineVoidCommand(name, encode) {
  return {
          name: name,
          encode: encode,
          decode: (function (param) {
              return {
                      TAG: "Ok",
                      _0: undefined
                    };
            })
        };
}

async function execute(cmd, args) {
  try {
    var encodedArgs = cmd.encode(args);
    var response = await Tauri_Core.invoke(cmd.name, encodedArgs, undefined);
    var decoded = cmd.decode(response);
    if (decoded.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: decoded._0
            };
    } else {
      return {
              TAG: "Error",
              _0: {
                code: serializationError,
                message: decoded._0,
                details: undefined
              }
            };
    }
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    return {
            TAG: "Error",
            _0: fromExn(exn)
          };
  }
}

async function executeWithRetry(cmd, args, maxRetriesOpt, delayMsOpt) {
  var maxRetries = maxRetriesOpt !== undefined ? maxRetriesOpt : 3;
  var delayMs = delayMsOpt !== undefined ? delayMsOpt : 1000;
  var loop = async function (retriesLeft, lastError) {
    if (retriesLeft <= 0) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(lastError, {
                    code: internalError,
                    message: "Max retries exceeded",
                    details: undefined
                  })
            };
    }
    var result = await execute(cmd, args);
    if (result.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: result._0
            };
    }
    var err = result._0;
    if (retriesLeft > 1) {
      await new Promise((function (resolve, param) {
              setTimeout((function () {
                      resolve();
                    }), delayMs);
            }));
      return await loop(retriesLeft - 1 | 0, err);
    } else {
      return {
              TAG: "Error",
              _0: err
            };
    }
  };
  return await loop(maxRetries, undefined);
}

async function executeWithTimeout(cmd, args, timeoutMs) {
  var timeoutPromise = new Promise((function (resolve, param) {
          setTimeout((function () {
                  resolve({
                        TAG: "Error",
                        _0: {
                          code: timeout,
                          message: "Command timed out",
                          details: undefined
                        }
                      });
                }), timeoutMs);
        }));
  var commandPromise = execute(cmd, args);
  return await Promise.race([
              commandPromise,
              timeoutPromise
            ]);
}

async function executeAll(commands) {
  return await Promise.all(commands.map(function (cmd) {
                  return cmd();
                }));
}

async function executeSequential(commands) {
  var results = [];
  var error;
  var i = 0;
  while(i < commands.length && Core__Option.isNone(error)) {
    var cmd = Core__Option.getExn(commands[i], undefined);
    var result = await cmd();
    if (result.TAG === "Ok") {
      results.push(result._0);
    } else {
      error = result._0;
    }
    i = i + 1 | 0;
  };
  var err = error;
  if (err !== undefined) {
    return {
            TAG: "Error",
            _0: err
          };
  } else {
    return {
            TAG: "Ok",
            _0: results
          };
  }
}

async function executeWithProgress(cmd, args, progressEvent, onProgress) {
  var unlisten = await Tauri_Event.listen(progressEvent, (function ($$event) {
          onProgress($$event.payload);
        }));
  var result = await execute(cmd, args);
  unlisten();
  return result;
}

function make$1(cmd) {
  return {
          cmd: cmd,
          timeout: undefined,
          retries: undefined,
          retryDelay: undefined
        };
}

function withTimeout(builder, ms) {
  return {
          cmd: builder.cmd,
          timeout: ms,
          retries: builder.retries,
          retryDelay: builder.retryDelay
        };
}

function withRetries(builder, count, delayMsOpt) {
  var delayMs = delayMsOpt !== undefined ? delayMsOpt : 1000;
  return {
          cmd: builder.cmd,
          timeout: builder.timeout,
          retries: count,
          retryDelay: delayMs
        };
}

async function run(builder, args) {
  var timeout = builder.timeout;
  if (timeout !== undefined) {
    return await executeWithTimeout(builder.cmd, args, timeout);
  }
  var retries = builder.retries;
  if (retries !== undefined) {
    return await executeWithRetry(builder.cmd, args, retries, Core__Option.getOr(builder.retryDelay, 1000));
  } else {
    return await execute(builder.cmd, args);
  }
}

var Builder = {
  make: make$1,
  withTimeout: withTimeout,
  withRetries: withRetries,
  run: run
};

export {
  CommandError ,
  defineCommand ,
  defineNoArgsCommand ,
  defineVoidCommand ,
  execute ,
  executeWithRetry ,
  executeWithTimeout ,
  executeAll ,
  executeSequential ,
  executeWithProgress ,
  Builder ,
}
/* Tauri_Core Not a pure module */
