// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_App from "./Tea_App.res.mjs";
import * as Tea_Cmd from "./Tea_Cmd.res.mjs";

var Cmd;

var Sub;

var Html;

var Json;

var Http;

var Make = Tea_App.Make;

var MakeSimple = Tea_App.MakeSimple;

var MakeWithDispatch = Tea_App.MakeWithDispatch;

var none = Tea_Cmd.none;

var batch = Tea_Cmd.batch;

var Test;

export {
  Cmd ,
  Sub ,
  Html ,
  Json ,
  Http ,
  Make ,
  MakeSimple ,
  MakeWithDispatch ,
  none ,
  batch ,
  Test ,
}
/* Tea_App Not a pure module */
