// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "/vendor/esm/react.mjs";
import * as Tea_Cmd from "./Tea_Cmd.res.mjs";
import * as Tea_Sub from "./Tea_Sub.res.mjs";
import * as Belt_Array from "/node_modules/@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_SetString from "/node_modules/@rescript/runtime/lib/es6/Belt_SetString.js";

function diff(oldSubs, newSubs, dispatch, cleanups) {
  var oldInternals = Tea_Sub.toInternals(oldSubs);
  var newInternals = Tea_Sub.toInternals(newSubs);
  var oldKeys = Belt_Array.map(oldInternals, (function (s) {
          return s.key;
        }));
  var newKeys = Belt_Array.map(newInternals, (function (s) {
          return s.key;
        }));
  var oldKeySet = Belt_SetString.fromArray(oldKeys);
  var newKeySet = Belt_SetString.fromArray(newKeys);
  Belt_SetString.forEach(oldKeySet, (function (key) {
          if (Belt_SetString.has(newKeySet, key)) {
            return ;
          }
          var cleanup = cleanups[key];
          if (cleanup !== undefined) {
            cleanup();
            return (delete cleanups[key]);
          }
          
        }));
  Belt_Array.forEach(newInternals, (function (internal) {
          if (Belt_SetString.has(oldKeySet, internal.key)) {
            return ;
          }
          var cleanup = internal.setup(dispatch);
          if (cleanup !== undefined) {
            cleanups[internal.key] = cleanup;
            return ;
          }
          
        }));
}

function cleanupAll(cleanups) {
  var keys = Object.keys(cleanups);
  Belt_Array.forEach(keys, (function (key) {
          var cleanup = cleanups[key];
          if (cleanup !== undefined) {
            return cleanup();
          }
          
        }));
}

function Make(Config) {
  var make = function (flags) {
    var match = Config.app.init(flags);
    var initialCmd = match[1];
    var initialModel = match[0];
    var match$1 = React.useState(function () {
          return initialModel;
        });
    var setModel = match$1[1];
    var model = match$1[0];
    var modelRef = React.useRef(model);
    var subsRef = React.useRef(Tea_Sub.none);
    var cleanupsRef = React.useRef({});
    var dispatchRef = React.useRef(function (param) {
          
        });
    React.useEffect((function () {
            modelRef.current = model;
          }), [model]);
    var dispatch = React.useCallback((function (msg) {
            var currentModel = modelRef.current;
            var match = Config.app.update(msg, currentModel);
            var newModel = match[0];
            setModel(function (param) {
                  return newModel;
                });
            Tea_Cmd.execute(match[1], dispatchRef.current);
          }), []);
    React.useEffect((function () {
            dispatchRef.current = dispatch;
          }), []);
    React.useEffect((function () {
            Tea_Cmd.execute(initialCmd, dispatch);
          }), []);
    React.useEffect((function () {
            var oldSubs = subsRef.current;
            var newSubs = Config.app.subscriptions(model);
            diff(oldSubs, newSubs, dispatch, cleanupsRef.current);
            subsRef.current = newSubs;
          }), [model]);
    React.useEffect((function () {
            return (function () {
                      cleanupAll(cleanupsRef.current);
                    });
          }), []);
    return Config.app.view(model);
  };
  return {
          make: make
        };
}

function MakeWithDispatch(Config) {
  var make = function (flags) {
    var match = Config.init(flags);
    var initialCmd = match[1];
    var initialModel = match[0];
    var match$1 = React.useState(function () {
          return initialModel;
        });
    var setModel = match$1[1];
    var model = match$1[0];
    var modelRef = React.useRef(model);
    var subsRef = React.useRef(Tea_Sub.none);
    var cleanupsRef = React.useRef({});
    var dispatchRef = React.useRef(function (param) {
          
        });
    React.useEffect((function () {
            modelRef.current = model;
          }), [model]);
    var dispatch = React.useCallback((function (msg) {
            var currentModel = modelRef.current;
            var match = Config.update(msg, currentModel);
            var newModel = match[0];
            setModel(function (param) {
                  return newModel;
                });
            Tea_Cmd.execute(match[1], dispatchRef.current);
          }), []);
    React.useEffect((function () {
            dispatchRef.current = dispatch;
          }), []);
    React.useEffect((function () {
            Tea_Cmd.execute(initialCmd, dispatch);
          }), []);
    React.useEffect((function () {
            var oldSubs = subsRef.current;
            var newSubs = Config.subscriptions(model);
            diff(oldSubs, newSubs, dispatch, cleanupsRef.current);
            subsRef.current = newSubs;
          }), [model]);
    React.useEffect((function () {
            return (function () {
                      cleanupAll(cleanupsRef.current);
                    });
          }), []);
    return Config.view(model, dispatch);
  };
  return {
          make: make
        };
}

function MakeSimple(funarg) {
  var app_init = function () {
    return funarg.app.init();
  };
  var app_update = funarg.app.update;
  var app_view = funarg.app.view;
  var app_subscriptions = funarg.app.subscriptions;
  var make = function () {
    var flags;
    var match = app_init(flags);
    var initialCmd = match[1];
    var initialModel = match[0];
    var match$1 = React.useState(function () {
          return initialModel;
        });
    var setModel = match$1[1];
    var model = match$1[0];
    var modelRef = React.useRef(model);
    var subsRef = React.useRef(Tea_Sub.none);
    var cleanupsRef = React.useRef({});
    var dispatchRef = React.useRef(function (param) {
          
        });
    React.useEffect((function () {
            modelRef.current = model;
          }), [model]);
    var dispatch = React.useCallback((function (msg) {
            var currentModel = modelRef.current;
            var match = app_update(msg, currentModel);
            var newModel = match[0];
            setModel(function (param) {
                  return newModel;
                });
            Tea_Cmd.execute(match[1], dispatchRef.current);
          }), []);
    React.useEffect((function () {
            dispatchRef.current = dispatch;
          }), []);
    React.useEffect((function () {
            Tea_Cmd.execute(initialCmd, dispatch);
          }), []);
    React.useEffect((function () {
            var oldSubs = subsRef.current;
            var newSubs = app_subscriptions(model);
            diff(oldSubs, newSubs, dispatch, cleanupsRef.current);
            subsRef.current = newSubs;
          }), [model]);
    React.useEffect((function () {
            return (function () {
                      cleanupAll(cleanupsRef.current);
                    });
          }), []);
    return app_view(model);
  };
  return {
          make: make
        };
}

export {
  Make ,
  MakeSimple ,
  MakeWithDispatch ,
}
/* react Not a pure module */
