// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "/node_modules/@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "/node_modules/@rescript/runtime/lib/es6/Belt_Option.js";

function lengthToString(length) {
  if (typeof length !== "object") {
    switch (length) {
      case "MinContent" :
          return "min-content";
      case "MaxContent" :
          return "max-content";
      case "Auto" :
          return "auto";
      
    }
  } else {
    switch (length.TAG) {
      case "Px" :
          return String(length._0) + "px";
      case "Rem" :
          return String(length._0) + "rem";
      case "Em" :
          return String(length._0) + "em";
      case "Percent" :
          return String(length._0) + "%";
      case "Vh" :
          return String(length._0) + "vh";
      case "Vw" :
          return String(length._0) + "vw";
      case "Fr" :
          return String(length._0) + "fr";
      
    }
  }
}

function trackToString(track) {
  switch (track.TAG) {
    case "Fixed" :
        return lengthToString(track._0);
    case "MinMax" :
        return "minmax(" + lengthToString(track._0) + ", " + lengthToString(track._1) + ")";
    case "FitContent" :
        return "fit-content(" + lengthToString(track._0) + ")";
    case "Repeat" :
        return "repeat(" + String(track._0) + ", " + lengthToString(track._1) + ")";
    case "RepeatAutoFill" :
        return "repeat(auto-fill, " + lengthToString(track._0) + ")";
    case "RepeatAutoFit" :
        return "repeat(auto-fit, " + lengthToString(track._0) + ")";
    
  }
}

function flexDirectionToString(dir) {
  switch (dir) {
    case "Row" :
        return "row";
    case "RowReverse" :
        return "row-reverse";
    case "Column" :
        return "column";
    case "ColumnReverse" :
        return "column-reverse";
    
  }
}

function flexWrapToString(wrap) {
  switch (wrap) {
    case "NoWrap" :
        return "nowrap";
    case "Wrap" :
        return "wrap";
    case "WrapReverse" :
        return "wrap-reverse";
    
  }
}

function justifyContentToString(jc) {
  switch (jc) {
    case "FlexStart" :
        return "flex-start";
    case "FlexEnd" :
        return "flex-end";
    case "Center" :
        return "center";
    case "SpaceBetween" :
        return "space-between";
    case "SpaceAround" :
        return "space-around";
    case "SpaceEvenly" :
        return "space-evenly";
    
  }
}

function alignItemsToString(ai) {
  switch (ai) {
    case "AlignStretch" :
        return "stretch";
    case "AlignFlexStart" :
        return "flex-start";
    case "AlignFlexEnd" :
        return "flex-end";
    case "AlignCenter" :
        return "center";
    case "AlignBaseline" :
        return "baseline";
    
  }
}

function alignContentToString(ac) {
  switch (ac) {
    case "ContentStretch" :
        return "stretch";
    case "ContentFlexStart" :
        return "flex-start";
    case "ContentFlexEnd" :
        return "flex-end";
    case "ContentCenter" :
        return "center";
    case "ContentSpaceBetween" :
        return "space-between";
    case "ContentSpaceAround" :
        return "space-around";
    
  }
}

function gridLineToString(line) {
  if (typeof line !== "object") {
    return "auto";
  }
  switch (line.TAG) {
    case "LineNumber" :
        return String(line._0);
    case "LineSpan" :
        return "span " + String(line._0);
    case "LineName" :
        return line._0;
    
  }
}

function flexContainerStyle(config) {
  var style = {
    display: "flex"
  };
  var dir = config.direction;
  var style$1 = dir !== undefined ? Object.assign({}, style, {
          flexDirection: flexDirectionToString(dir)
        }) : style;
  var wrap = config.wrap;
  var style$2 = wrap !== undefined ? Object.assign({}, style$1, {
          flexWrap: flexWrapToString(wrap)
        }) : style$1;
  var jc = config.justifyContent;
  var style$3 = jc !== undefined ? Object.assign({}, style$2, {
          justifyContent: justifyContentToString(jc)
        }) : style$2;
  var ai = config.alignItems;
  var style$4 = ai !== undefined ? Object.assign({}, style$3, {
          alignItems: alignItemsToString(ai)
        }) : style$3;
  var ac = config.alignContent;
  var style$5 = ac !== undefined ? Object.assign({}, style$4, {
          alignContent: alignContentToString(ac)
        }) : style$4;
  var gap = config.gap;
  var style$6 = gap !== undefined ? Object.assign({}, style$5, {
          gap: lengthToString(gap)
        }) : style$5;
  var gap$1 = config.rowGap;
  var style$7 = gap$1 !== undefined ? Object.assign({}, style$6, {
          rowGap: lengthToString(gap$1)
        }) : style$6;
  var gap$2 = config.columnGap;
  if (gap$2 !== undefined) {
    return Object.assign({}, style$7, {
                columnGap: lengthToString(gap$2)
              });
  } else {
    return style$7;
  }
}

function flexItemStyle(config) {
  var style = {};
  var grow = config.grow;
  var style$1 = grow !== undefined ? Object.assign({}, style, {
          flexGrow: String(grow)
        }) : style;
  var shrink = config.shrink;
  var style$2 = shrink !== undefined ? Object.assign({}, style$1, {
          flexShrink: String(shrink)
        }) : style$1;
  var basis = config.basis;
  var style$3 = basis !== undefined ? Object.assign({}, style$2, {
          flexBasis: lengthToString(basis)
        }) : style$2;
  var align = config.alignSelf;
  var style$4 = align !== undefined ? Object.assign({}, style$3, {
          alignSelf: alignItemsToString(align)
        }) : style$3;
  var order = config.order;
  if (order !== undefined) {
    return Object.assign({}, style$4, {
                order: String(order)
              });
  } else {
    return style$4;
  }
}

function gridContainerStyle(config) {
  var style = {
    display: "grid"
  };
  var cols = config.templateColumns;
  var style$1;
  if (cols !== undefined) {
    var colStr = Belt_Array.joinWith(Belt_Array.map(cols, trackToString), " ", (function (x) {
            return x;
          }));
    style$1 = Object.assign({}, style, {
          gridTemplateColumns: colStr
        });
  } else {
    style$1 = style;
  }
  var rows = config.templateRows;
  var style$2;
  if (rows !== undefined) {
    var rowStr = Belt_Array.joinWith(Belt_Array.map(rows, trackToString), " ", (function (x) {
            return x;
          }));
    style$2 = Object.assign({}, style$1, {
          gridTemplateRows: rowStr
        });
  } else {
    style$2 = style$1;
  }
  var areas = config.templateAreas;
  var style$3;
  if (areas !== undefined) {
    var areasStr = Belt_Array.joinWith(Belt_Array.map(areas, (function (row) {
                return "\"" + row + "\"";
              })), " ", (function (x) {
            return x;
          }));
    style$3 = Object.assign({}, style$2, {
          gridTemplateAreas: areasStr
        });
  } else {
    style$3 = style$2;
  }
  var gap = config.gap;
  var style$4 = gap !== undefined ? Object.assign({}, style$3, {
          gap: lengthToString(gap)
        }) : style$3;
  var gap$1 = config.rowGap;
  var style$5 = gap$1 !== undefined ? Object.assign({}, style$4, {
          rowGap: lengthToString(gap$1)
        }) : style$4;
  var gap$2 = config.columnGap;
  var style$6 = gap$2 !== undefined ? Object.assign({}, style$5, {
          columnGap: lengthToString(gap$2)
        }) : style$5;
  var ji = config.justifyItems;
  var style$7 = ji !== undefined ? Object.assign({}, style$6, {
          justifyItems: justifyContentToString(ji)
        }) : style$6;
  var ai = config.alignItems;
  var style$8 = ai !== undefined ? Object.assign({}, style$7, {
          alignItems: alignItemsToString(ai)
        }) : style$7;
  var jc = config.justifyContent;
  var style$9 = jc !== undefined ? Object.assign({}, style$8, {
          justifyContent: justifyContentToString(jc)
        }) : style$8;
  var ac = config.alignContent;
  var style$10 = ac !== undefined ? Object.assign({}, style$9, {
          alignContent: alignContentToString(ac)
        }) : style$9;
  var flow = config.autoFlow;
  var style$11 = flow !== undefined ? Object.assign({}, style$10, {
          gridAutoFlow: flow
        }) : style$10;
  var rows$1 = config.autoRows;
  var style$12 = rows$1 !== undefined ? Object.assign({}, style$11, {
          gridAutoRows: lengthToString(rows$1)
        }) : style$11;
  var cols$1 = config.autoColumns;
  if (cols$1 !== undefined) {
    return Object.assign({}, style$12, {
                gridAutoColumns: lengthToString(cols$1)
              });
  } else {
    return style$12;
  }
}

function gridItemStyle(config) {
  var style = {};
  var match = config.placement;
  var style$1;
  if (match !== undefined) {
    var columnEnd = match.columnEnd;
    var columnStart = match.columnStart;
    var rowEnd = match.rowEnd;
    var rowStart = match.rowStart;
    var style$2 = rowStart !== undefined ? Object.assign({}, style, {
            gridRowStart: gridLineToString(rowStart)
          }) : style;
    var style$3 = rowEnd !== undefined ? Object.assign({}, style$2, {
            gridRowEnd: gridLineToString(rowEnd)
          }) : style$2;
    var style$4 = columnStart !== undefined ? Object.assign({}, style$3, {
            gridColumnStart: gridLineToString(columnStart)
          }) : style$3;
    style$1 = columnEnd !== undefined ? Object.assign({}, style$4, {
            gridColumnEnd: gridLineToString(columnEnd)
          }) : style$4;
  } else {
    style$1 = style;
  }
  var area = config.area;
  var style$5 = area !== undefined ? Object.assign({}, style$1, {
          gridArea: area
        }) : style$1;
  var js = config.justifySelf;
  var style$6 = js !== undefined ? Object.assign({}, style$5, {
          justifySelf: justifyContentToString(js)
        }) : style$5;
  var as_ = config.alignSelf;
  if (as_ !== undefined) {
    return Object.assign({}, style$6, {
                alignSelf: alignItemsToString(as_)
              });
  } else {
    return style$6;
  }
}

function quadrantContainerStyle(config) {
  var baseStyle = {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    gridTemplateAreas: "\"tl tr\" \"bl br\""
  };
  var gap = config.gap;
  var style = gap !== undefined ? Object.assign({}, baseStyle, {
          gap: lengthToString(gap)
        }) : baseStyle;
  var height = config.minCellHeight;
  var style$1 = height !== undefined ? Object.assign({}, style, {
          minHeight: "calc(" + lengthToString(height) + " * 2)"
        }) : style;
  var ratio = config.aspectRatio;
  if (ratio !== undefined) {
    return Object.assign({}, style$1, {
                aspectRatio: ratio
              });
  } else {
    return style$1;
  }
}

function quadrantToArea(q) {
  switch (q) {
    case "TopLeft" :
        return "tl";
    case "TopRight" :
        return "tr";
    case "BottomLeft" :
        return "bl";
    case "BottomRight" :
        return "br";
    
  }
}

function quadrantCellStyle(position) {
  return {
          gridArea: quadrantToArea(position)
        };
}

function dashboardContainerStyle(config) {
  var hasFooter = Belt_Option.isSome(config.footerHeight);
  var fh = config.footerHeight;
  var rowTemplate = fh !== undefined ? lengthToString(config.headerHeight) + " 1fr " + lengthToString(fh) : lengthToString(config.headerHeight) + " 1fr";
  var areasTemplate = hasFooter ? "\"header header\" \"sidebar main\" \"footer footer\"" : "\"header header\" \"sidebar main\"";
  var baseStyle = {
    display: "grid",
    gridTemplateColumns: lengthToString(config.sidebarWidth) + " 1fr",
    gridTemplateRows: rowTemplate,
    gridTemplateAreas: areasTemplate,
    minHeight: "100vh"
  };
  var gap = config.gap;
  if (gap !== undefined) {
    return Object.assign({}, baseStyle, {
                gap: lengthToString(gap)
              });
  } else {
    return baseStyle;
  }
}

function dashboardAreaToString(area) {
  switch (area) {
    case "Header" :
        return "header";
    case "Sidebar" :
        return "sidebar";
    case "Main" :
        return "main";
    case "Footer" :
        return "footer";
    
  }
}

function dashboardAreaStyle(area) {
  return {
          gridArea: dashboardAreaToString(area)
        };
}

function breakpointToPx(bp) {
  switch (bp) {
    case "Sm" :
        return 640;
    case "Md" :
        return 768;
    case "Lg" :
        return 1024;
    case "Xl" :
        return 1280;
    case "Xxl" :
        return 1536;
    
  }
}

function flexRow(gapOpt, justifyOpt, alignOpt, param) {
  var gap = gapOpt !== undefined ? gapOpt : ({
        TAG: "Px",
        _0: 8
      });
  var justify = justifyOpt !== undefined ? justifyOpt : "FlexStart";
  var align = alignOpt !== undefined ? alignOpt : "AlignCenter";
  return flexContainerStyle({
              direction: "Row",
              wrap: undefined,
              justifyContent: justify,
              alignItems: align,
              alignContent: undefined,
              gap: gap,
              rowGap: undefined,
              columnGap: undefined
            });
}

function flexColumn(gapOpt, justifyOpt, alignOpt, param) {
  var gap = gapOpt !== undefined ? gapOpt : ({
        TAG: "Px",
        _0: 8
      });
  var justify = justifyOpt !== undefined ? justifyOpt : "FlexStart";
  var align = alignOpt !== undefined ? alignOpt : "AlignStretch";
  return flexContainerStyle({
              direction: "Column",
              wrap: undefined,
              justifyContent: justify,
              alignItems: align,
              alignContent: undefined,
              gap: gap,
              rowGap: undefined,
              columnGap: undefined
            });
}

function equalColumns(count, gapOpt, param) {
  var gap = gapOpt !== undefined ? gapOpt : ({
        TAG: "Px",
        _0: 16
      });
  return gridContainerStyle({
              templateColumns: Belt_Array.make(count, {
                    TAG: "Fixed",
                    _0: {
                      TAG: "Fr",
                      _0: 1.0
                    }
                  }),
              templateRows: undefined,
              templateAreas: undefined,
              gap: gap,
              rowGap: undefined,
              columnGap: undefined,
              justifyItems: undefined,
              alignItems: undefined,
              justifyContent: undefined,
              alignContent: undefined,
              autoFlow: undefined,
              autoRows: undefined,
              autoColumns: undefined
            });
}

function autoFitGrid(minWidth, gapOpt, param) {
  var gap = gapOpt !== undefined ? gapOpt : ({
        TAG: "Px",
        _0: 16
      });
  return gridContainerStyle({
              templateColumns: [{
                  TAG: "RepeatAutoFit",
                  _0: minWidth
                }],
              templateRows: undefined,
              templateAreas: undefined,
              gap: gap,
              rowGap: undefined,
              columnGap: undefined,
              justifyItems: undefined,
              alignItems: undefined,
              justifyContent: undefined,
              alignContent: undefined,
              autoFlow: undefined,
              autoRows: undefined,
              autoColumns: undefined
            });
}

function centered() {
  return flexContainerStyle({
              direction: undefined,
              wrap: undefined,
              justifyContent: "Center",
              alignItems: "AlignCenter",
              alignContent: undefined,
              gap: undefined,
              rowGap: undefined,
              columnGap: undefined
            });
}

function spaceBetweenRow(alignOpt, param) {
  var align = alignOpt !== undefined ? alignOpt : "AlignCenter";
  return flexContainerStyle({
              direction: "Row",
              wrap: undefined,
              justifyContent: "SpaceBetween",
              alignItems: align,
              alignContent: undefined,
              gap: undefined,
              rowGap: undefined,
              columnGap: undefined
            });
}

function combineStyles(styles) {
  return Belt_Array.reduce(styles, {}, (function (acc, s) {
                return Object.assign({}, acc, s);
              }));
}

function withSize(style, width, height, param) {
  var style$1 = width !== undefined ? Object.assign({}, style, {
          width: lengthToString(width)
        }) : style;
  if (height !== undefined) {
    return Object.assign({}, style$1, {
                height: lengthToString(height)
              });
  } else {
    return style$1;
  }
}

function withPadding(style, padding) {
  return Object.assign({}, style, {
              padding: lengthToString(padding)
            });
}

function withMargin(style, margin) {
  return Object.assign({}, style, {
              margin: lengthToString(margin)
            });
}

function withBackground(style, color) {
  return Object.assign({}, style, {
              backgroundColor: color
            });
}

function withBorderRadius(style, radius) {
  return Object.assign({}, style, {
              borderRadius: lengthToString(radius)
            });
}

var defaultFlexConfig = {
  direction: undefined,
  wrap: undefined,
  justifyContent: undefined,
  alignItems: undefined,
  alignContent: undefined,
  gap: undefined,
  rowGap: undefined,
  columnGap: undefined
};

var defaultFlexItemConfig = {
  grow: undefined,
  shrink: undefined,
  basis: undefined,
  alignSelf: undefined,
  order: undefined
};

var defaultGridConfig = {
  templateColumns: undefined,
  templateRows: undefined,
  templateAreas: undefined,
  gap: undefined,
  rowGap: undefined,
  columnGap: undefined,
  justifyItems: undefined,
  alignItems: undefined,
  justifyContent: undefined,
  alignContent: undefined,
  autoFlow: undefined,
  autoRows: undefined,
  autoColumns: undefined
};

var defaultGridItemConfig = {
  placement: undefined,
  area: undefined,
  justifySelf: undefined,
  alignSelf: undefined
};

var defaultQuadrantConfig = {
  gap: {
    TAG: "Px",
    _0: 16
  },
  minCellHeight: {
    TAG: "Px",
    _0: 200
  },
  aspectRatio: undefined
};

var defaultDashboardConfig = {
  headerHeight: {
    TAG: "Px",
    _0: 64
  },
  sidebarWidth: {
    TAG: "Px",
    _0: 250
  },
  footerHeight: undefined,
  gap: {
    TAG: "Px",
    _0: 0
  }
};

export {
  lengthToString ,
  trackToString ,
  defaultFlexConfig ,
  defaultFlexItemConfig ,
  defaultGridConfig ,
  defaultGridItemConfig ,
  flexContainerStyle ,
  flexItemStyle ,
  gridContainerStyle ,
  gridItemStyle ,
  defaultQuadrantConfig ,
  quadrantContainerStyle ,
  quadrantToArea ,
  quadrantCellStyle ,
  defaultDashboardConfig ,
  dashboardContainerStyle ,
  dashboardAreaToString ,
  dashboardAreaStyle ,
  breakpointToPx ,
  flexRow ,
  flexColumn ,
  equalColumns ,
  autoFitGrid ,
  centered ,
  spaceBetweenRow ,
  combineStyles ,
  withSize ,
  withPadding ,
  withMargin ,
  withBackground ,
  withBorderRadius ,
}
/* No side effect */
