// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "/node_modules/@rescript/runtime/lib/es6/Js_exn.js";
import * as Tea_Cmd from "./Tea_Cmd.res.mjs";
import * as Caml_obj from "/node_modules/rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "/node_modules/@rescript/runtime/lib/es6/Belt_Array.js";

function simulate(init, update, msgs) {
  var match = init();
  return Belt_Array.reduce(msgs, match[0], (function (model, msg) {
                return update(msg, model)[0];
              }));
}

function simulateWithFlags(init, update, flags, msgs) {
  var match = init(flags);
  return Belt_Array.reduce(msgs, match[0], (function (model, msg) {
                return update(msg, model)[0];
              }));
}

function collectCmds(init, update, msgs) {
  var match = init();
  return Belt_Array.reduce(msgs, [
                match[0],
                [match[1]]
              ], (function (param, msg) {
                  var match = update(msg, param[0]);
                  return [
                          match[0],
                          Belt_Array.concat(param[1], [match[1]])
                        ];
                }))[1];
}

function step(update, model, msg) {
  var match = update(msg, model);
  return {
          model: match[0],
          cmd: match[1]
        };
}

function steps(init, update, msgs) {
  var match = init();
  var initialModel = match[0];
  var initialStep_cmd = match[1];
  var initialStep = {
    model: initialModel,
    cmd: initialStep_cmd
  };
  return Belt_Array.reduce(msgs, [
                initialModel,
                [initialStep]
              ], (function (param, msg) {
                  var match = update(msg, param[0]);
                  var newModel = match[0];
                  var step_cmd = match[1];
                  var step = {
                    model: newModel,
                    cmd: step_cmd
                  };
                  return [
                          newModel,
                          Belt_Array.concat(param[1], [step])
                        ];
                }))[1];
}

function expectModel(model, predicate, message) {
  if (!predicate(model)) {
    return Js_exn.raiseError("Assertion failed: " + message);
  }
  
}

function assertEqual(actual, expected, message) {
  if (Caml_obj.notequal(actual, expected)) {
    return Js_exn.raiseError("Assertion failed: " + message);
  }
  
}

function isNone(cmd) {
  return cmd === Tea_Cmd.none;
}

function isBatch(cmd) {
  var match = typeof cmd;
  if (match !== "object") {
    return false;
  }
  var match$1 = cmd.TAG;
  return match$1 === 1;
}

export {
  simulate ,
  simulateWithFlags ,
  collectCmds ,
  step ,
  steps ,
  expectModel ,
  assertEqual ,
  isNone ,
  isBatch ,
}
/* No side effect */
