// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "/node_modules/@rescript/runtime/lib/es6/Belt_Array.js";
import * as Core__Promise from "/node_modules/@rescript/core/src/Core__Promise.res.mjs";
import * as Caml_js_exceptions from "/node_modules/@rescript/runtime/lib/es6/Primitive_exceptions.js";

function batch(cmds) {
  var filtered = Belt_Array.keep(cmds, (function (cmd) {
          if (typeof cmd !== "object") {
            return false;
          } else {
            return true;
          }
        }));
  var match = filtered.length;
  if (match !== 0) {
    if (match !== 1) {
      return {
              TAG: "Batch",
              _0: filtered
            };
    } else {
      return Belt_Array.getExn(filtered, 0);
    }
  } else {
    return "None";
  }
}

function perform(operation, toMsg) {
  return {
          TAG: "Effect",
          _0: (function (dispatch) {
              operation().then(function (value) {
                    dispatch(toMsg(value));
                    return Promise.resolve();
                  });
            })
        };
}

function attempt(operation, toMsg) {
  return {
          TAG: "Effect",
          _0: (function (dispatch) {
              Core__Promise.$$catch(operation().then(function (value) {
                        dispatch(toMsg({
                                  TAG: "Ok",
                                  _0: value
                                }));
                        return Promise.resolve();
                      }), (function (err) {
                      var exn = Caml_js_exceptions.internalToOCamlException(err);
                      dispatch(toMsg({
                                TAG: "Error",
                                _0: exn
                              }));
                      return Promise.resolve();
                    }));
            })
        };
}

function map(f, cmd) {
  if (typeof cmd !== "object") {
    return "None";
  }
  if (cmd.TAG === "Batch") {
    return {
            TAG: "Batch",
            _0: Belt_Array.map(cmd._0, (function (c) {
                    return map(f, c);
                  }))
          };
  }
  var effect = cmd._0;
  return {
          TAG: "Effect",
          _0: (function (dispatch) {
              effect(function (a) {
                    dispatch(f(a));
                  });
            })
        };
}

function execute(cmd, dispatch) {
  if (typeof cmd !== "object") {
    return ;
  }
  if (cmd.TAG === "Batch") {
    return Belt_Array.forEach(cmd._0, (function (c) {
                  execute(c, dispatch);
                }));
  }
  var effect = cmd._0;
  setTimeout((function () {
          effect(dispatch);
        }), 0);
}

function message(msg) {
  return {
          TAG: "Effect",
          _0: (function (dispatch) {
              dispatch(msg);
            })
        };
}

function effect(callback) {
  return {
          TAG: "Effect",
          _0: callback
        };
}

var none = "None";

export {
  none ,
  batch ,
  perform ,
  attempt ,
  map ,
  execute ,
  message ,
  effect ,
}
/* No side effect */
