// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function batch(subs) {
  var filtered = Belt_Array.keep(subs, (function (sub) {
          if (typeof sub !== "object") {
            return false;
          } else {
            return true;
          }
        }));
  if (filtered.length === 0) {
    return "NoSub";
  } else if (filtered.length === 1) {
    return Belt_Array.getExn(filtered, 0);
  } else {
    return {
            TAG: "Batch",
            _0: filtered
          };
  }
}

function map(f, sub) {
  if (typeof sub !== "object") {
    return "NoSub";
  }
  if (sub.TAG === "Batch") {
    return {
            TAG: "Batch",
            _0: Belt_Array.map(sub._0, (function (__x) {
                    return map(f, __x);
                  }))
          };
  }
  var internal = sub._0;
  return {
          TAG: "SingleSub",
          _0: {
            key: internal.key,
            setup: (function (dispatch) {
                return internal.setup(function (msg) {
                            dispatch(f(msg));
                          });
              })
          }
        };
}

function toInternals(sub) {
  if (typeof sub !== "object") {
    return [];
  } else if (sub.TAG === "Batch") {
    return Belt_Array.flatMap(sub._0, toInternals);
  } else {
    return [sub._0];
  }
}

function every(intervalMs, toMsg) {
  return {
          TAG: "SingleSub",
          _0: {
            key: "time-every-" + String(intervalMs),
            setup: (function (dispatch) {
                var id = setInterval((function () {
                        dispatch(toMsg(Date.now()));
                      }), intervalMs);
                return (function () {
                          clearInterval(id);
                        });
              })
          }
        };
}

var Time = {
  every: every
};

function resizes(param) {
  return "NoSub";
}

var BrowserWindow = {
  resizes: resizes
};

function clicks(param) {
  return "NoSub";
}

function moves(param) {
  return "NoSub";
}

var Mouse = {
  clicks: clicks,
  moves: moves
};

function downs(param) {
  return "NoSub";
}

function ups(param) {
  return "NoSub";
}

var Keyboard = {
  downs: downs,
  ups: ups
};

function frames(toMsg) {
  return {
          TAG: "SingleSub",
          _0: {
            key: "animation-frames",
            setup: (function (dispatch) {
                var running = {
                  contents: true
                };
                var loop = function (timestamp) {
                  if (running.contents) {
                    dispatch(toMsg(timestamp));
                    requestAnimationFrame(loop);
                    return ;
                  }
                  
                };
                var id = requestAnimationFrame(loop);
                return (function () {
                          running.contents = false;
                          cancelAnimationFrame(id);
                        });
              })
          }
        };
}

function framesWithDelta(param) {
  return "NoSub";
}

function throttledFrames(param, param$1) {
  return "NoSub";
}

function conditionalFrames(param, param$1) {
  return "NoSub";
}

function adaptiveFrames(param, param$1) {
  return "NoSub";
}

function tween(durationMs, toMsg) {
  return {
          TAG: "SingleSub",
          _0: {
            key: "animation-tween-" + String(durationMs),
            setup: (function (dispatch) {
                var running = {
                  contents: true
                };
                var startTime = {
                  contents: undefined
                };
                var loop = function (timestamp) {
                  if (!running.contents) {
                    return ;
                  }
                  var t = startTime.contents;
                  var start = t !== undefined ? t : (startTime.contents = timestamp, timestamp);
                  var elapsed = timestamp - start;
                  var progress = Math.min(elapsed / durationMs, 1.0);
                  dispatch(toMsg(progress));
                  if (progress < 1.0) {
                    requestAnimationFrame(loop);
                  } else {
                    running.contents = false;
                  }
                };
                var id = requestAnimationFrame(loop);
                return (function () {
                          running.contents = false;
                          cancelAnimationFrame(id);
                        });
              })
          }
        };
}

var $$Animation = {
  frames: frames,
  framesWithDelta: framesWithDelta,
  throttledFrames: throttledFrames,
  conditionalFrames: conditionalFrames,
  adaptiveFrames: adaptiveFrames,
  tween: tween
};

var none = "NoSub";

export {
  none ,
  batch ,
  map ,
  toInternals ,
  Time ,
  Keyboard ,
  Mouse ,
  BrowserWindow ,
  $$Animation ,
}
/* No side effect */
