// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function errorToStringHelper(_error, _path) {
  while(true) {
    var path = _path;
    var error = _error;
    switch (error.TAG) {
      case "Field" :
          _path = Belt_Array.concat(path, [".\"" + error._0 + "\""]);
          _error = error._1;
          continue ;
      case "Index" :
          _path = Belt_Array.concat(path, ["[" + String(error._0) + "]"]);
          _error = error._1;
          continue ;
      case "OneOf" :
          var prefix = path.length !== 0 ? "at " + path.join("") + ": " : "";
          var errorStrs = Belt_Array.map(error._0, (function (e) {
                  return errorToStringHelper(e, []);
                }));
          return prefix + "none of the following decoders succeeded:\n" + errorStrs.join("\n");
      case "Failure" :
          var prefix$1 = path.length !== 0 ? "at " + path.join("") + ": " : "";
          return prefix$1 + error._0;
      
    }
  };
}

function errorToString(error) {
  return errorToStringHelper(error, []);
}

function string(json) {
  var s = Js_json.classify(json);
  if (typeof s !== "object" || s.TAG !== "JSONString") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected a string",
              _1: json
            }
          };
  } else {
    return {
            TAG: "Ok",
            _0: s._0
          };
  }
}

function $$int(json) {
  var n = Js_json.classify(json);
  if (typeof n !== "object") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected an integer",
              _1: json
            }
          };
  }
  if (n.TAG !== "JSONNumber") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected an integer",
              _1: json
            }
          };
  }
  var n$1 = n._0;
  if (Math.floor(n$1) === n$1) {
    return {
            TAG: "Ok",
            _0: n$1 | 0
          };
  } else {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected an integer",
              _1: json
            }
          };
  }
}

function $$float(json) {
  var n = Js_json.classify(json);
  if (typeof n !== "object" || n.TAG !== "JSONNumber") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected a number",
              _1: json
            }
          };
  } else {
    return {
            TAG: "Ok",
            _0: n._0
          };
  }
}

function bool(json) {
  var match = Js_json.classify(json);
  if (typeof match === "object") {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "expected a boolean",
              _1: json
            }
          };
  }
  switch (match) {
    case "JSONFalse" :
        return {
                TAG: "Ok",
                _0: false
              };
    case "JSONTrue" :
        return {
                TAG: "Ok",
                _0: true
              };
    default:
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected a boolean",
                _1: json
              }
            };
  }
}

function $$null(value) {
  return function (json) {
    var match = Js_json.classify(json);
    if (typeof match !== "object" && match === "JSONNull") {
      return {
              TAG: "Ok",
              _0: value
            };
    } else {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected null",
                _1: json
              }
            };
    }
  };
}

function field(name, decoder) {
  return function (json) {
    var dict = Js_json.classify(json);
    if (typeof dict !== "object") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an object",
                _1: json
              }
            };
    }
    if (dict.TAG !== "JSONObject") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an object",
                _1: json
              }
            };
    }
    var value = dict._0[name];
    if (value === undefined) {
      return {
              TAG: "Error",
              _0: {
                TAG: "Field",
                _0: name,
                _1: {
                  TAG: "Failure",
                  _0: "missing field \"" + name + "\"",
                  _1: json
                }
              }
            };
    }
    var v = decoder(value);
    if (v.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: v._0
            };
    } else {
      return {
              TAG: "Error",
              _0: {
                TAG: "Field",
                _0: name,
                _1: v._0
              }
            };
    }
  };
}

function optionalField(name, decoder) {
  return function (json) {
    var dict = Js_json.classify(json);
    if (typeof dict !== "object") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an object",
                _1: json
              }
            };
    }
    if (dict.TAG !== "JSONObject") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an object",
                _1: json
              }
            };
    }
    var value = dict._0[name];
    if (value === undefined) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var match = Js_json.classify(value);
    if (typeof match !== "object" && match === "JSONNull") {
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var v = decoder(value);
    if (v.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: Caml_option.some(v._0)
            };
    } else {
      return {
              TAG: "Error",
              _0: {
                TAG: "Field",
                _0: name,
                _1: v._0
              }
            };
    }
  };
}

function at(path, decoder) {
  return Belt_Array.reduceReverse(path, decoder, (function (acc, name) {
                return field(name, acc);
              }));
}

function array(decoder) {
  return function (json) {
    var arr = Js_json.classify(json);
    if (typeof arr !== "object") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an array",
                _1: json
              }
            };
    }
    if (arr.TAG !== "JSONArray") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an array",
                _1: json
              }
            };
    }
    var arr$1 = arr._0;
    var _idx = 0;
    var _results = [];
    while(true) {
      var results = _results;
      var idx = _idx;
      if (idx >= arr$1.length) {
        return {
                TAG: "Ok",
                _0: results
              };
      }
      var v = decoder(Belt_Array.getExn(arr$1, idx));
      if (v.TAG !== "Ok") {
        return {
                TAG: "Error",
                _0: {
                  TAG: "Index",
                  _0: idx,
                  _1: v._0
                }
              };
      }
      _results = Belt_Array.concat(results, [v._0]);
      _idx = idx + 1 | 0;
      continue ;
    };
  };
}

function index(idx, decoder) {
  return function (json) {
    var arr = Js_json.classify(json);
    if (typeof arr !== "object") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an array",
                _1: json
              }
            };
    }
    if (arr.TAG !== "JSONArray") {
      return {
              TAG: "Error",
              _0: {
                TAG: "Failure",
                _0: "expected an array",
                _1: json
              }
            };
    }
    var value = Belt_Array.get(arr._0, idx);
    if (value === undefined) {
      return {
              TAG: "Error",
              _0: {
                TAG: "Index",
                _0: idx,
                _1: {
                  TAG: "Failure",
                  _0: "index " + String(idx) + " out of bounds",
                  _1: json
                }
              }
            };
    }
    var v = decoder(value);
    if (v.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: v._0
            };
    } else {
      return {
              TAG: "Error",
              _0: {
                TAG: "Index",
                _0: idx,
                _1: v._0
              }
            };
    }
  };
}

function map(f, decoder) {
  return function (json) {
    var a = decoder(json);
    if (a.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: f(a._0)
            };
    } else {
      return {
              TAG: "Error",
              _0: a._0
            };
    }
  };
}

function map2(f, decoderA, decoderB) {
  return function (json) {
    var match = decoderA(json);
    var match$1 = decoderB(json);
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        return {
                TAG: "Ok",
                _0: f(match._0, match$1._0)
              };
      } else {
        return {
                TAG: "Error",
                _0: match$1._0
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: match._0
            };
    }
  };
}

function map3(f, decoderA, decoderB, decoderC) {
  return function (json) {
    var match = decoderA(json);
    var match$1 = decoderB(json);
    var match$2 = decoderC(json);
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          return {
                  TAG: "Ok",
                  _0: f(match._0, match$1._0, match$2._0)
                };
        } else {
          return {
                  TAG: "Error",
                  _0: match$2._0
                };
        }
      } else {
        return {
                TAG: "Error",
                _0: match$1._0
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: match._0
            };
    }
  };
}

function map4(f, decoderA, decoderB, decoderC, decoderD) {
  return function (json) {
    var match = decoderA(json);
    var match$1 = decoderB(json);
    var match$2 = decoderC(json);
    var match$3 = decoderD(json);
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: f(match._0, match$1._0, match$2._0, match$3._0)
                  };
          } else {
            return {
                    TAG: "Error",
                    _0: match$3._0
                  };
          }
        } else {
          return {
                  TAG: "Error",
                  _0: match$2._0
                };
        }
      } else {
        return {
                TAG: "Error",
                _0: match$1._0
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: match._0
            };
    }
  };
}

function map5(f, decoderA, decoderB, decoderC, decoderD, decoderE) {
  return function (json) {
    var match = decoderA(json);
    var match$1 = decoderB(json);
    var match$2 = decoderC(json);
    var match$3 = decoderD(json);
    var match$4 = decoderE(json);
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            if (match$4.TAG === "Ok") {
              return {
                      TAG: "Ok",
                      _0: f(match._0, match$1._0, match$2._0, match$3._0, match$4._0)
                    };
            } else {
              return {
                      TAG: "Error",
                      _0: match$4._0
                    };
            }
          } else {
            return {
                    TAG: "Error",
                    _0: match$3._0
                  };
          }
        } else {
          return {
                  TAG: "Error",
                  _0: match$2._0
                };
        }
      } else {
        return {
                TAG: "Error",
                _0: match$1._0
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: match._0
            };
    }
  };
}

function map6(f, decoderA, decoderB, decoderC, decoderD, decoderE, decoderF) {
  return function (json) {
    var match = decoderA(json);
    var match$1 = decoderB(json);
    var match$2 = decoderC(json);
    var match$3 = decoderD(json);
    var match$4 = decoderE(json);
    var match$5 = decoderF(json);
    if (match.TAG === "Ok") {
      if (match$1.TAG === "Ok") {
        if (match$2.TAG === "Ok") {
          if (match$3.TAG === "Ok") {
            if (match$4.TAG === "Ok") {
              if (match$5.TAG === "Ok") {
                return {
                        TAG: "Ok",
                        _0: f(match._0, match$1._0, match$2._0, match$3._0, match$4._0, match$5._0)
                      };
              } else {
                return {
                        TAG: "Error",
                        _0: match$5._0
                      };
              }
            } else {
              return {
                      TAG: "Error",
                      _0: match$4._0
                    };
            }
          } else {
            return {
                    TAG: "Error",
                    _0: match$3._0
                  };
          }
        } else {
          return {
                  TAG: "Error",
                  _0: match$2._0
                };
        }
      } else {
        return {
                TAG: "Error",
                _0: match$1._0
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: match._0
            };
    }
  };
}

function andThen(f, decoder) {
  return function (json) {
    var a = decoder(json);
    if (a.TAG === "Ok") {
      return f(a._0)(json);
    } else {
      return {
              TAG: "Error",
              _0: a._0
            };
    }
  };
}

function oneOf(decoders) {
  return function (json) {
    var _idx = 0;
    var _errors = [];
    while(true) {
      var errors = _errors;
      var idx = _idx;
      if (idx >= decoders.length) {
        return {
                TAG: "Error",
                _0: {
                  TAG: "OneOf",
                  _0: errors
                }
              };
      }
      var v = Belt_Array.getExn(decoders, idx)(json);
      if (v.TAG === "Ok") {
        return {
                TAG: "Ok",
                _0: v._0
              };
      }
      _errors = Belt_Array.concat(errors, [v._0]);
      _idx = idx + 1 | 0;
      continue ;
    };
  };
}

function optional(decoder) {
  return function (json) {
    var match = Js_json.classify(json);
    if (typeof match !== "object" && match === "JSONNull") {
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var v = decoder(json);
    if (v.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: Caml_option.some(v._0)
            };
    } else {
      return {
              TAG: "Error",
              _0: v._0
            };
    }
  };
}

function nullable(decoder) {
  return oneOf([
              $$null(undefined),
              map((function (v) {
                      return Caml_option.some(v);
                    }), decoder)
            ]);
}

function succeed(value) {
  return function (_json) {
    return {
            TAG: "Ok",
            _0: value
          };
  };
}

function fail(message) {
  return function (json) {
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: message,
              _1: json
            }
          };
  };
}

function value(json) {
  return {
          TAG: "Ok",
          _0: json
        };
}

function decodeValue(decoder, json) {
  return decoder(json);
}

function decodeString(decoder, str) {
  try {
    var json = JSON.parse(str);
    return decoder(json);
  }
  catch (exn){
    return {
            TAG: "Error",
            _0: {
              TAG: "Failure",
              _0: "invalid JSON",
              _1: null
            }
          };
  }
}

export {
  string ,
  $$int ,
  $$float ,
  bool ,
  $$null ,
  field ,
  optionalField ,
  at ,
  array ,
  index ,
  map ,
  map2 ,
  map3 ,
  map4 ,
  map5 ,
  map6 ,
  andThen ,
  oneOf ,
  optional ,
  nullable ,
  succeed ,
  fail ,
  value ,
  decodeValue ,
  decodeString ,
  errorToString ,
}
/* No side effect */
