// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_Cmd from "./Tea_Cmd.res.mjs";
import * as Tea_Json from "./Tea_Json.res.mjs";
import * as Belt_Array from "/node_modules/@rescript/runtime/lib/es6/Belt_Array.js";
import * as Core__Promise from "/node_modules/@rescript/core/src/Core__Promise.res.mjs";

var getHeaders = (function(response) {
      const headers = {};
      response.headers.forEach((value, key) => {
        headers[key] = value;
      });
      return headers;
    });

function methodToString(method) {
  switch (method) {
    case "GET" :
        return "GET";
    case "POST" :
        return "POST";
    case "PUT" :
        return "PUT";
    case "PATCH" :
        return "PATCH";
    case "DELETE" :
        return "DELETE";
    case "HEAD" :
        return "HEAD";
    case "OPTIONS" :
        return "OPTIONS";
    
  }
}

function buildFetchOptions(request) {
  var options = {};
  options["method"] = methodToString(request.method);
  if (request.headers.length !== 0) {
    var headersDict = {};
    Belt_Array.forEach(request.headers, (function (param) {
            headersDict[param[0]] = param[1];
          }));
    options["headers"] = headersDict;
  }
  var body = request.body;
  if (body !== undefined) {
    options["body"] = JSON.stringify(body);
  }
  return options;
}

function withTimeout(promise, timeoutMs) {
  return (function(promise, timeoutMs) {
        return new Promise((resolve, reject) => {
          const timer = setTimeout(() => {
            reject(new Error('TIMEOUT'));
          }, timeoutMs);

          promise.then(
            (value) => {
              clearTimeout(timer);
              resolve(value);
            },
            (error) => {
              clearTimeout(timer);
              reject(error);
            }
          );
        });
      })(promise, timeoutMs);
}

function get(url, decoder) {
  return {
          method: "GET",
          url: url,
          headers: [],
          body: undefined,
          timeout: undefined,
          decoder: decoder
        };
}

function post(url, body, decoder) {
  return {
          method: "POST",
          url: url,
          headers: [[
              "Content-Type",
              "application/json"
            ]],
          body: body,
          timeout: undefined,
          decoder: decoder
        };
}

function put(url, body, decoder) {
  return {
          method: "PUT",
          url: url,
          headers: [[
              "Content-Type",
              "application/json"
            ]],
          body: body,
          timeout: undefined,
          decoder: decoder
        };
}

function patch(url, body, decoder) {
  return {
          method: "PATCH",
          url: url,
          headers: [[
              "Content-Type",
              "application/json"
            ]],
          body: body,
          timeout: undefined,
          decoder: decoder
        };
}

function $$delete(url, decoder) {
  return {
          method: "DELETE",
          url: url,
          headers: [],
          body: undefined,
          timeout: undefined,
          decoder: decoder
        };
}

function withHeader(request, key, value) {
  return {
          method: request.method,
          url: request.url,
          headers: Belt_Array.concat(request.headers, [[
                  key,
                  value
                ]]),
          body: request.body,
          timeout: request.timeout,
          decoder: request.decoder
        };
}

function withHeaders(request, headers) {
  return {
          method: request.method,
          url: request.url,
          headers: Belt_Array.concat(request.headers, headers),
          body: request.body,
          timeout: request.timeout,
          decoder: request.decoder
        };
}

function withTimeout$1(request, timeoutMs) {
  return {
          method: request.method,
          url: request.url,
          headers: request.headers,
          body: request.body,
          timeout: timeoutMs,
          decoder: request.decoder
        };
}

function withBody(request, body) {
  return {
          method: request.method,
          url: request.url,
          headers: Belt_Array.some(request.headers, (function (param) {
                  return param[0] === "Content-Type";
                })) ? request.headers : Belt_Array.concat(request.headers, [[
                    "Content-Type",
                    "application/json"
                  ]]),
          body: body,
          timeout: request.timeout,
          decoder: request.decoder
        };
}

function errorToString(error) {
  if (typeof error !== "object") {
    return "Request timed out";
  }
  switch (error.TAG) {
    case "BadUrl" :
        return "Invalid URL: " + error._0;
    case "NetworkError" :
        return "Network error: " + error._0;
    case "BadStatus" :
        return "HTTP " + String(error._0) + ": " + error._1;
    case "BadBody" :
        return "Failed to decode response: " + Tea_Json.errorToString(error._0);
    
  }
}

function send(request, toMsg) {
  return Tea_Cmd.effect(function (dispatch) {
              var fetchPromise = fetch(request.url, buildFetchOptions(request));
              var ms = request.timeout;
              var promiseWithTimeout = ms !== undefined ? withTimeout(fetchPromise, ms) : fetchPromise;
              Core__Promise.$$catch(promiseWithTimeout.then(function (response) {
                        if (response.ok) {
                          return Core__Promise.$$catch(response.json().then(function (json) {
                                          var value = Tea_Json.decodeValue(request.decoder, json);
                                          if (value.TAG === "Ok") {
                                            dispatch(toMsg({
                                                      TAG: "Ok",
                                                      _0: value._0
                                                    }));
                                          } else {
                                            dispatch(toMsg({
                                                      TAG: "Error",
                                                      _0: {
                                                        TAG: "BadBody",
                                                        _0: value._0
                                                      }
                                                    }));
                                          }
                                          return Promise.resolve();
                                        }), (function (param) {
                                        dispatch(toMsg({
                                                  TAG: "Error",
                                                  _0: {
                                                    TAG: "BadBody",
                                                    _0: {
                                                      TAG: "Failure",
                                                      _0: "Invalid JSON",
                                                      _1: null
                                                    }
                                                  }
                                                }));
                                        return Promise.resolve();
                                      }));
                        } else {
                          dispatch(toMsg({
                                    TAG: "Error",
                                    _0: {
                                      TAG: "BadStatus",
                                      _0: response.status,
                                      _1: response.statusText
                                    }
                                  }));
                          return Promise.resolve();
                        }
                      }), (function (error) {
                      var errorMsg = error.message;
                      var httpError = errorMsg === "TIMEOUT" ? "Timeout" : ({
                            TAG: "NetworkError",
                            _0: errorMsg
                          });
                      dispatch(toMsg({
                                TAG: "Error",
                                _0: httpError
                              }));
                      return Promise.resolve();
                    }));
            });
}

function sendWithResponse(request, toMsg) {
  return Tea_Cmd.effect(function (dispatch) {
              var fetchPromise = fetch(request.url, buildFetchOptions(request));
              var ms = request.timeout;
              var promiseWithTimeout = ms !== undefined ? withTimeout(fetchPromise, ms) : fetchPromise;
              Core__Promise.$$catch(promiseWithTimeout.then(function (fetchResponse) {
                        if (fetchResponse.ok) {
                          return Core__Promise.$$catch(fetchResponse.json().then(function (json) {
                                          var value = Tea_Json.decodeValue(request.decoder, json);
                                          if (value.TAG === "Ok") {
                                            var response_url = fetchResponse.url;
                                            var response_status = fetchResponse.status;
                                            var response_statusText = fetchResponse.statusText;
                                            var response_headers = getHeaders(fetchResponse);
                                            var response_body = value._0;
                                            var response = {
                                              url: response_url,
                                              status: response_status,
                                              statusText: response_statusText,
                                              headers: response_headers,
                                              body: response_body
                                            };
                                            dispatch(toMsg({
                                                      TAG: "Ok",
                                                      _0: response
                                                    }));
                                          } else {
                                            dispatch(toMsg({
                                                      TAG: "Error",
                                                      _0: {
                                                        TAG: "BadBody",
                                                        _0: value._0
                                                      }
                                                    }));
                                          }
                                          return Promise.resolve();
                                        }), (function (param) {
                                        dispatch(toMsg({
                                                  TAG: "Error",
                                                  _0: {
                                                    TAG: "BadBody",
                                                    _0: {
                                                      TAG: "Failure",
                                                      _0: "Invalid JSON",
                                                      _1: null
                                                    }
                                                  }
                                                }));
                                        return Promise.resolve();
                                      }));
                        } else {
                          dispatch(toMsg({
                                    TAG: "Error",
                                    _0: {
                                      TAG: "BadStatus",
                                      _0: fetchResponse.status,
                                      _1: fetchResponse.statusText
                                    }
                                  }));
                          return Promise.resolve();
                        }
                      }), (function (error) {
                      var errorMsg = error.message;
                      var httpError = errorMsg === "TIMEOUT" ? "Timeout" : ({
                            TAG: "NetworkError",
                            _0: errorMsg
                          });
                      dispatch(toMsg({
                                TAG: "Error",
                                _0: httpError
                              }));
                      return Promise.resolve();
                    }));
            });
}

function getString(url, toMsg) {
  return send(get(url, Tea_Json.string), toMsg);
}

function getJson(url, decoder, toMsg) {
  return send(get(url, decoder), toMsg);
}

function postJson(url, body, decoder, toMsg) {
  return send(post(url, body, decoder), toMsg);
}

export {
  get ,
  post ,
  put ,
  patch ,
  $$delete ,
  withHeader ,
  withHeaders ,
  withTimeout$1 as withTimeout,
  withBody ,
  errorToString ,
  send ,
  sendWithResponse ,
  getString ,
  getJson ,
  postJson ,
}
/* No side effect */
