-- SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
-- SPDX-License-Identifier: MPL-2.0
--
-- Config_Parser - Implementation
pragma Ada_2022;

with Ada.Directories;
with Ada.Environment_Variables;
with Ada.Text_IO;

package body Config_Parser is

   -----------------
   -- Load_Config
   -----------------

   procedure Load_Config (Path : String := "") is
      Config_Path : constant String :=
        (if Path = "" then Get_Default_Config_Path else Path);
      File : Ada.Text_IO.File_Type;
   begin
      if not Ada.Directories.Exists (Config_Path) then
         --  Use defaults if no config file
         return;
      end if;

      Ada.Text_IO.Open (File, Ada.Text_IO.In_File, Config_Path);

      --  Simple TOML-like parsing (simplified)
      while not Ada.Text_IO.End_Of_File (File) loop
         declare
            Line : constant String := Ada.Text_IO.Get_Line (File);
         begin
            --  Skip comments and empty lines
            if Line'Length > 0 and then Line (Line'First) /= '#' then
               --  Would parse TOML here
               null;
            end if;
         end;
      end loop;

      Ada.Text_IO.Close (File);

   exception
      when others =>
         if Ada.Text_IO.Is_Open (File) then
            Ada.Text_IO.Close (File);
         end if;
         --  Keep defaults on error
   end Load_Config;

   -----------------
   -- Save_Config
   -----------------

   procedure Save_Config (Path : String := "") is
      Config_Path : constant String :=
        (if Path = "" then Get_Default_Config_Path else Path);
      File : Ada.Text_IO.File_Type;
   begin
      Ensure_Config_Dir;

      Ada.Text_IO.Create (File, Ada.Text_IO.Out_File, Config_Path);

      --  Write TOML format
      Ada.Text_IO.Put_Line (File, "# DNFinition Configuration");
      Ada.Text_IO.Put_Line (File, "# Generated by dnfinition");
      Ada.Text_IO.New_Line (File);

      Ada.Text_IO.Put_Line (File, "[general]");
      Ada.Text_IO.Put_Line (File, "default_backend = """ &
        To_String (Current_Config.General.Default_Backend) & """");
      Ada.Text_IO.Put_Line (File, "confirm_before_install = " &
        Boolean'Image (Current_Config.General.Confirm_Before_Install));
      Ada.Text_IO.Put_Line (File, "confirm_before_upgrade = " &
        Boolean'Image (Current_Config.General.Confirm_Before_Upgrade));
      Ada.Text_IO.Put_Line (File, "confirm_before_removal = " &
        Boolean'Image (Current_Config.General.Confirm_Before_Removal));
      Ada.Text_IO.New_Line (File);

      Ada.Text_IO.Put_Line (File, "[reversibility]");
      Ada.Text_IO.Put_Line (File, "snapshot_before_install = " &
        Boolean'Image
          (Current_Config.Reversibility.Snapshot_Before_Install));
      Ada.Text_IO.Put_Line (File, "snapshot_before_upgrade = " &
        Boolean'Image
          (Current_Config.Reversibility.Snapshot_Before_Upgrade));
      Ada.Text_IO.Put_Line (File, "snapshot_before_os_upgrade = " &
        Boolean'Image
          (Current_Config.Reversibility.Snapshot_Before_OS_Upgrade));
      Ada.Text_IO.Put_Line (File, "keep_snapshots = " &
        Positive'Image (Current_Config.Reversibility.Keep_Count));
      Ada.Text_IO.Put_Line (File, "auto_cleanup = " &
        Boolean'Image (Current_Config.Reversibility.Auto_Cleanup));
      Ada.Text_IO.New_Line (File);

      Ada.Text_IO.Put_Line (File, "[ui]");
      Ada.Text_IO.Put_Line (File, "theme = """ &
        To_String (Current_Config.UI.Theme) & """");
      Ada.Text_IO.Put_Line (File, "show_package_descriptions = " &
        Boolean'Image (Current_Config.UI.Show_Package_Descriptions));
      Ada.Text_IO.Put_Line (File, "show_dependencies = " &
        Boolean'Image (Current_Config.UI.Show_Dependencies));
      Ada.Text_IO.Put_Line (File, "page_size = " &
        Positive'Image (Current_Config.UI.Page_Size));

      Ada.Text_IO.Close (File);

   exception
      when others =>
         if Ada.Text_IO.Is_Open (File) then
            Ada.Text_IO.Close (File);
         end if;
         raise Config_Error with "Failed to save configuration";
   end Save_Config;

   ------------------------------
   -- Get_Default_Config_Path
   ------------------------------

   function Get_Default_Config_Path return String is
   begin
      return Get_Config_Dir & "/dnfinition.toml";
   end Get_Default_Config_Path;

   --------------------
   -- Get_Config_Dir
   --------------------

   function Get_Config_Dir return String is
      use Ada.Environment_Variables;
   begin
      if Exists ("XDG_CONFIG_HOME") then
         return Value ("XDG_CONFIG_HOME") & "/dnfinition";
      elsif Exists ("HOME") then
         return Value ("HOME") & "/.config/dnfinition";
      else
         return "/etc/dnfinition";
      end if;
   end Get_Config_Dir;

   -----------------------
   -- Ensure_Config_Dir
   -----------------------

   procedure Ensure_Config_Dir is
      Dir : constant String := Get_Config_Dir;
   begin
      if not Ada.Directories.Exists (Dir) then
         Ada.Directories.Create_Path (Dir);
      end if;
   end Ensure_Config_Dir;

   ------------------
   -- Reset_Config
   ------------------

   procedure Reset_Config is
   begin
      Current_Config := Default_App_Config;
   end Reset_Config;

   ---------------
   -- Get_Theme
   ---------------

   function Get_Theme return String is
   begin
      return To_String (Current_Config.UI.Theme);
   end Get_Theme;

   ---------------
   -- Set_Theme
   ---------------

   procedure Set_Theme (Theme : String) is
   begin
      Current_Config.UI.Theme := To_Unbounded_String (Theme);
   end Set_Theme;

   -------------------------
   -- Get_Confirm_Install
   -------------------------

   function Get_Confirm_Install return Boolean is
   begin
      return Current_Config.General.Confirm_Before_Install;
   end Get_Confirm_Install;

   -------------------------
   -- Set_Confirm_Install
   -------------------------

   procedure Set_Confirm_Install (Value : Boolean) is
   begin
      Current_Config.General.Confirm_Before_Install := Value;
   end Set_Confirm_Install;

   ----------------------------------
   -- Get_Snapshot_Before_Install
   ----------------------------------

   function Get_Snapshot_Before_Install return Boolean is
   begin
      return Current_Config.Reversibility.Snapshot_Before_Install;
   end Get_Snapshot_Before_Install;

   ----------------------------------
   -- Set_Snapshot_Before_Install
   ----------------------------------

   procedure Set_Snapshot_Before_Install (Value : Boolean) is
   begin
      Current_Config.Reversibility.Snapshot_Before_Install := Value;
   end Set_Snapshot_Before_Install;

   ------------------------
   -- Get_Keep_Snapshots
   ------------------------

   function Get_Keep_Snapshots return Positive is
   begin
      return Current_Config.Reversibility.Keep_Count;
   end Get_Keep_Snapshots;

   ------------------------
   -- Set_Keep_Snapshots
   ------------------------

   procedure Set_Keep_Snapshots (Value : Positive) is
   begin
      Current_Config.Reversibility.Keep_Count := Value;
   end Set_Keep_Snapshots;

end Config_Parser;
