// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Dafny code generator.
// Transforms ABI-level DafnyModule into syntactically valid .dfy source files
// with method declarations, requires/ensures/decreases clauses, and
// auto-generated helper predicates (e.g. sorted()).

use crate::abi::{DafnyFunction, DafnyModule};

/// Generate a complete .dfy file from a DafnyModule.
///
/// The output includes:
/// - A module wrapper with the module name.
/// - Helper predicate definitions (auto-detected from contracts).
/// - Method/function declarations with full contract annotations.
/// - Placeholder method bodies with `// TODO: implement` markers.
pub fn generate_dfy(module: &DafnyModule) -> String {
    let mut out = String::with_capacity(2048);

    // File header.
    out.push_str("// SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str("// Generated by dafniser — do not edit manually.\n");
    out.push_str("// See https://github.com/hyperpolymath/dafniser\n\n");

    // Module declaration.
    out.push_str(&format!("module {} {{\n\n", module.name));

    // Helper predicates.
    for pred_name in &module.helper_predicates {
        let predicate = generate_helper_predicate(pred_name);
        out.push_str(&predicate);
        out.push('\n');
    }

    // Functions and methods.
    for func in &module.functions {
        let method_code = generate_method(func);
        out.push_str(&method_code);
        out.push('\n');
    }

    // Close module.
    out.push_str("}\n");
    out
}

/// Generate a helper predicate definition.
///
/// Recognises common predicates (sorted, positive, non_negative) and
/// generates standard Dafny predicate bodies. Unknown predicates get a
/// placeholder body.
fn generate_helper_predicate(name: &str) -> String {
    match name {
        "sorted" => {
            "  // Helper predicate: checks that a sequence is sorted in non-decreasing order.\n\
             \x20 predicate sorted(s: seq<int>)\n\
             \x20 {\n\
             \x20   forall i, j :: 0 <= i < j < |s| ==> s[i] <= s[j]\n\
             \x20 }\n"
                .to_string()
        }
        "positive" => "  // Helper predicate: checks all elements are strictly positive.\n\
             \x20 predicate positive(s: seq<int>)\n\
             \x20 {\n\
             \x20   forall i :: 0 <= i < |s| ==> s[i] > 0\n\
             \x20 }\n"
            .to_string(),
        "non_negative" => "  // Helper predicate: checks all elements are non-negative.\n\
             \x20 predicate non_negative(s: seq<int>)\n\
             \x20 {\n\
             \x20   forall i :: 0 <= i < |s| ==> s[i] >= 0\n\
             \x20 }\n"
            .to_string(),
        other => {
            format!(
                "  // Helper predicate: {} (auto-detected, needs manual definition).\n\
                 \x20 predicate {}(s: seq<int>)\n\
                 \x20 {{\n\
                 \x20   true // TODO: define predicate body\n\
                 \x20 }}\n",
                other, other
            )
        }
    }
}

/// Generate a single method or function declaration with full contracts.
///
/// Produces:
/// - `method` or `function method` keyword
/// - Parameter list with Dafny types
/// - `requires` clauses from preconditions
/// - `ensures` clauses from postconditions
/// - `decreases` clause if present
/// - Placeholder body
fn generate_method(func: &DafnyFunction) -> String {
    let mut out = String::with_capacity(512);

    // Comment header.
    out.push_str(&format!(
        "  // Method: {} — verified by Dafny (Z3 backend).\n",
        func.name
    ));

    // Method signature.
    let keyword = if func.is_function {
        "function method"
    } else {
        "method"
    };
    let params_str = func
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.dafny_type))
        .collect::<Vec<_>>()
        .join(", ");

    out.push_str(&format!("  {} {}({})\n", keyword, func.name, params_str));

    // Return type.
    out.push_str(&format!(
        "    returns (result: {})\n",
        func.returns.dafny_type
    ));

    // Requires clauses (preconditions).
    for pre in &func.preconditions {
        out.push_str(&format!("    requires {}\n", pre.expression));
    }

    // Ensures clauses (postconditions).
    for post in &func.postconditions {
        out.push_str(&format!("    ensures {}\n", post.expression));
    }

    // Decreases clause.
    if let Some(dec) = &func.decreases {
        out.push_str(&format!("    decreases {}\n", dec.expression));
    }

    // Method body placeholder.
    out.push_str("  {\n");
    out.push_str(&format!(
        "    // TODO: implement {} — Dafny will verify the contracts above.\n",
        func.name
    ));

    // Generate a default return value based on the return type.
    let default_return = default_value_for_type(&func.returns.dafny_type);
    out.push_str(&format!("    result := {};\n", default_return));

    out.push_str("  }\n");
    out
}

/// Produce a sensible default value for a Dafny type.
///
/// Used as a placeholder in generated method bodies so the code parses
/// before the user fills in the real implementation.
fn default_value_for_type(dafny_type: &str) -> &str {
    match dafny_type {
        "int" | "nat" => "0",
        "real" => "0.0",
        "bool" => "false",
        "string" => "\"\"",
        t if t.starts_with("seq<") => "[]",
        t if t.starts_with("set<") => "{}",
        t if t.starts_with("map<") => "map[]",
        t if t.starts_with("multiset<") => "multiset{}",
        _ => "0 // placeholder",
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::*;

    /// Build a minimal DafnyModule for testing.
    fn sample_module() -> DafnyModule {
        DafnyModule {
            name: "Verified_sort".to_string(),
            functions: vec![DafnyFunction {
                name: "binary_search".to_string(),
                params: vec![
                    DafnyParam {
                        name: "arr".to_string(),
                        dafny_type: "seq<int>".to_string(),
                        requires: vec!["sorted(arr)".to_string()],
                    },
                    DafnyParam {
                        name: "key".to_string(),
                        dafny_type: "int".to_string(),
                        requires: vec![],
                    },
                ],
                returns: DafnyReturn {
                    dafny_type: "int".to_string(),
                    ensures: vec!["result >= 0 ==> arr[result] == key".to_string()],
                },
                preconditions: vec![Precondition {
                    expression: "sorted(arr)".to_string(),
                    description: None,
                }],
                postconditions: vec![Postcondition {
                    expression: "result >= 0 ==> arr[result] == key".to_string(),
                    description: None,
                }],
                decreases: Some(DecreasesClause {
                    expression: "arr.Length".to_string(),
                }),
                loop_invariants: vec![],
                is_function: false,
            }],
            helper_predicates: vec!["sorted".to_string()],
        }
    }

    #[test]
    fn test_generate_dfy_contains_module() {
        let module = sample_module();
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("module Verified_sort {"));
    }

    #[test]
    fn test_generate_dfy_contains_sorted_predicate() {
        let module = sample_module();
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("predicate sorted(s: seq<int>)"));
        assert!(dfy.contains("forall i, j :: 0 <= i < j < |s| ==> s[i] <= s[j]"));
    }

    #[test]
    fn test_requires_ensures_generation() {
        let module = sample_module();
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("requires sorted(arr)"));
        assert!(dfy.contains("ensures result >= 0 ==> arr[result] == key"));
    }

    #[test]
    fn test_decreases_clause_generation() {
        let module = sample_module();
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("decreases arr.Length"));
    }

    #[test]
    fn test_method_signature() {
        let module = sample_module();
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("method binary_search(arr: seq<int>, key: int)"));
        assert!(dfy.contains("returns (result: int)"));
    }

    #[test]
    fn test_default_values() {
        assert_eq!(default_value_for_type("int"), "0");
        assert_eq!(default_value_for_type("bool"), "false");
        assert_eq!(default_value_for_type("seq<int>"), "[]");
        assert_eq!(default_value_for_type("set<int>"), "{}");
    }

    #[test]
    fn test_function_keyword() {
        let mut module = sample_module();
        module.functions[0].is_function = true;
        let dfy = generate_dfy(&module);
        assert!(dfy.contains("function method binary_search"));
    }
}
