#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath)
//
// rescript-vite-config — CLI wrapper that enables vite.config.res
//
// Compiles a ReScript vite config to JS, then invokes Vite with it.
// This exists because Vite core rejected native ReScript config support
// (vitejs/vite#21649) due to insufficient ecosystem size.
//
// Usage:
//   npx rescript-vite-config dev      # compile config + vite dev
//   npx rescript-vite-config build    # compile config + vite build
//   npx rescript-vite-config preview  # compile config + vite preview
//
// How it works:
//   1. Looks for vite.config.res in the current directory
//   2. Compiles it to vite.config.res.mjs using rescript (or rescript-legacy)
//   3. Creates a thin vite.config.js that re-exports from the compiled output
//   4. Invokes vite with the requested command
//   5. Cleans up the generated vite.config.js on exit

import { execSync, spawn } from "node:child_process";
import { existsSync, writeFileSync, unlinkSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";

const CONFIG_RES = "vite.config.res";
const CONFIG_COMPILED = "vite.config.res.mjs";
const CONFIG_BRIDGE = "vite.config.js";
const BACKUP_SUFFIX = ".rescript-vite-backup";

// --- Helpers ---

function log(msg) {
  console.log(`[rescript-vite-config] ${msg}`);
}

function findRescriptCompiler() {
  // Try rescript-legacy first (handles UTF-8 crash in rescript 12.x)
  for (const cmd of ["rescript-legacy", "rescript", "npx rescript"]) {
    try {
      execSync(`${cmd} --version`, { stdio: "pipe" });
      return cmd;
    } catch {
      // Try next
    }
  }
  // Try Deno-based rescript
  try {
    execSync("deno run --node-modules-dir=auto npm:rescript -- --version", {
      stdio: "pipe",
    });
    return "deno run --node-modules-dir=auto npm:rescript --";
  } catch {
    // Not available
  }
  return null;
}

function compileConfig(compiler) {
  log(`Compiling ${CONFIG_RES} with ${compiler}...`);
  try {
    execSync(`${compiler} build`, {
      stdio: "inherit",
      env: { ...process.env, RESCRIPT_CONFIG_FILE: CONFIG_RES },
    });
  } catch (err) {
    // ReScript may return non-zero even on success with warnings
    if (!existsSync(CONFIG_COMPILED)) {
      console.error(
        `[rescript-vite-config] Failed to compile ${CONFIG_RES}. Is your rescript.json configured?`
      );
      process.exit(1);
    }
  }
}

function createBridge() {
  // Back up existing vite.config.js if present
  if (existsSync(CONFIG_BRIDGE)) {
    const existing = readFileSync(CONFIG_BRIDGE, "utf-8");
    if (!existing.includes("rescript-vite-config")) {
      writeFileSync(CONFIG_BRIDGE + BACKUP_SUFFIX, existing);
      log(`Backed up existing ${CONFIG_BRIDGE}`);
    }
  }

  // Write bridge that re-exports the compiled ReScript config
  writeFileSync(
    CONFIG_BRIDGE,
    `// Auto-generated by rescript-vite-config — do not edit
// Source: ${CONFIG_RES} → ${CONFIG_COMPILED}
export { default } from "./${CONFIG_COMPILED}";
`
  );
  log(`Created ${CONFIG_BRIDGE} → ${CONFIG_COMPILED}`);
}

function cleanup() {
  // Remove bridge
  if (existsSync(CONFIG_BRIDGE)) {
    const content = readFileSync(CONFIG_BRIDGE, "utf-8");
    if (content.includes("rescript-vite-config")) {
      unlinkSync(CONFIG_BRIDGE);
    }
  }
  // Restore backup
  if (existsSync(CONFIG_BRIDGE + BACKUP_SUFFIX)) {
    const backup = readFileSync(CONFIG_BRIDGE + BACKUP_SUFFIX, "utf-8");
    writeFileSync(CONFIG_BRIDGE, backup);
    unlinkSync(CONFIG_BRIDGE + BACKUP_SUFFIX);
    log(`Restored original ${CONFIG_BRIDGE}`);
  }
}

// --- Main ---

const args = process.argv.slice(2);
const command = args[0] || "dev";

if (command === "--help" || command === "-h") {
  console.log(`
rescript-vite-config — Use vite.config.res instead of vite.config.ts

Usage:
  rescript-vite-config dev       Start dev server
  rescript-vite-config build     Production build
  rescript-vite-config preview   Preview production build
  rescript-vite-config --help    Show this help

How it works:
  1. Compiles vite.config.res → vite.config.res.mjs
  2. Creates a bridge vite.config.js
  3. Runs vite with your command
  4. Cleans up on exit
`);
  process.exit(0);
}

// Check for vite.config.res
if (!existsSync(CONFIG_RES)) {
  console.error(
    `[rescript-vite-config] No ${CONFIG_RES} found in current directory.`
  );
  console.error("Create one and try again.");
  process.exit(1);
}

// Find compiler
const compiler = findRescriptCompiler();
if (!compiler) {
  console.error(
    "[rescript-vite-config] Could not find rescript compiler. Install via:"
  );
  console.error("  deno add npm:rescript   OR   npm install rescript");
  process.exit(1);
}

// Compile, bridge, run
compileConfig(compiler);
createBridge();

// Handle cleanup on exit
process.on("SIGINT", () => {
  cleanup();
  process.exit(0);
});
process.on("SIGTERM", () => {
  cleanup();
  process.exit(0);
});
process.on("exit", cleanup);

// Run vite
const viteArgs = [command, ...args.slice(1)];
log(`Running: vite ${viteArgs.join(" ")}`);

const vite = spawn("npx", ["vite", ...viteArgs], {
  stdio: "inherit",
  env: process.env,
});

vite.on("close", (code) => {
  cleanup();
  process.exit(code || 0);
});
