// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as PluginNotification from "@tauri-apps/plugin-notification";

async function notify(title, body) {
  try {
    var permitted = await PluginNotification.isPermissionGranted();
    if (permitted) {
      await PluginNotification.sendNotification({
            title: title,
            body: body
          });
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var state = await PluginNotification.requestPermission();
    if (state !== "granted") {
      return {
              TAG: "Error",
              _0: "Notification permission denied"
            };
    } else {
      await PluginNotification.sendNotification({
            title: title,
            body: body
          });
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to send notification")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to send notification"
            };
    }
  }
}

async function send(options) {
  try {
    var permitted = await PluginNotification.isPermissionGranted();
    if (permitted) {
      await PluginNotification.sendNotification(options);
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var state = await PluginNotification.requestPermission();
    if (state !== "granted") {
      return {
              TAG: "Error",
              _0: "Notification permission denied"
            };
    } else {
      await PluginNotification.sendNotification(options);
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to send notification")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to send notification"
            };
    }
  }
}

async function isAvailable() {
  try {
    return await PluginNotification.isPermissionGranted();
  }
  catch (exn){
    return false;
  }
}

async function ensurePermission() {
  try {
    var permitted = await PluginNotification.isPermissionGranted();
    if (permitted) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var state = await PluginNotification.requestPermission();
    if (state === "granted") {
      return {
              TAG: "Ok",
              _0: undefined
            };
    } else {
      return {
              TAG: "Error",
              _0: "Notification permission denied"
            };
    }
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to check permission")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to check permission"
            };
    }
  }
}

function make(title) {
  return {
          title: title
        };
}

function body(builder, text) {
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.body = text;
  return newrecord;
}

function icon(builder, path) {
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.icon = path;
  return newrecord;
}

function sound(builder, name) {
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.sound = name;
  return newrecord;
}

function tag(builder, tag$1) {
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.tag = tag$1;
  return newrecord;
}

function silent(builder) {
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.silent = true;
  return newrecord;
}

function action(builder, id, title) {
  var existing = Core__Option.getOr(builder.actions, []);
  var newrecord = Caml_obj.obj_dup(builder);
  newrecord.actions = existing.concat([{
          id: id,
          title: title
        }]);
  return newrecord;
}

async function send_(builder) {
  return await send(builder);
}

var NotificationBuilder = {
  make: make,
  body: body,
  icon: icon,
  sound: sound,
  tag: tag,
  silent: silent,
  action: action,
  send_: send_
};

function isPermissionGranted(prim) {
  return PluginNotification.isPermissionGranted();
}

function requestPermission(prim) {
  return PluginNotification.requestPermission();
}

function permissionState(prim) {
  return PluginNotification.permissionState();
}

function sendNotification(prim) {
  return PluginNotification.sendNotification(prim);
}

function registerActionTypes(prim) {
  return PluginNotification.registerActionTypes(prim);
}

function removeActiveNotifications(prim) {
  return PluginNotification.removeActiveNotifications(prim);
}

function removeAllActiveNotifications(prim) {
  return PluginNotification.removeAllActiveNotifications();
}

function getPendingNotifications(prim) {
  return PluginNotification.getPendingNotifications();
}

function getActiveNotifications(prim) {
  return PluginNotification.getActiveNotifications();
}

function onNotificationReceived(prim) {
  return PluginNotification.onNotificationReceived(prim);
}

function onAction(prim) {
  return PluginNotification.onAction(prim);
}

export {
  isPermissionGranted ,
  requestPermission ,
  permissionState ,
  sendNotification ,
  registerActionTypes ,
  removeActiveNotifications ,
  removeAllActiveNotifications ,
  getPendingNotifications ,
  getActiveNotifications ,
  onNotificationReceived ,
  onAction ,
  notify ,
  send ,
  isAvailable ,
  ensurePermission ,
  NotificationBuilder ,
}
/* @tauri-apps/plugin-notification Not a pure module */
