// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as Path from "@tauri-apps/api/path";

async function getBaseDir(dir) {
  switch (dir) {
    case 1 :
        return await Path.audioDir();
    case 2 :
        return await Path.cacheDir();
    case 3 :
        return await Path.configDir();
    case 4 :
        return await Path.dataDir();
    case 5 :
        return await Path.localDataDir();
    case 6 :
        return await Path.documentDir();
    case 7 :
        return await Path.downloadDir();
    case 8 :
        return await Path.pictureDir();
    case 9 :
        return await Path.publicDir();
    case 10 :
        return await Path.videoDir();
    case 11 :
        return await Path.resourceDir();
    case 12 :
        return await Path.tempDir();
    case 13 :
        return await Path.appConfigDir();
    case 14 :
        return await Path.appDataDir();
    case 15 :
        return await Path.appLocalDataDir();
    case 16 :
        return await Path.appCacheDir();
    case 17 :
        return await Path.appLogDir();
    case 18 :
        return await Path.desktopDir();
    case 19 :
        return await Path.executableDir();
    case 20 :
        return await Path.fontDir();
    case 21 :
        return await Path.homeDir();
    case 22 :
        return await Path.runtimeDir();
    case 23 :
        return await Path.templateDir();
    
  }
}

function prependToArray(elem, arr) {
  return $$Array.concat({
              hd: [elem],
              tl: {
                hd: arr,
                tl: /* [] */0
              }
            });
}

async function joinFromBase(dir, segments) {
  var base = await getBaseDir(dir);
  return await Path.join(prependToArray(base, segments));
}

async function inAppData(segments) {
  return await joinFromBase(14, segments);
}

async function inAppConfig(segments) {
  return await joinFromBase(13, segments);
}

async function inAppCache(segments) {
  return await joinFromBase(16, segments);
}

async function inTemp(segments) {
  return await joinFromBase(12, segments);
}

async function inHome(segments) {
  return await joinFromBase(21, segments);
}

function audioDir(prim) {
  return Path.audioDir();
}

function cacheDir(prim) {
  return Path.cacheDir();
}

function configDir(prim) {
  return Path.configDir();
}

function dataDir(prim) {
  return Path.dataDir();
}

function localDataDir(prim) {
  return Path.localDataDir();
}

function documentDir(prim) {
  return Path.documentDir();
}

function downloadDir(prim) {
  return Path.downloadDir();
}

function pictureDir(prim) {
  return Path.pictureDir();
}

function publicDir(prim) {
  return Path.publicDir();
}

function videoDir(prim) {
  return Path.videoDir();
}

function desktopDir(prim) {
  return Path.desktopDir();
}

function executableDir(prim) {
  return Path.executableDir();
}

function fontDir(prim) {
  return Path.fontDir();
}

function homeDir(prim) {
  return Path.homeDir();
}

function runtimeDir(prim) {
  return Path.runtimeDir();
}

function templateDir(prim) {
  return Path.templateDir();
}

function resourceDir(prim) {
  return Path.resourceDir();
}

function tempDir(prim) {
  return Path.tempDir();
}

function appConfigDir(prim) {
  return Path.appConfigDir();
}

function appDataDir(prim) {
  return Path.appDataDir();
}

function appLocalDataDir(prim) {
  return Path.appLocalDataDir();
}

function appCacheDir(prim) {
  return Path.appCacheDir();
}

function appLogDir(prim) {
  return Path.appLogDir();
}

function sep(prim) {
  return Path.sep();
}

function delimiter(prim) {
  return Path.delimiter();
}

function join(prim) {
  return Path.join(prim);
}

function normalize(prim) {
  return Path.normalize(prim);
}

function resolve(prim) {
  return Path.resolve(prim);
}

function dirname(prim) {
  return Path.dirname(prim);
}

function basename(prim) {
  return Path.basename(prim);
}

function basenameWithExt(prim0, prim1) {
  return Path.basename(prim0, prim1);
}

function extname(prim) {
  return Path.extname(prim);
}

function isAbsolute(prim) {
  return Path.isAbsolute(prim);
}

export {
  audioDir ,
  cacheDir ,
  configDir ,
  dataDir ,
  localDataDir ,
  documentDir ,
  downloadDir ,
  pictureDir ,
  publicDir ,
  videoDir ,
  desktopDir ,
  executableDir ,
  fontDir ,
  homeDir ,
  runtimeDir ,
  templateDir ,
  resourceDir ,
  tempDir ,
  appConfigDir ,
  appDataDir ,
  appLocalDataDir ,
  appCacheDir ,
  appLogDir ,
  sep ,
  delimiter ,
  join ,
  normalize ,
  resolve ,
  dirname ,
  basename ,
  basenameWithExt ,
  extname ,
  isAbsolute ,
  getBaseDir ,
  joinFromBase ,
  inAppData ,
  inAppConfig ,
  inAppCache ,
  inTemp ,
  inHome ,
}
/* @tauri-apps/api/path Not a pure module */
