// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as PluginFs from "@tauri-apps/plugin-fs";

async function readJsonFile(path, options) {
  try {
    var content = await PluginFs.readTextFile(path, options !== undefined ? Caml_option.valFromOption(options) : undefined);
    var exit = 0;
    var json;
    try {
      json = JSON.parse(content);
      exit = 1;
    }
    catch (exn){
      return {
              TAG: "Error",
              _0: "Failed to parse JSON"
            };
    }
    if (exit === 1) {
      return {
              TAG: "Ok",
              _0: json
            };
    }
    
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to read file")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to read file"
            };
    }
  }
}

async function writeJsonFile(path, data, options) {
  try {
    var content = JSON.stringify(data, undefined, 2);
    await PluginFs.writeTextFile(path, content, options !== undefined ? Caml_option.valFromOption(options) : undefined);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to write file")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to write file"
            };
    }
  }
}

async function ensureDir(path, options) {
  try {
    var baseDir = options !== undefined ? options.baseDir : undefined;
    var dirExists = await PluginFs.exists(path, {
          baseDir: baseDir
        });
    if (!dirExists) {
      if (options !== undefined) {
        var newrecord = Caml_obj.obj_dup(options);
        await PluginFs.mkdir(path, (newrecord.recursive = true, newrecord));
      } else {
        await PluginFs.mkdir(path, {
              recursive: true
            });
      }
    }
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to ensure directory")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to ensure directory"
            };
    }
  }
}

async function listFilesRecursive(path, options) {
  try {
    var entries = await PluginFs.readDir(path, options !== undefined ? Caml_option.valFromOption(options) : undefined);
    var allFiles = [];
    for(var i = 0 ,i_finish = entries.length; i < i_finish; ++i){
      var entry = Core__Option.getExn(entries[i], undefined);
      var fullPath = path + "/" + entry.name;
      if (entry.isDirectory) {
        var subFiles = await listFilesRecursive(fullPath, options);
        if (subFiles.TAG === "Ok") {
          subFiles._0.forEach(function (f) {
                allFiles.push(f);
              });
        }
        
      } else {
        allFiles.push(fullPath);
      }
    }
    return {
            TAG: "Ok",
            _0: allFiles
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to list files")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to list files"
            };
    }
  }
}

function readFile(prim0, prim1) {
  return PluginFs.readFile(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function readTextFile(prim0, prim1) {
  return PluginFs.readTextFile(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function writeFile(prim0, prim1, prim2) {
  return PluginFs.writeFile(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function writeTextFile(prim0, prim1, prim2) {
  return PluginFs.writeTextFile(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function open_(prim0, prim1) {
  return PluginFs.open(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function close(prim) {
  return prim.close();
}

function read(prim0, prim1) {
  return prim0.read(prim1);
}

function write(prim0, prim1) {
  return prim0.write(prim1);
}

function seek(prim0, prim1, prim2) {
  return prim0.seek(prim1, prim2);
}

function stat(prim) {
  return prim.stat();
}

function truncate(prim0, prim1) {
  return prim0.truncate(prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function readDir(prim0, prim1) {
  return PluginFs.readDir(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function mkdir(prim0, prim1) {
  return PluginFs.mkdir(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function remove(prim0, prim1) {
  return PluginFs.remove(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function copyFile(prim0, prim1, prim2) {
  return PluginFs.copyFile(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function rename(prim0, prim1, prim2) {
  return PluginFs.rename(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function lstat(prim0, prim1) {
  return PluginFs.lstat(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function exists(prim0, prim1) {
  return PluginFs.exists(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function watch(prim0, prim1, prim2) {
  return PluginFs.watch(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function watchImmediate(prim0, prim1, prim2) {
  return PluginFs.watchImmediate(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

export {
  readFile ,
  readTextFile ,
  writeFile ,
  writeTextFile ,
  open_ ,
  close ,
  read ,
  write ,
  seek ,
  stat ,
  truncate ,
  readDir ,
  mkdir ,
  remove ,
  copyFile ,
  rename ,
  lstat ,
  exists ,
  watch ,
  watchImmediate ,
  readJsonFile ,
  writeJsonFile ,
  ensureDir ,
  listFilesRecursive ,
}
/* @tauri-apps/plugin-fs Not a pure module */
