// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PluginOs from "@tauri-apps/plugin-os";

async function isDesktop() {
  var p = await PluginOs.platform();
  switch (p) {
    case "ios" :
    case "android" :
        return false;
    default:
      return true;
  }
}

async function isMobile() {
  var p = await PluginOs.platform();
  switch (p) {
    case "ios" :
    case "android" :
        return true;
    default:
      return false;
  }
}

async function isMacos() {
  var p = await PluginOs.platform();
  return p === "darwin";
}

async function isWindows() {
  var p = await PluginOs.platform();
  return p === "windows";
}

async function isLinux() {
  var p = await PluginOs.platform();
  return p === "linux";
}

async function isIos() {
  var p = await PluginOs.platform();
  return p === "ios";
}

async function isAndroid() {
  var p = await PluginOs.platform();
  return p === "android";
}

async function isUnix() {
  var f = await PluginOs.family();
  return f === "unix";
}

async function getOsInfo() {
  var p = await PluginOs.platform();
  var a = await PluginOs.arch();
  var t = await PluginOs.type();
  var v = await PluginOs.version();
  var f = await PluginOs.family();
  var h = await PluginOs.hostname();
  var l = await PluginOs.locale();
  return {
          platform: p,
          arch: a,
          osType: t,
          version: v,
          family: f,
          hostname: h,
          locale: l
        };
}

function platform(prim) {
  return PluginOs.platform();
}

function arch(prim) {
  return PluginOs.arch();
}

function osType(prim) {
  return PluginOs.type();
}

function version(prim) {
  return PluginOs.version();
}

function locale(prim) {
  return PluginOs.locale();
}

function hostname(prim) {
  return PluginOs.hostname();
}

function exeExtension(prim) {
  return PluginOs.exeExtension();
}

function family(prim) {
  return PluginOs.family();
}

function eol(prim) {
  return PluginOs.eol();
}

export {
  platform ,
  arch ,
  osType ,
  version ,
  locale ,
  hostname ,
  exeExtension ,
  family ,
  eol ,
  isDesktop ,
  isMobile ,
  isMacos ,
  isWindows ,
  isLinux ,
  isIos ,
  isAndroid ,
  isUnix ,
  getOsInfo ,
}
/* @tauri-apps/plugin-os Not a pure module */
