// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as PluginClipboardManager from "@tauri-apps/plugin-clipboard-manager";

async function getText() {
  try {
    var text = await PluginClipboardManager.readText();
    return {
            TAG: "Ok",
            _0: text
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to read clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to read clipboard"
            };
    }
  }
}

async function setText(text) {
  try {
    await PluginClipboardManager.writeText(text);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to write to clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to write to clipboard"
            };
    }
  }
}

async function getImage() {
  try {
    var img = await PluginClipboardManager.readImage();
    return {
            TAG: "Ok",
            _0: (img == null) ? undefined : Caml_option.some(img)
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to read image from clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to read image from clipboard"
            };
    }
  }
}

async function setImage(base64) {
  try {
    await PluginClipboardManager.writeImage(base64);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to write image to clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to write image to clipboard"
            };
    }
  }
}

async function getHtml() {
  try {
    var html = await PluginClipboardManager.readHtml();
    return {
            TAG: "Ok",
            _0: (html == null) ? undefined : Caml_option.some(html)
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to read HTML from clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to read HTML from clipboard"
            };
    }
  }
}

async function setHtml(html, alt) {
  try {
    await PluginClipboardManager.writeHtml(html, alt !== undefined ? Caml_option.valFromOption(alt) : undefined);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to write HTML to clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to write HTML to clipboard"
            };
    }
  }
}

async function clearClipboard() {
  try {
    await PluginClipboardManager.clear();
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Failed to clear clipboard")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Failed to clear clipboard"
            };
    }
  }
}

function readText(prim) {
  return PluginClipboardManager.readText();
}

function writeText(prim) {
  return PluginClipboardManager.writeText(prim);
}

function readImageBase64(prim) {
  return PluginClipboardManager.readImage();
}

function writeImageBase64(prim) {
  return PluginClipboardManager.writeImage(prim);
}

function readHtml(prim) {
  return PluginClipboardManager.readHtml();
}

function writeHtml(prim0, prim1) {
  return PluginClipboardManager.writeHtml(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
}

function clear(prim) {
  return PluginClipboardManager.clear();
}

var copy = setText;

var paste = getText;

export {
  readText ,
  writeText ,
  readImageBase64 ,
  writeImageBase64 ,
  readHtml ,
  writeHtml ,
  clear ,
  getText ,
  setText ,
  getImage ,
  setImage ,
  getHtml ,
  setHtml ,
  copy ,
  paste ,
  clearClipboard ,
}
/* @tauri-apps/plugin-clipboard-manager Not a pure module */
