// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Window from "@tauri-apps/api/window";

function get(prim) {
  return $$Window.getCurrentWindow();
}

function center() {
  return $$Window.getCurrentWindow().center();
}

function close() {
  return $$Window.getCurrentWindow().close();
}

function minimize() {
  return $$Window.getCurrentWindow().minimize();
}

function maximize() {
  return $$Window.getCurrentWindow().maximize();
}

function setTitle(title) {
  return $$Window.getCurrentWindow().setTitle(title);
}

function setFullscreen(fullscreen) {
  return $$Window.getCurrentWindow().setFullscreen(fullscreen);
}

function setSize(size) {
  return $$Window.getCurrentWindow().setSize(size);
}

function setPosition(pos) {
  return $$Window.getCurrentWindow().setPosition(pos);
}

function show() {
  return $$Window.getCurrentWindow().show();
}

function hide() {
  return $$Window.getCurrentWindow().hide();
}

function isFocused() {
  return $$Window.getCurrentWindow().isFocused();
}

function isMaximized() {
  return $$Window.getCurrentWindow().isMaximized();
}

function isMinimized() {
  return $$Window.getCurrentWindow().isMinimized();
}

function isFullscreen() {
  return $$Window.getCurrentWindow().isFullscreen();
}

function getTitle() {
  return $$Window.getCurrentWindow().title();
}

function getTheme() {
  return $$Window.getCurrentWindow().theme();
}

var Current = {
  get: get,
  center: center,
  close: close,
  minimize: minimize,
  maximize: maximize,
  setTitle: setTitle,
  setFullscreen: setFullscreen,
  setSize: setSize,
  setPosition: setPosition,
  show: show,
  hide: hide,
  isFocused: isFocused,
  isMaximized: isMaximized,
  isMinimized: isMinimized,
  isFullscreen: isFullscreen,
  getTitle: getTitle,
  getTheme: getTheme
};

function getCurrentWindow(prim) {
  return $$Window.getCurrentWindow();
}

function getAllWindows(prim) {
  return $$Window.getAllWindows();
}

function label(prim) {
  return prim.label();
}

function scaleFactor(prim) {
  return prim.scaleFactor();
}

function innerPosition(prim) {
  return prim.innerPosition();
}

function outerPosition(prim) {
  return prim.outerPosition();
}

function innerSize(prim) {
  return prim.innerSize();
}

function outerSize(prim) {
  return prim.outerSize();
}

function isFullscreen$1(prim) {
  return prim.isFullscreen();
}

function isMinimized$1(prim) {
  return prim.isMinimized();
}

function isMaximized$1(prim) {
  return prim.isMaximized();
}

function isFocused$1(prim) {
  return prim.isFocused();
}

function isDecorated(prim) {
  return prim.isDecorated();
}

function isResizable(prim) {
  return prim.isResizable();
}

function isMaximizable(prim) {
  return prim.isMaximizable();
}

function isMinimizable(prim) {
  return prim.isMinimizable();
}

function isClosable(prim) {
  return prim.isClosable();
}

function isVisible(prim) {
  return prim.isVisible();
}

function title(prim) {
  return prim.title();
}

function theme(prim) {
  return prim.theme();
}

function center$1(prim) {
  return prim.center();
}

function requestUserAttention(prim0, prim1) {
  return prim0.requestUserAttention(prim1);
}

function setResizable(prim0, prim1) {
  return prim0.setResizable(prim1);
}

function setMaximizable(prim0, prim1) {
  return prim0.setMaximizable(prim1);
}

function setMinimizable(prim0, prim1) {
  return prim0.setMinimizable(prim1);
}

function setClosable(prim0, prim1) {
  return prim0.setClosable(prim1);
}

function setTitle$1(prim0, prim1) {
  return prim0.setTitle(prim1);
}

function maximize$1(prim) {
  return prim.maximize();
}

function unmaximize(prim) {
  return prim.unmaximize();
}

function toggleMaximize(prim) {
  return prim.toggleMaximize();
}

function minimize$1(prim) {
  return prim.minimize();
}

function unminimize(prim) {
  return prim.unminimize();
}

function show$1(prim) {
  return prim.show();
}

function hide$1(prim) {
  return prim.hide();
}

function close$1(prim) {
  return prim.close();
}

function destroy(prim) {
  return prim.destroy();
}

function setDecorations(prim0, prim1) {
  return prim0.setDecorations(prim1);
}

function setShadow(prim0, prim1) {
  return prim0.setShadow(prim1);
}

function setAlwaysOnTop(prim0, prim1) {
  return prim0.setAlwaysOnTop(prim1);
}

function setAlwaysOnBottom(prim0, prim1) {
  return prim0.setAlwaysOnBottom(prim1);
}

function setContentProtected(prim0, prim1) {
  return prim0.setContentProtected(prim1);
}

function setSize$1(prim0, prim1) {
  return prim0.setSize(prim1);
}

function setMinSize(prim0, prim1) {
  return prim0.setMinSize(prim1);
}

function setMaxSize(prim0, prim1) {
  return prim0.setMaxSize(prim1);
}

function setPosition$1(prim0, prim1) {
  return prim0.setPosition(prim1);
}

function setFullscreen$1(prim0, prim1) {
  return prim0.setFullscreen(prim1);
}

function setFocus(prim) {
  return prim.setFocus();
}

function setSkipTaskbar(prim0, prim1) {
  return prim0.setSkipTaskbar(prim1);
}

function setCursorGrab(prim0, prim1) {
  return prim0.setCursorGrab(prim1);
}

function setCursorVisible(prim0, prim1) {
  return prim0.setCursorVisible(prim1);
}

function setCursorIcon(prim0, prim1) {
  return prim0.setCursorIcon(prim1);
}

function setCursorPosition(prim0, prim1) {
  return prim0.setCursorPosition(prim1);
}

function setIgnoreCursorEvents(prim0, prim1) {
  return prim0.setIgnoreCursorEvents(prim1);
}

function startDragging(prim) {
  return prim.startDragging();
}

function startResizeDragging(prim) {
  return prim.startResizeDragging();
}

function setProgressBar(prim0, prim1) {
  return prim0.setProgressBar(prim1);
}

function setVisibleOnAllWorkspaces(prim0, prim1) {
  return prim0.setVisibleOnAllWorkspaces(prim1);
}

function onCloseRequested(prim0, prim1) {
  return prim0.onCloseRequested(prim1);
}

function onFocusChanged(prim0, prim1) {
  return prim0.onFocusChanged(prim1);
}

function onMoved(prim0, prim1) {
  return prim0.onMoved(prim1);
}

function onResized(prim0, prim1) {
  return prim0.onResized(prim1);
}

function onScaleChanged(prim0, prim1) {
  return prim0.onScaleChanged(prim1);
}

function onThemeChanged(prim0, prim1) {
  return prim0.onThemeChanged(prim1);
}

export {
  getCurrentWindow ,
  getAllWindows ,
  label ,
  scaleFactor ,
  innerPosition ,
  outerPosition ,
  innerSize ,
  outerSize ,
  isFullscreen$1 as isFullscreen,
  isMinimized$1 as isMinimized,
  isMaximized$1 as isMaximized,
  isFocused$1 as isFocused,
  isDecorated ,
  isResizable ,
  isMaximizable ,
  isMinimizable ,
  isClosable ,
  isVisible ,
  title ,
  theme ,
  center$1 as center,
  requestUserAttention ,
  setResizable ,
  setMaximizable ,
  setMinimizable ,
  setClosable ,
  setTitle$1 as setTitle,
  maximize$1 as maximize,
  unmaximize ,
  toggleMaximize ,
  minimize$1 as minimize,
  unminimize ,
  show$1 as show,
  hide$1 as hide,
  close$1 as close,
  destroy ,
  setDecorations ,
  setShadow ,
  setAlwaysOnTop ,
  setAlwaysOnBottom ,
  setContentProtected ,
  setSize$1 as setSize,
  setMinSize ,
  setMaxSize ,
  setPosition$1 as setPosition,
  setFullscreen$1 as setFullscreen,
  setFocus ,
  setSkipTaskbar ,
  setCursorGrab ,
  setCursorVisible ,
  setCursorIcon ,
  setCursorPosition ,
  setIgnoreCursorEvents ,
  startDragging ,
  startResizeDragging ,
  setProgressBar ,
  setVisibleOnAllWorkspaces ,
  onCloseRequested ,
  onFocusChanged ,
  onMoved ,
  onResized ,
  onScaleChanged ,
  onThemeChanged ,
  Current ,
}
/* @tauri-apps/api/window Not a pure module */
