// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as App from "@tauri-apps/api/app";
import * as Core from "@tauri-apps/api/core";
import * as $$Image from "@tauri-apps/api/image";

async function invokeTyped(command, args, decoder) {
  try {
    var response = await Core.invoke(command, args);
    return decoder(response);
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: Core__Option.getOr(err._1.message, "Unknown Tauri invoke error")
            };
    }
    throw err;
  }
}

function invoke(prim0, prim1, prim2) {
  return Core.invoke(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function transformCallback(prim) {
  return Core.transformCallback(prim);
}

function isPluginAvailable(prim) {
  return Core.isPluginAvailable(prim);
}

function makeChannel(prim) {
  return new Core.Channel();
}

function onMessage(prim0, prim1) {
  prim0.onmessage(prim1);
}

function channelId(prim) {
  return prim.id;
}

function makeResource(prim) {
  return new Core.Resource(prim);
}

function closeResource(prim) {
  return prim.close();
}

function resourceRid(prim) {
  return prim.rid;
}

function imageFromBytes(prim) {
  return new $$Image.Image(prim);
}

function imageFromPath(prim) {
  return new $$Image.Image(prim);
}

function imageRgba(prim) {
  return prim.rgba();
}

function imageSize(prim) {
  return prim.size();
}

function getName(prim) {
  return App.getName();
}

function getVersion(prim) {
  return App.getVersion();
}

function getTauriVersion(prim) {
  return App.getTauriVersion();
}

function show(prim) {
  return App.show();
}

function hide(prim) {
  return App.hide();
}

export {
  invoke ,
  invokeTyped ,
  transformCallback ,
  isPluginAvailable ,
  makeChannel ,
  onMessage ,
  channelId ,
  makeResource ,
  closeResource ,
  resourceRid ,
  imageFromBytes ,
  imageFromPath ,
  imageRgba ,
  imageSize ,
  getName ,
  getVersion ,
  getTauriVersion ,
  show ,
  hide ,
}
/* @tauri-apps/api/app Not a pure module */
