# SPDX-License-Identifier: MPL-2.0
homepage: "https://github.com/hyperpolymath/idaptik"
language: rust
primary_contact: "j.d.a.jewell@open.ac.uk"
main_repo: "https://github.com/hyperpolymath/idaptik.git"
