// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as $$Navigation from "./Navigation.res.mjs";

function make(href, onClick, className, style, target, children) {
  var handleClick = function ($$event) {
    if (onClick !== undefined) {
      onClick($$event);
    }
    var shouldNavigate = false;
    if (!$$event.defaultPrevented && $$event.button === 0 && !$$event.metaKey && !$$event.altKey && !$$event.ctrlKey && !$$event.shiftKey) {
      var tmp;
      tmp = target !== undefined && target !== "_self" ? false : true;
      shouldNavigate = tmp;
    }
    if (shouldNavigate) {
      $$event.preventDefault();
      return $$Navigation.pushUrl(href);
    }
    
  };
  var props = {
    href: href,
    onClick: handleClick,
    className: className,
    style: style,
    target: target
  };
  return React.createElement("a", props, children);
}

function Make(funarg) {
  var Nav = $$Navigation.Make(funarg);
  var make = function (route, className, style, children) {
    var href = funarg.toString(route);
    var handleClick = function ($$event) {
      var shouldNavigate = !$$event.defaultPrevented && $$event.button === 0 && !$$event.metaKey && !$$event.altKey && !$$event.ctrlKey && !$$event.shiftKey;
      if (shouldNavigate) {
        $$event.preventDefault();
        return Nav.pushRoute(route);
      }
      
    };
    var props = {
      href: href,
      onClick: handleClick,
      className: className,
      style: style
    };
    return React.createElement("a", props, children);
  };
  return {
          make: make
        };
}

export {
  make ,
  Make ,
}
/* react Not a pure module */
