// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "./Url.res.mjs";

function pushUrl(url) {
  window.history.pushState(null, "", url);
}

function replaceUrl(url) {
  window.history.replaceState(null, "", url);
}

function back() {
  window.history.back();
}

function forward() {
  window.history.forward();
}

function go(delta) {
  window.history.go(delta);
}

function currentUrl() {
  return Url.fromLocation();
}

function onUrlChange(callback) {
  var handler = function (param) {
    callback(Url.fromLocation());
  };
  window.addEventListener("popstate", handler);
  return function () {
    window.removeEventListener("popstate", handler);
  };
}

function Make(R) {
  var pushRoute = function (route) {
    pushUrl(R.toString(route));
  };
  var replaceRoute = function (route) {
    replaceUrl(R.toString(route));
  };
  return {
          pushRoute: pushRoute,
          replaceRoute: replaceRoute
        };
}

export {
  pushUrl ,
  replaceUrl ,
  back ,
  forward ,
  go ,
  currentUrl ,
  onUrlChange ,
  Make ,
}
/* No side effect */
