// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Parser from "./Parser.res.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function findInTree(tree, target, eq, currentPath) {
  if (tree.TAG === "Leaf") {
    var route = tree._0;
    if (eq(route, target)) {
      return {
              segments: Belt_List.toArray(Belt_List.reverse(currentPath)),
              leaf: route
            };
    } else {
      return ;
    }
  }
  var children = tree.children;
  var route$1 = tree.route;
  if (eq(route$1, target)) {
    return {
            segments: Belt_List.toArray(Belt_List.reverse(currentPath)),
            leaf: route$1
          };
  }
  var newPath = {
    hd: route$1,
    tl: currentPath
  };
  var result;
  var i = 0;
  var len = children.length;
  while(result === undefined && i < len) {
    var child = children[i];
    if (child !== undefined) {
      var found = findInTree(child, target, eq, newPath);
      if (found !== undefined) {
        result = found;
      } else {
        i = i + 1 | 0;
      }
    } else {
      i = i + 1 | 0;
    }
  };
  return result;
}

function make(tree, parse, toString, eq) {
  return {
          tree: tree,
          parse: parse,
          toString: toString,
          eq: eq
        };
}

function getLayoutPath(def, route) {
  return findInTree(def.tree, route, def.eq, /* [] */0);
}

function getLayoutContexts(def, route) {
  var match = getLayoutPath(def, route);
  if (match === undefined) {
    return [];
  }
  var segments = match.segments;
  var parentContexts = Belt_Array.mapWithIndex(segments, (function (i, r) {
          return {
                  route: r,
                  depth: i,
                  isLeaf: false
                };
        }));
  var leafContext_route = match.leaf;
  var leafContext_depth = segments.length;
  var leafContext = {
    route: leafContext_route,
    depth: leafContext_depth,
    isLeaf: true
  };
  return Belt_Array.concat(parentContexts, [leafContext]);
}

function leaf(route) {
  return {
          TAG: "Leaf",
          _0: route
        };
}

function branch(route, children) {
  return {
          TAG: "Branch",
          route: route,
          children: children
        };
}

function index(parent, indexRoute, children) {
  return {
          TAG: "Branch",
          route: parent,
          children: Belt_Array.concat([{
                  TAG: "Leaf",
                  _0: indexRoute
                }], children)
        };
}

function outlet(context, fallbackOpt) {
  var fallback = fallbackOpt !== undefined ? Caml_option.valFromOption(fallbackOpt) : null;
  var nextLayout = context.remainingLayouts[0];
  if (nextLayout !== undefined) {
    return context.renderLayout(nextLayout);
  } else {
    return fallback;
  }
}

function nextOutletContext(context) {
  return {
          remainingLayouts: Belt_Array.sliceToEnd(context.remainingLayouts, 1),
          renderLayout: context.renderLayout
        };
}

function Make(Config) {
  var make = function (route) {
    var layouts = getLayoutContexts(Config.definition, route);
    if (layouts.length === 0) {
      return Config.renderNotFound();
    }
    var renderAtDepth = function (idx) {
      var layout = layouts[idx];
      if (layout === undefined) {
        return null;
      }
      var outletCtx_remainingLayouts = Belt_Array.sliceToEnd(layouts, idx + 1 | 0);
      var outletCtx_renderLayout = function (ctx) {
        var nextIdx = Belt_Array.getIndexBy(layouts, (function (l) {
                return Config.definition.eq(l.route, ctx.route);
              }));
        if (nextIdx !== undefined) {
          return renderAtDepth(nextIdx);
        } else {
          return null;
        }
      };
      var outletCtx = {
        remainingLayouts: outletCtx_remainingLayouts,
        renderLayout: outletCtx_renderLayout
      };
      return Config.renderLayout(layout, outletCtx);
    };
    return renderAtDepth(0);
  };
  return {
          make: make
        };
}

var React = {
  outlet: outlet,
  nextOutletContext: nextOutletContext,
  Make: Make
};

function nestedParser(parentParser, childParser, combine) {
  return Parser.map(Parser.andThen(parentParser, childParser), (function (param) {
                return combine(param[0], param[1]);
              }));
}

function optionalChild(parentParser, childParser, parentOnly, withChild) {
  return Parser.oneOf([
              Parser.map(Parser.andThen(parentParser, childParser), (function (param) {
                      return withChild(param[0], param[1]);
                    })),
              Parser.map(Parser.andThen(parentParser, Parser.top), (function (param) {
                      return parentOnly(param[0]);
                    }))
            ]);
}

export {
  findInTree ,
  make ,
  getLayoutPath ,
  getLayoutContexts ,
  leaf ,
  branch ,
  index ,
  React ,
  nestedParser ,
  optionalChild ,
}
/* No side effect */
