// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Parser from "./Parser.res.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function lit(literal) {
  return {
          parser: Parser.s(literal),
          serializer: (function () {
              return {
                      hd: literal,
                      tl: /* [] */0
                    };
            })
        };
}

function str() {
  return {
          parser: Parser.str,
          serializer: (function (s) {
              return {
                      hd: s,
                      tl: /* [] */0
                    };
            })
        };
}

function $$int() {
  return {
          parser: Parser.$$int,
          serializer: (function (n) {
              return {
                      hd: String(n),
                      tl: /* [] */0
                    };
            })
        };
}

function custom(parse, serialize) {
  return {
          parser: Parser.custom(parse),
          serializer: (function (a) {
              return {
                      hd: serialize(a),
                      tl: /* [] */0
                    };
            })
        };
}

function andThen(segA, segB) {
  return {
          parser: Parser.andThen(segA.parser, segB.parser),
          serializer: (function (param) {
              return Belt_List.concat(segA.serializer(param[0]), segB.serializer(param[1]));
            })
        };
}

function end__serializer() {
  return /* [] */0;
}

var end_ = {
  parser: Parser.top,
  serializer: end__serializer
};

function build(seg, toRoute, fromRoute) {
  return {
          parse: (function (url) {
              var fullParser = Parser.map(Parser.andThen(seg.parser, Parser.top), (function (param) {
                      return param[0];
                    }));
              var a = Parser.parse(fullParser, url);
              if (a !== undefined) {
                return Caml_option.some(toRoute(Caml_option.valFromOption(a)));
              }
              
            }),
          toString: (function (route) {
              var a = fromRoute(route);
              if (a === undefined) {
                return ;
              }
              var segments = seg.serializer(Caml_option.valFromOption(a));
              return "/" + Belt_List.toArray(segments).join("/");
            })
        };
}

function oneOf(routes) {
  return {
          parse: (function (url) {
              var result;
              var i = 0;
              var len = routes.length;
              while(result === undefined && i < len) {
                var r = routes[i];
                if (r !== undefined) {
                  var success = r.parse(url);
                  if (success !== undefined) {
                    result = success;
                  } else {
                    i = i + 1 | 0;
                  }
                } else {
                  i = i + 1 | 0;
                }
              };
              return result;
            }),
          toString: (function (route) {
              var result;
              var i = 0;
              var len = routes.length;
              while(result === undefined && i < len) {
                var r = routes[i];
                if (r !== undefined) {
                  var success = r.toString(route);
                  if (success !== undefined) {
                    result = success;
                  } else {
                    i = i + 1 | 0;
                  }
                } else {
                  i = i + 1 | 0;
                }
              };
              return result;
            })
        };
}

var $slash$great = andThen;

function Make(funarg) {
  var parseOption = function (url) {
    return funarg.definition.parse(url);
  };
  var parse = function (url) {
    var route = funarg.definition.parse(url);
    if (route !== undefined) {
      return Caml_option.valFromOption(route);
    } else {
      return funarg.notFound;
    }
  };
  var toString = function (route) {
    var s = funarg.definition.toString(route);
    if (s !== undefined) {
      return s;
    } else {
      return "/";
    }
  };
  return {
          parse: parse,
          parseOption: parseOption,
          toString: toString
        };
}

export {
  lit ,
  str ,
  $$int ,
  custom ,
  andThen ,
  $slash$great ,
  end_ ,
  build ,
  oneOf ,
  Make ,
}
/* No side effect */
