set shell := ["bash", "-euo", "pipefail", "-c"]

default: test

test:
    yarn build
    yarn typecheck
    @git diff --quiet src/ || { echo; echo "Please review the Gentype outputs too!"; echo; false; }

clean:
    yarn clean
