// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Alloy 6 model generator: converts parsed entities and manifest assertions
// into complete .als files ready for the Alloy Analyzer.
//
// The generator produces:
// 1. Module declaration
// 2. Primitive type signatures (String, Int, Bool) as abstract sigs
// 3. Entity signatures with typed fields
// 4. Facts (implicit constraints from the API spec)
// 5. Assertions from the manifest
// 6. Check commands for each assertion
// 7. A `run` command to visualise sample instances

use std::collections::BTreeSet;
use std::fmt::Write as FmtWrite;

use crate::abi::{AlloyModel, Assertion, Fact, Signature};
use crate::manifest::{AssertionEntry, Manifest};

/// Generate a complete AlloyModel from signatures and manifest assertions.
///
/// This function:
/// 1. Creates the module declaration from the project name
/// 2. Collects primitive types used as field targets and creates abstract sigs
/// 3. Adds all entity signatures
/// 4. Converts manifest assertions into Alloy assertions with check commands
/// 5. Adds a default `run` command for instance visualisation
///
/// # Arguments
/// * `module_name` — The Alloy module name (from project.name).
/// * `signatures` — Entity signatures extracted from API specs.
/// * `manifest` — The alloyiser manifest (for assertions and config).
///
/// # Returns
/// A fully populated `AlloyModel` ready to render as `.als`.
pub fn generate_alloy_model(
    module_name: &str,
    signatures: &[Signature],
    manifest: &Manifest,
) -> AlloyModel {
    let mut model = AlloyModel::new(sanitise_module_name(module_name));
    model.comment = Some(format!(
        "Formal model generated by alloyiser from project '{}'.\n\
         Verify with: java -jar alloy.jar {}",
        manifest.project.name,
        format!("{}.als", sanitise_module_name(module_name)),
    ));

    // Collect primitive types referenced as field targets but not
    // defined as entity sigs. These need abstract sig declarations.
    let entity_names: BTreeSet<&str> = signatures.iter().map(|s| s.name.as_str()).collect();
    let primitive_types = collect_primitive_types(signatures, &entity_names);

    // Add primitive type sigs (abstract, no fields)
    for prim in &primitive_types {
        let mut prim_sig = Signature::new(prim.as_str());
        prim_sig.is_abstract = true;
        model.add_signature(prim_sig);
    }

    // Add entity signatures
    for sig in signatures {
        model.add_signature(sig.clone());
    }

    // Convert manifest assertions to Alloy assertions
    for assertion_entry in &manifest.assertions {
        let assertion = assertion_entry_to_alloy(assertion_entry);
        model.add_assertion(assertion);
    }

    model
}

/// Render a complete .als file string from an AlloyModel, including
/// a trailing `run` command for instance visualisation.
///
/// # Arguments
/// * `model` — The Alloy model to render.
/// * `default_scope` — The scope for the default `run {}` command.
///
/// # Returns
/// The complete `.als` file content as a string.
pub fn render_als_file(model: &AlloyModel, default_scope: u32) -> String {
    let mut output = model.render();

    // Add a default run command for instance visualisation
    // (lets users see sample valid instances in the Alloy visualiser)
    output.push_str(&format!(
        "// Visualise a sample instance\nrun {{}} for {}\n",
        default_scope
    ));

    output
}

/// Generate Alloy facts from structural constraints implied by the API spec.
///
/// For example, if a field has `one` multiplicity and references another sig,
/// the referenced sig must have at least one instance. This function infers
/// such constraints and returns them as Alloy facts.
///
/// # Arguments
/// * `signatures` — The entity signatures to analyse.
///
/// # Returns
/// A vector of inferred Alloy facts.
pub fn infer_structural_facts(signatures: &[Signature]) -> Vec<Fact> {
    let mut facts = Vec::new();
    let entity_names: BTreeSet<&str> = signatures.iter().map(|s| s.name.as_str()).collect();

    // For each entity, check if any field creates a referential integrity constraint
    for sig in signatures {
        for field in &sig.fields {
            // Only generate facts for references to other entities (not primitives)
            if entity_names.contains(field.target.as_str()) {
                // If a field uses `one` multiplicity, the target must exist
                // when the source exists. This is an implicit referential integrity fact.
                if field.multiplicity == crate::abi::Multiplicity::One {
                    let mut body = String::new();
                    write!(
                        body,
                        "all s: {} | s.{} in {}",
                        sig.name, field.name, field.target
                    )
                    .expect("TODO: handle error");
                    facts.push(Fact {
                        name: Some(format!("{}_{}_integrity", sig.name, field.name)),
                        body,
                    });
                }
            }
        }
    }

    facts
}

/// Convert a manifest `AssertionEntry` into an Alloy `Assertion`.
///
/// The manifest assertion's `check` field becomes the assertion body,
/// and the `name` is sanitised to be a valid Alloy identifier.
fn assertion_entry_to_alloy(entry: &AssertionEntry) -> Assertion {
    Assertion {
        name: sanitise_identifier(&entry.name),
        body: entry.check.clone(),
        scope: entry.scope,
    }
}

/// Collect primitive type names that are used as field targets but are not
/// defined as entity signatures. These need abstract sig declarations.
///
/// # Arguments
/// * `signatures` — Entity signatures to scan for field targets.
/// * `entity_names` — Set of entity names already defined as sigs.
///
/// # Returns
/// A sorted set of primitive type names that need abstract sig declarations.
fn collect_primitive_types(
    signatures: &[Signature],
    entity_names: &BTreeSet<&str>,
) -> BTreeSet<String> {
    let mut primitives = BTreeSet::new();
    for sig in signatures {
        for field in &sig.fields {
            if !entity_names.contains(field.target.as_str()) {
                primitives.insert(field.target.clone());
            }
        }
    }
    primitives
}

/// Sanitise a project name into a valid Alloy module name.
///
/// Alloy module names must be valid identifiers: start with a letter,
/// contain only letters, digits, and underscores. Hyphens and other
/// special characters are replaced with underscores.
fn sanitise_module_name(name: &str) -> String {
    let sanitised: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // Ensure it starts with a letter
    if sanitised.starts_with(|c: char| c.is_ascii_digit()) {
        format!("m_{}", sanitised)
    } else if sanitised.is_empty() {
        "unnamed_model".to_string()
    } else {
        sanitised
    }
}

/// Sanitise a string into a valid Alloy identifier.
///
/// Replaces hyphens, spaces, and other non-alphanumeric characters
/// with underscores.
fn sanitise_identifier(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{AlloyField, Multiplicity};
    use crate::manifest::{
        AlloyConfig, AssertionEntry, Manifest, ProjectConfig, SpecEntry, SpecFormat,
    };

    /// Helper: create a minimal manifest for testing.
    fn test_manifest() -> Manifest {
        Manifest {
            project: ProjectConfig {
                name: "blog-api".to_string(),
            },
            specs: vec![SpecEntry {
                name: "blog".into(),
                source: "openapi.yaml".into(),
                format: SpecFormat::Openapi,
            }],
            assertions: vec![
                AssertionEntry {
                    name: "no-orphan-posts".into(),
                    check: "all p: Post | some p.author".into(),
                    scope: 5,
                },
                AssertionEntry {
                    name: "unique-emails".into(),
                    check: "all disj u1, u2: User | u1.email != u2.email".into(),
                    scope: 4,
                },
            ],
            alloy: AlloyConfig {
                solver: "sat4j".into(),
                max_scope: 10,
            },
        }
    }

    /// Helper: create test signatures.
    fn test_signatures() -> Vec<Signature> {
        vec![
            Signature::new("User")
                .with_field(AlloyField {
                    name: "email".into(),
                    multiplicity: Multiplicity::One,
                    target: "String".into(),
                })
                .with_field(AlloyField {
                    name: "posts".into(),
                    multiplicity: Multiplicity::Set,
                    target: "Post".into(),
                }),
            Signature::new("Post")
                .with_field(AlloyField {
                    name: "title".into(),
                    multiplicity: Multiplicity::One,
                    target: "String".into(),
                })
                .with_field(AlloyField {
                    name: "author".into(),
                    multiplicity: Multiplicity::One,
                    target: "User".into(),
                }),
        ]
    }

    /// Verify that the generated model contains all expected sections.
    #[test]
    fn test_generate_alloy_model_structure() {
        let manifest = test_manifest();
        let sigs = test_signatures();
        let model = generate_alloy_model("blog-api", &sigs, &manifest);

        assert_eq!(model.module_name, "blog_api");
        // 1 primitive (String) + 2 entities = 3 sigs
        assert_eq!(model.signatures.len(), 3);
        assert_eq!(model.assertions.len(), 2);
    }

    /// Verify that the rendered .als file has correct Alloy 6 syntax.
    #[test]
    fn test_render_als_file() {
        let manifest = test_manifest();
        let sigs = test_signatures();
        let model = generate_alloy_model("blog-api", &sigs, &manifest);
        let als = render_als_file(&model, 5);

        assert!(als.starts_with("module blog_api\n"));
        assert!(als.contains("abstract sig String {}"));
        assert!(als.contains("sig User {"));
        assert!(als.contains("email: one String"));
        assert!(als.contains("sig Post {"));
        assert!(als.contains("assert no_orphan_posts {"));
        assert!(als.contains("check no_orphan_posts for 5"));
        assert!(als.contains("assert unique_emails {"));
        assert!(als.contains("check unique_emails for 4"));
        assert!(als.contains("run {} for 5"));
    }

    /// Verify that structural facts are inferred for referential integrity.
    #[test]
    fn test_infer_structural_facts() {
        let sigs = test_signatures();
        let facts = infer_structural_facts(&sigs);

        // Post.author is `one User` → should generate an integrity fact
        assert!(
            facts
                .iter()
                .any(|f| f.name.as_deref() == Some("Post_author_integrity"))
        );
    }

    /// Verify module name sanitisation.
    #[test]
    fn test_sanitise_module_name() {
        assert_eq!(sanitise_module_name("blog-api"), "blog_api");
        assert_eq!(sanitise_module_name("my api v2"), "my_api_v2");
        assert_eq!(sanitise_module_name("123start"), "m_123start");
        assert_eq!(sanitise_module_name(""), "unnamed_model");
    }

    /// Verify identifier sanitisation.
    #[test]
    fn test_sanitise_identifier() {
        assert_eq!(sanitise_identifier("no-orphan-posts"), "no_orphan_posts");
        assert_eq!(sanitise_identifier("valid_name"), "valid_name");
    }

    /// Verify that primitive types not in the entity set are collected.
    #[test]
    fn test_collect_primitive_types() {
        let sigs = test_signatures();
        let entity_names: BTreeSet<&str> = sigs.iter().map(|s| s.name.as_str()).collect();
        let prims = collect_primitive_types(&sigs, &entity_names);
        assert!(prims.contains("String"));
        assert!(!prims.contains("User"));
        assert!(!prims.contains("Post"));
    }
}
