// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Alloy Analyzer integration: generates analysis commands and parses
// counterexample output from the Alloy command-line interface.
//
// In Phase 1, alloyiser generates .als files for manual analysis.
// This module prepares the command-line invocations and provides
// parsing utilities for when automated analysis is added in Phase 2.

use anyhow::Result;
use std::path::Path;

use crate::abi::{AtomBinding, Counterexample, ModelCheckResult};

/// Configuration for invoking the Alloy Analyzer.
///
/// The Alloy Analyzer is a Java application distributed as a JAR file.
/// This struct captures the paths and settings needed to invoke it.
#[derive(Debug, Clone)]
pub struct AnalyzerConfig {
    /// Path to the Alloy JAR file, e.g. "alloy.jar" or "/opt/alloy/alloy6.jar".
    pub alloy_jar_path: String,
    /// The SAT solver to use: "sat4j", "minisat", or "glucose".
    pub solver: String,
    /// Maximum time in seconds before aborting analysis.
    pub timeout_seconds: u64,
}

impl Default for AnalyzerConfig {
    fn default() -> Self {
        AnalyzerConfig {
            alloy_jar_path: "alloy.jar".to_string(),
            solver: "sat4j".to_string(),
            timeout_seconds: 300,
        }
    }
}

/// Generate the command-line string to invoke the Alloy Analyzer
/// on a given .als file.
///
/// The Alloy Analyzer can be invoked in headless (batch) mode to
/// check all assertions in a model file. This function constructs
/// the appropriate `java -jar` command.
///
/// # Arguments
/// * `config` — Analyzer configuration (JAR path, solver, timeout).
/// * `als_path` — Path to the `.als` file to analyse.
///
/// # Returns
/// A vector of command-line arguments suitable for `std::process::Command`.
pub fn build_analyzer_command(config: &AnalyzerConfig, als_path: &Path) -> Vec<String> {
    vec![
        "java".to_string(),
        "-jar".to_string(),
        config.alloy_jar_path.clone(),
        "-batch".to_string(),
        "-solver".to_string(),
        config.solver.clone(),
        als_path.to_string_lossy().to_string(),
    ]
}

/// Generate a shell script that runs all check commands in the model.
///
/// This is useful when users want to run analysis outside of alloyiser,
/// or in CI/CD pipelines where the Alloy JAR is available.
///
/// # Arguments
/// * `config` — Analyzer configuration.
/// * `als_path` — Path to the `.als` file.
/// * `assertion_names` — Names of assertions to check.
///
/// # Returns
/// A shell script string that checks each assertion.
pub fn generate_analysis_script(
    config: &AnalyzerConfig,
    als_path: &Path,
    assertion_names: &[String],
) -> String {
    let mut script = String::new();
    script.push_str("#!/bin/sh\n");
    script.push_str("# SPDX-License-Identifier: MPL-2.0\n");
    script.push_str("# Generated by alloyiser — Alloy analysis script\n");
    script.push_str("# Requires: java, alloy.jar\n\n");
    script.push_str(&format!("ALLOY_JAR=\"{}\"\n", config.alloy_jar_path));
    script.push_str(&format!("MODEL=\"{}\"\n", als_path.display()));
    script.push_str(&format!("SOLVER=\"{}\"\n", config.solver));
    script.push_str(&format!("TIMEOUT=\"{}\"\n\n", config.timeout_seconds));

    script.push_str("echo \"=== alloyiser analysis ===\"\n");
    script.push_str("echo \"Model: $MODEL\"\n");
    script.push_str("echo \"Solver: $SOLVER\"\n");
    script.push_str(&format!(
        "echo \"Assertions: {}\"\n\n",
        assertion_names.len()
    ));

    // Generate a check invocation for each assertion
    for name in assertion_names {
        script.push_str(&format!("echo \"Checking: {}...\"\n", name));
        script.push_str(&format!(
            "timeout \"$TIMEOUT\" java -jar \"$ALLOY_JAR\" -batch -solver \"$SOLVER\" \"$MODEL\" 2>&1 | grep -A5 \"{}\"\n",
            name
        ));
        script.push_str("echo \"\"\n\n");
    }

    script.push_str("echo \"=== analysis complete ===\"\n");
    script
}

/// Parse the text output from the Alloy Analyzer to determine check results.
///
/// The Alloy Analyzer outputs text indicating whether each check command
/// found a counterexample or not. This function parses that output into
/// structured `ModelCheckResult` values.
///
/// # Arguments
/// * `output` — Raw text output from the Alloy Analyzer.
///
/// # Returns
/// A vector of model check results, one per assertion checked.
///
/// # Note
/// In Phase 1 this parser handles the common output patterns. More
/// sophisticated parsing (XML, JSON) will be added when alloyiser
/// gains automated analysis in Phase 2.
pub fn parse_analyzer_output(output: &str) -> Vec<ModelCheckResult> {
    let mut results = Vec::new();

    for line in output.lines() {
        let trimmed = line.trim();

        // Pattern: "No counterexample found. <assertion_name> may be valid."
        if let Some(rest) = trimmed.strip_prefix("No counterexample found.") {
            let assertion_name = rest
                .trim()
                .trim_end_matches("may be valid.")
                .trim()
                .to_string();
            if !assertion_name.is_empty() {
                results.push(ModelCheckResult::NoCounterexample {
                    assertion_name,
                    scope: 0, // Scope not reported in this output format
                });
            }
        }

        // Pattern: "Counterexample found. <assertion_name> is invalid."
        if let Some(rest) = trimmed.strip_prefix("Counterexample found.") {
            let assertion_name = rest
                .trim()
                .trim_end_matches("is invalid.")
                .trim()
                .to_string();
            if !assertion_name.is_empty() {
                results.push(ModelCheckResult::CounterexampleFound {
                    assertion_name,
                    counterexample: Counterexample {
                        description: "Counterexample found by Alloy Analyzer".to_string(),
                        atom_bindings: Vec::new(), // Detailed parsing in Phase 2
                    },
                });
            }
        }
    }

    results
}

/// Parse a counterexample instance block from Alloy's XML output.
///
/// Alloy can output counterexamples in XML format, which contains
/// detailed atom assignments. This function parses the common pattern:
/// ```xml
/// <instance>
///   <sig label="User">
///     <atom label="User$0"/>
///   </sig>
///   <field label="email" parentID="...">
///     <tuple><atom label="User$0"/><atom label="String$0"/></tuple>
///   </field>
/// </instance>
/// ```
///
/// # Arguments
/// * `xml_content` — The XML output from Alloy Analyzer.
///
/// # Returns
/// A `Counterexample` with atom bindings, or an error.
///
/// # Note
/// This is a simplified parser for Phase 1. Full XML parsing with
/// a proper XML library is planned for Phase 2.
pub fn parse_counterexample_xml(xml_content: &str) -> Result<Counterexample> {
    let mut bindings = Vec::new();
    let mut current_atom: Option<String> = None;
    let mut current_sig: Option<String> = None;
    let mut current_fields: Vec<(String, String)> = Vec::new();

    for line in xml_content.lines() {
        let trimmed = line.trim();

        // Detect atom declarations: <atom label="User$0"/>
        if trimmed.starts_with("<atom")
            && trimmed.contains("label=")
            && let Some(label) = extract_xml_attr(trimmed, "label")
        {
            // If we were tracking a previous atom, save it
            if let (Some(atom), Some(sig)) = (&current_atom, &current_sig) {
                bindings.push(AtomBinding {
                    atom: atom.clone(),
                    sig_type: sig.clone(),
                    field_values: current_fields.clone(),
                });
                current_fields.clear();
            }
            // Parse the sig type from the atom label (e.g. "User$0" → "User")
            let sig_type = label.split('$').next().unwrap_or(&label).to_string();
            current_atom = Some(label);
            current_sig = Some(sig_type);
        }
    }

    // Save the last atom if present
    if let (Some(atom), Some(sig)) = (current_atom, current_sig) {
        bindings.push(AtomBinding {
            atom,
            sig_type: sig,
            field_values: current_fields,
        });
    }

    Ok(Counterexample {
        description: "Counterexample parsed from Alloy XML output".to_string(),
        atom_bindings: bindings,
    })
}

/// Extract the value of an XML attribute from a tag string.
///
/// Given `<atom label="User$0"/>`, extracts "User$0" for attribute "label".
fn extract_xml_attr(tag: &str, attr_name: &str) -> Option<String> {
    let pattern = format!("{}=\"", attr_name);
    if let Some(start) = tag.find(&pattern) {
        let value_start = start + pattern.len();
        if let Some(end) = tag[value_start..].find('"') {
            return Some(tag[value_start..value_start + end].to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that the analyzer command is constructed correctly.
    #[test]
    fn test_build_analyzer_command() {
        let config = AnalyzerConfig {
            alloy_jar_path: "/opt/alloy/alloy6.jar".into(),
            solver: "minisat".into(),
            timeout_seconds: 120,
        };
        let cmd = build_analyzer_command(&config, Path::new("model.als"));
        assert_eq!(cmd[0], "java");
        assert_eq!(cmd[1], "-jar");
        assert_eq!(cmd[2], "/opt/alloy/alloy6.jar");
        assert!(cmd.contains(&"minisat".to_string()));
        assert!(cmd.contains(&"model.als".to_string()));
    }

    /// Verify that the analysis script is generated with all assertions.
    #[test]
    fn test_generate_analysis_script() {
        let config = AnalyzerConfig::default();
        let names = vec!["no_orphans".into(), "unique_emails".into()];
        let script = generate_analysis_script(&config, Path::new("blog.als"), &names);
        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains("no_orphans"));
        assert!(script.contains("unique_emails"));
        assert!(script.contains("alloy.jar"));
    }

    /// Verify parsing of "no counterexample" output.
    #[test]
    fn test_parse_no_counterexample() {
        let output = "No counterexample found. unique_emails may be valid.\n";
        let results = parse_analyzer_output(output);
        assert_eq!(results.len(), 1);
        match &results[0] {
            ModelCheckResult::NoCounterexample { assertion_name, .. } => {
                assert_eq!(assertion_name, "unique_emails")
            }
            _ => panic!("Expected NoCounterexample"),
        }
    }

    /// Verify parsing of "counterexample found" output.
    #[test]
    fn test_parse_counterexample_found() {
        let output = "Counterexample found. no_orphans is invalid.\n";
        let results = parse_analyzer_output(output);
        assert_eq!(results.len(), 1);
        match &results[0] {
            ModelCheckResult::CounterexampleFound { assertion_name, .. } => {
                assert_eq!(assertion_name, "no_orphans")
            }
            _ => panic!("Expected CounterexampleFound"),
        }
    }

    /// Verify XML attribute extraction helper.
    #[test]
    fn test_extract_xml_attr() {
        let tag = r#"<atom label="User$0"/>"#;
        assert_eq!(extract_xml_attr(tag, "label"), Some("User$0".to_string()));
        assert_eq!(extract_xml_attr(tag, "missing"), None);
    }

    /// Verify counterexample XML parsing.
    #[test]
    fn test_parse_counterexample_xml() {
        let xml = r#"
<instance>
  <atom label="User$0"/>
  <atom label="Post$0"/>
</instance>
"#;
        let ce = parse_counterexample_xml(xml).expect("TODO: handle error");
        assert_eq!(ce.atom_bindings.len(), 2);
        assert_eq!(ce.atom_bindings[0].atom, "User$0");
        assert_eq!(ce.atom_bindings[0].sig_type, "User");
        assert_eq!(ce.atom_bindings[1].atom, "Post$0");
        assert_eq!(ce.atom_bindings[1].sig_type, "Post");
    }
}
