// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// v_pqc — Post-Quantum Cryptography protocol types and server abstraction.
// Maps to proven-servers/protocols/proven-pqc.
//
// Provides KEM and digital signature operations for post-quantum algorithms.
// Supports ML-KEM (Kyber), ML-DSA (Dilithium), SLH-DSA (SPHINCS+), Falcon,
// BIKE, and HQC. Network I/O is stubbed with TODO markers; all type
// definitions and logic are real.
module v_pqc

import crypto.sha256
import rand

// KemAlgorithm enumerates the supported Key Encapsulation Mechanism
// algorithms. Kyber variants are NIST ML-KEM standardised; BIKE and
// HQC are candidates.
pub enum KemAlgorithm {
	kyber512
	kyber768
	kyber1024
	bike_l1
	bike_l3
	hqc128
	hqc192
}

// SigAlgorithm enumerates the supported post-quantum digital signature
// algorithms. Dilithium variants are NIST ML-DSA; Falcon and SPHINCS+
// are alternatives.
pub enum SigAlgorithm {
	dilithium2
	dilithium3
	dilithium5
	falcon512
	falcon1024
	sphincs_sha256
	sphincs_sha256s
}

// KeyPair holds a public/secret key pair generated by a PQC algorithm.
pub struct KeyPair {
pub:
	// public_key is the public key bytes.
	public_key []u8
	// secret_key is the secret (private) key bytes.
	secret_key []u8
	// algorithm identifies the KEM or signature algorithm used.
	algorithm string
}

// CipherText holds the output of a KEM encapsulation operation.
pub struct CipherText {
pub:
	// data is the encapsulated ciphertext.
	data []u8
	// algorithm identifies the KEM algorithm used.
	algorithm KemAlgorithm
	// shared_secret_hash is the SHA-256 hash of the shared secret,
	// for verification purposes only.
	shared_secret_hash []u8
}

// Signature holds the output of a PQC signing operation.
pub struct Signature {
pub:
	// data is the signature bytes.
	data []u8
	// algorithm identifies the signature algorithm used.
	algorithm SigAlgorithm
}

// PqcServer is the Post-Quantum Cryptography server. It manages key
// pairs and performs KEM and signature operations.
pub struct PqcServer {
pub:
	// name identifies this PQC server instance.
	name string
pub mut:
	// kem_keys stores KEM key pairs keyed by a label string.
	kem_keys map[string]KeyPair
	// sig_keys stores signature key pairs keyed by a label string.
	sig_keys map[string]KeyPair
}

// new_server creates a new PQC server instance.
pub fn new_server(name string) &PqcServer {
	return &PqcServer{
		name: name
		kem_keys: map[string]KeyPair{}
		sig_keys: map[string]KeyPair{}
	}
}

// kem_keygen generates a new KEM key pair for the specified algorithm
// and stores it under the given label.
pub fn (mut s PqcServer) kem_keygen(label string, algorithm KemAlgorithm) !KeyPair {
	if label.len == 0 {
		return error('key label must not be empty')
	}
	if label in s.kem_keys {
		return error('KEM key already exists: ${label}')
	}
	// Determine key sizes based on algorithm security level.
	pk_size, sk_size := kem_key_sizes(algorithm)
	// TODO: Use actual PQC library (e.g. liboqs FFI) for key generation.
	// Placeholder: generate random bytes of correct sizes.
	public_key := generate_random_bytes(pk_size)
	secret_key := generate_random_bytes(sk_size)
	kp := KeyPair{
		public_key: public_key
		secret_key: secret_key
		algorithm: kem_algorithm_name(algorithm)
	}
	s.kem_keys[label] = kp
	return kp
}

// kem_encapsulate performs a KEM encapsulation against the public key
// stored under the given label. Returns the ciphertext and the shared
// secret.
pub fn (s PqcServer) kem_encapsulate(label string) !(CipherText, []u8) {
	kp := s.kem_keys[label] or {
		return error('KEM key not found: ${label}')
	}
	// TODO: Perform real KEM encapsulation with liboqs.
	// Placeholder: derive shared secret from public key hash.
	shared_secret := generate_random_bytes(32)
	ss_hash := sha256.sum(shared_secret)
	// Ciphertext is derived from public key and shared secret.
	mut ct_input := []u8{}
	ct_input << kp.public_key
	ct_input << shared_secret
	ct_hash := sha256.sum(ct_input)
	algorithm := parse_kem_algorithm(kp.algorithm)
	ct := CipherText{
		data: ct_hash.to_array()
		algorithm: algorithm
		shared_secret_hash: ss_hash.to_array()
	}
	return ct, shared_secret
}

// kem_decapsulate performs a KEM decapsulation using the secret key
// stored under the given label. Returns the shared secret.
pub fn (s PqcServer) kem_decapsulate(label string, ciphertext CipherText) ![]u8 {
	if label !in s.kem_keys {
		return error('KEM key not found: ${label}')
	}
	kp := s.kem_keys[label] or { return error('KEM key not found: ${label}') }
	// TODO: Perform real KEM decapsulation with liboqs.
	// Placeholder: derive shared secret from secret key and ciphertext.
	mut input := []u8{}
	input << kp.secret_key
	input << ciphertext.data
	hash := sha256.sum(input)
	return hash.to_array()
}

// sig_keygen generates a new signature key pair for the specified
// algorithm and stores it under the given label.
pub fn (mut s PqcServer) sig_keygen(label string, algorithm SigAlgorithm) !KeyPair {
	if label.len == 0 {
		return error('key label must not be empty')
	}
	if label in s.sig_keys {
		return error('signature key already exists: ${label}')
	}
	pk_size, sk_size := sig_key_sizes(algorithm)
	// TODO: Use actual PQC library for key generation.
	public_key := generate_random_bytes(pk_size)
	secret_key := generate_random_bytes(sk_size)
	kp := KeyPair{
		public_key: public_key
		secret_key: secret_key
		algorithm: sig_algorithm_name(algorithm)
	}
	s.sig_keys[label] = kp
	return kp
}

// sig_sign signs a message using the signature key stored under the
// given label.
pub fn (s PqcServer) sig_sign(label string, message []u8) !Signature {
	kp := s.sig_keys[label] or {
		return error('signature key not found: ${label}')
	}
	// TODO: Perform real PQC signing with liboqs.
	// Placeholder: HMAC-like hash of message with secret key.
	mut combined := []u8{}
	combined << kp.secret_key
	combined << message
	hash := sha256.sum(combined)
	algorithm := parse_sig_algorithm(kp.algorithm)
	return Signature{
		data: hash.to_array()
		algorithm: algorithm
	}
}

// sig_verify verifies a signature against a message using the public
// key stored under the given label.
pub fn (s PqcServer) sig_verify(label string, message []u8, sig Signature) ! {
	kp := s.sig_keys[label] or {
		return error('signature key not found: ${label}')
	}
	// TODO: Perform real PQC signature verification with liboqs.
	// Placeholder: recompute and compare.
	mut combined := []u8{}
	combined << kp.secret_key
	combined << message
	hash := sha256.sum(combined)
	expected := hash.to_array()
	if sig.data.len != expected.len {
		return error('signature verification failed')
	}
	for i in 0 .. sig.data.len {
		if sig.data[i] != expected[i] {
			return error('signature verification failed')
		}
	}
}

// hybrid_exchange performs a hybrid key exchange combining a classical
// ECDH-like exchange with a post-quantum KEM. Returns the combined
// shared secret.
pub fn (s PqcServer) hybrid_exchange(kem_label string) ![]u8 {
	if kem_label !in s.kem_keys {
		return error('KEM key not found: ${kem_label}')
	}
	// TODO: Perform real ECDH + PQC KEM hybrid exchange.
	// Placeholder: generate classical and PQ shared secrets, combine.
	classical_secret := generate_random_bytes(32)
	pq_secret := generate_random_bytes(32)
	mut combined := []u8{}
	combined << classical_secret
	combined << pq_secret
	hash := sha256.sum(combined)
	return hash.to_array()
}

// kem_key_sizes returns the (public_key, secret_key) sizes in bytes
// for the given KEM algorithm.
fn kem_key_sizes(algorithm KemAlgorithm) (int, int) {
	return match algorithm {
		.kyber512 { 800, 1632 }
		.kyber768 { 1184, 2400 }
		.kyber1024 { 1568, 3168 }
		.bike_l1 { 2542, 3110 }
		.bike_l3 { 4964, 5765 }
		.hqc128 { 2249, 2289 }
		.hqc192 { 4522, 4562 }
	}
}

// sig_key_sizes returns the (public_key, secret_key) sizes in bytes
// for the given signature algorithm.
fn sig_key_sizes(algorithm SigAlgorithm) (int, int) {
	return match algorithm {
		.dilithium2 { 1312, 2528 }
		.dilithium3 { 1952, 4000 }
		.dilithium5 { 2592, 4864 }
		.falcon512 { 897, 1281 }
		.falcon1024 { 1793, 2305 }
		.sphincs_sha256 { 32, 64 }
		.sphincs_sha256s { 32, 64 }
	}
}

// kem_algorithm_name returns the string name for a KEM algorithm.
fn kem_algorithm_name(algorithm KemAlgorithm) string {
	return match algorithm {
		.kyber512 { 'kyber512' }
		.kyber768 { 'kyber768' }
		.kyber1024 { 'kyber1024' }
		.bike_l1 { 'bike_l1' }
		.bike_l3 { 'bike_l3' }
		.hqc128 { 'hqc128' }
		.hqc192 { 'hqc192' }
	}
}

// sig_algorithm_name returns the string name for a signature algorithm.
fn sig_algorithm_name(algorithm SigAlgorithm) string {
	return match algorithm {
		.dilithium2 { 'dilithium2' }
		.dilithium3 { 'dilithium3' }
		.dilithium5 { 'dilithium5' }
		.falcon512 { 'falcon512' }
		.falcon1024 { 'falcon1024' }
		.sphincs_sha256 { 'sphincs_sha256' }
		.sphincs_sha256s { 'sphincs_sha256s' }
	}
}

// parse_kem_algorithm converts a string back to a KemAlgorithm enum.
fn parse_kem_algorithm(name string) KemAlgorithm {
	return match name {
		'kyber512' { .kyber512 }
		'kyber768' { .kyber768 }
		'kyber1024' { .kyber1024 }
		'bike_l1' { .bike_l1 }
		'bike_l3' { .bike_l3 }
		'hqc128' { .hqc128 }
		'hqc192' { .hqc192 }
		else { .kyber768 }
	}
}

// parse_sig_algorithm converts a string back to a SigAlgorithm enum.
fn parse_sig_algorithm(name string) SigAlgorithm {
	return match name {
		'dilithium2' { .dilithium2 }
		'dilithium3' { .dilithium3 }
		'dilithium5' { .dilithium5 }
		'falcon512' { .falcon512 }
		'falcon1024' { .falcon1024 }
		'sphincs_sha256' { .sphincs_sha256 }
		'sphincs_sha256s' { .sphincs_sha256s }
		else { .dilithium3 }
	}
}

// generate_random_bytes creates an array of random bytes of the
// specified length.
fn generate_random_bytes(length int) []u8 {
	mut bytes := []u8{len: length}
	for i in 0 .. length {
		bytes[i] = u8(rand.int_in_range(0, 256) or { 0 })
	}
	return bytes
}
