// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// BQN source code generator for bqniser.
//
// Takes a BQNProgram (populated by the parser) and emits a .bqn file
// containing:
// - A header comment with project metadata
// - Named BQN functions for each detected array pattern
// - Uses the correct BQN primitives: +´ reduce, ∾ join, ⌽ reverse,
//   ⍋ grade, / replicate, ⊏ select, ⥊ reshape, ¨ each, ⌜ table, ` scan

use anyhow::Result;

use crate::abi::{ArrayPatternKind, BQNProgram};
use crate::codegen::parser::primitive_comment;

/// Generate the complete .bqn source file for a BQNProgram.
///
/// The output is valid BQN that can be run directly with CBQN.
/// Each pattern becomes a named block (using export-style assignments)
/// so that the FFI bridge can call individual functions.
pub fn generate_bqn(program: &BQNProgram) -> Result<String> {
    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "# BQN program generated by bqniser for project: {}\n",
        program.project_name
    ));
    out.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str("#\n");
    out.push_str("# Each function below implements one array computation pattern\n");
    out.push_str("# detected in the source code, rewritten as optimised BQN primitives.\n");
    if program.optimised {
        out.push_str("# Optimisation: enabled\n");
    }
    out.push('\n');

    // Emit each pattern as a named BQN function.
    for (i, pattern) in program.patterns.iter().enumerate() {
        let fn_name = sanitise_bqn_name(&pattern.name);
        let ffi = &program.ffi_declarations[i];

        // Comment block describing the pattern.
        out.push_str(&format!(
            "# Pattern: {} ({})\n",
            pattern.name,
            pattern_kind_label(pattern.kind)
        ));
        out.push_str(&format!(
            "# Input:   {} -> Output: {}\n",
            pattern.input_type, pattern.output_type
        ));
        for prim in &pattern.primitives {
            out.push_str(&format!("{}\n", primitive_comment(*prim)));
        }

        // Emit the BQN function body.
        let body = generate_pattern_body(pattern.kind, program.optimised);
        // BQN assignment arrow: ←
        out.push_str(&format!("{} \u{2190} {}\n", fn_name, body));
        out.push_str(&format!("# FFI: {} => \"{}\"\n", ffi.c_name, ffi.bqn_expr));
        out.push('\n');
    }

    // If there are patterns, emit an export namespace so CBQN FFI can find them.
    if !program.patterns.is_empty() {
        out.push_str("# Exports for CBQN FFI bridge\n");
        // BQN assignment arrow: ←
        out.push_str("bqniser \u{2190} {\n");
        for pattern in &program.patterns {
            let fn_name = sanitise_bqn_name(&pattern.name);
            // BQN export arrow: ⇐
            out.push_str(&format!("  {} \u{21D0} {}\n", fn_name, fn_name));
        }
        out.push_str("}\n");
    }

    Ok(out)
}

// BQN special characters used in generated code:
// 𝕩 = U+1D569  (BQN right argument)
// 𝕗 = U+1D557  (BQN left operand / modifier operand)
// ´ = U+00B4   (BQN fold modifier)
// ¨ = U+00A8   (BQN each modifier)
// ⍋ = U+234B   (BQN grade up)
// ⊏ = U+228F   (BQN select)
// ⊔ = U+2514   — actually BQN group is ⊔ = U+2294
// ← = U+2190   (BQN assignment)
//
// We use literal Unicode characters in strings below for clarity.

/// Generate the BQN function body for a given pattern kind.
///
/// Returns a BQN block `{...}` expression using the appropriate primitives.
fn generate_pattern_body(kind: ArrayPatternKind, optimised: bool) -> String {
    match kind {
        ArrayPatternKind::LoopSum => {
            // +´ — fold with addition.
            // 𝕩 is the right argument in a BQN block.
            "{+\u{00B4}\u{1D569}}".to_string()
        }
        ArrayPatternKind::MapTransform => {
            // 𝕗¨ — each: apply the operand function element-wise.
            // 𝕗 is the modifier operand, 𝕩 is the argument.
            "{\u{1D557}\u{00A8}\u{1D569}}".to_string()
        }
        ArrayPatternKind::FilterPredicate => {
            // (𝕗 𝕩)/𝕩 — compute boolean mask then replicate.
            "{(\u{1D557} \u{1D569})/\u{1D569}}".to_string()
        }
        ArrayPatternKind::Sort => {
            if optimised {
                // Single expression: select by grade-up.
                // (⍋𝕩)⊏𝕩
                "{(\u{234B}\u{1D569})\u{228F}\u{1D569}}".to_string()
            } else {
                // Two-step for clarity.
                "{\n  perm \u{2190} \u{234B}\u{1D569}\n  perm\u{228F}\u{1D569}\n}".to_string()
            }
        }
        ArrayPatternKind::GroupBy => {
            // (𝕗 𝕩)⊔𝕩 — group elements by classifier function.
            // BQN group: ⊔ = U+2294
            "{(\u{1D557} \u{1D569})\u{2294}\u{1D569}}".to_string()
        }
    }
}

/// Convert a pattern name to a valid BQN identifier.
///
/// BQN identifiers are lowercase Unicode letters. We replace hyphens
/// and underscores with nothing (camelCase) and ensure lowercase start.
fn sanitise_bqn_name(name: &str) -> String {
    let parts: Vec<&str> = name.split(['-', '_', ' ']).collect();
    if parts.is_empty() {
        return "unnamed".to_string();
    }
    let mut result = parts[0].to_lowercase();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_uppercase().next().unwrap_or(first));
            result.extend(chars);
        }
    }
    result
}

/// Human-readable label for a pattern kind.
fn pattern_kind_label(kind: ArrayPatternKind) -> &'static str {
    match kind {
        ArrayPatternKind::LoopSum => "loop-sum",
        ArrayPatternKind::MapTransform => "map-transform",
        ArrayPatternKind::FilterPredicate => "filter-predicate",
        ArrayPatternKind::Sort => "sort",
        ArrayPatternKind::GroupBy => "group-by",
    }
}
