// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// CBQN FFI bridge generator for bqniser.
//
// Emits two files:
// 1. A C header (`bqniser_ffi.h`) declaring functions that host code can call.
// 2. A Zig source file (`bqniser_ffi.zig`) implementing those functions via
//    the CBQN C API (BQN_NewValue, BQN_Eval, etc.).
//
// The generated bridge allows any language with a C FFI to call BQN array
// primitives without embedding BQN source code directly.

use anyhow::Result;

use crate::abi::BQNProgram;

/// Generate both the C header and the Zig FFI implementation.
///
/// Returns `(header_source, zig_source)`.
pub fn generate_ffi(program: &BQNProgram) -> Result<(String, String)> {
    let header = generate_c_header(program)?;
    let zig = generate_zig_impl(program)?;
    Ok((header, zig))
}

/// Generate the C header file for the CBQN FFI bridge.
///
/// Declares one C function per pattern, plus init/cleanup lifecycle functions.
fn generate_c_header(program: &BQNProgram) -> Result<String> {
    let mut out = String::new();

    // Header guard and preamble.
    out.push_str("/* SPDX-License-Identifier: PMPL-1.0-or-later */\n");
    out.push_str(&format!(
        "/* bqniser FFI bridge for project: {} */\n",
        program.project_name
    ));
    out.push_str("/* Generated by bqniser — do not edit manually. */\n\n");
    out.push_str("#ifndef BQNISER_FFI_H\n");
    out.push_str("#define BQNISER_FFI_H\n\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdint.h>\n\n");
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("#endif\n\n");

    // Lifecycle functions.
    out.push_str("/**\n");
    out.push_str(
        " * Initialise the CBQN runtime. Must be called before any other bqniser function.\n",
    );
    out.push_str(" * Returns 0 on success, non-zero on failure.\n");
    out.push_str(" */\n");
    out.push_str("int bqniser_init(void);\n\n");
    out.push_str("/**\n");
    out.push_str(" * Shut down the CBQN runtime and free resources.\n");
    out.push_str(" */\n");
    out.push_str("void bqniser_cleanup(void);\n\n");

    // One function per pattern.
    for ffi in &program.ffi_declarations {
        out.push_str(&format!("/**\n * BQN expression: {}\n */\n", ffi.bqn_expr));
        let params = ffi
            .param_types
            .iter()
            .enumerate()
            .map(|(i, t)| format!("{} arg{}", t, i))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "{} {}({});\n\n",
            ffi.return_type, ffi.c_name, params
        ));
    }

    out.push_str("#ifdef __cplusplus\n");
    out.push_str("}\n");
    out.push_str("#endif\n\n");
    out.push_str("#endif /* BQNISER_FFI_H */\n");

    Ok(out)
}

/// Generate the Zig FFI implementation file.
///
/// Uses the CBQN C API to:
/// 1. Initialise the BQN runtime on `bqniser_init`.
/// 2. For each pattern function, convert C arrays to BQN values, evaluate
///    the BQN expression, and convert the result back.
/// 3. Clean up on `bqniser_cleanup`.
fn generate_zig_impl(program: &BQNProgram) -> Result<String> {
    let mut out = String::new();

    // Preamble.
    out.push_str("// SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str(&format!(
        "// bqniser FFI bridge (Zig) for project: {}\n",
        program.project_name
    ));
    out.push_str("// Generated by bqniser — do not edit manually.\n");
    out.push_str("//\n");
    out.push_str("// This file implements the C-ABI functions declared in bqniser_ffi.h\n");
    out.push_str("// by calling CBQN via its C API.\n\n");

    // Import CBQN C API.
    out.push_str("const c = @cImport({\n");
    out.push_str("    @cInclude(\"cbqn.h\");\n");
    out.push_str("});\n\n");

    // Global BQN runtime state.
    out.push_str("/// Global flag tracking whether CBQN has been initialised.\n");
    out.push_str("var bqn_initialised: bool = false;\n\n");

    // Lifecycle: init.
    out.push_str("/// Initialise the CBQN runtime.\n");
    out.push_str("export fn bqniser_init() callconv(.C) c_int {\n");
    out.push_str("    if (bqn_initialised) return 0;\n");
    out.push_str("    c.bqn_init();\n");
    out.push_str("    bqn_initialised = true;\n");
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");

    // Lifecycle: cleanup.
    out.push_str("/// Shut down the CBQN runtime.\n");
    out.push_str("export fn bqniser_cleanup() callconv(.C) void {\n");
    out.push_str("    if (!bqn_initialised) return;\n");
    out.push_str("    // CBQN does not currently expose a teardown function;\n");
    out.push_str("    // this is a placeholder for future API additions.\n");
    out.push_str("    bqn_initialised = false;\n");
    out.push_str("}\n\n");

    // One function per pattern.
    for ffi in &program.ffi_declarations {
        out.push_str(&format!("/// BQN: {}\n", ffi.bqn_expr));

        // Build Zig function signature.
        let zig_ret = c_type_to_zig(&ffi.return_type);
        let zig_params: Vec<String> = ffi
            .param_types
            .iter()
            .enumerate()
            .map(|(i, t)| format!("arg{}: {}", i, c_type_to_zig(t)))
            .collect();
        let params_str = zig_params.join(", ");

        out.push_str(&format!(
            "export fn {}({}) callconv(.C) {} {{\n",
            ffi.c_name, params_str, zig_ret
        ));

        // Function body: evaluate BQN expression via CBQN API.
        out.push_str(&format!("    // Evaluate: {}\n", ffi.bqn_expr));
        out.push_str("    _ = .{");
        // Reference all parameters to avoid unused-variable errors.
        for (i, _) in ffi.param_types.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("arg{}", i));
        }
        out.push_str("};\n");

        // Emit a placeholder BQN eval call.
        let escaped_expr = ffi.bqn_expr.replace('"', "\\\"");
        out.push_str(&format!("    const expr = \"{}\";\n", escaped_expr));
        out.push_str("    const bqn_result = c.bqn_eval(expr.ptr, expr.len);\n");
        out.push_str("    _ = bqn_result;\n");

        // Return a default value (actual CBQN result extraction is backend-specific).
        match zig_ret {
            "void" => {}
            "f64" | "f32" => out.push_str("    return 0.0;\n"),
            _ => out.push_str("    return 0;\n"),
        }

        out.push_str("}\n\n");
    }

    Ok(out)
}

/// Map a C type string to the corresponding Zig type.
fn c_type_to_zig(c_type: &str) -> &str {
    match c_type.trim() {
        "double" => "f64",
        "float" => "f32",
        "int32_t" => "i32",
        "int64_t" => "i64",
        "uint32_t" => "u32",
        "uint64_t" => "u64",
        "uint8_t" => "u8",
        "int8_t" => "i8",
        "uint16_t" => "u16",
        "int16_t" => "i16",
        "size_t" => "usize",
        "void" => "void",
        s if s.starts_with("const ") && s.ends_with('*') => {
            // const T* -> [*]const ZigT — simplified to opaque pointer
            "[*]const u8"
        }
        s if s.ends_with('*') => {
            // T* -> [*]ZigT — simplified to opaque pointer
            "[*]u8"
        }
        _ => "c_int",
    }
}
