// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Build script generator for Chapeliser.
//
// Generates a bash script that compiles all generated artifacts:
//   1. Zig FFI bridge → .o object file
//   2. User's application → .o or .a (user-specific, documented in comments)
//   3. Chapel wrapper + FFI object + user code → distributed binary
//
// The build script also supports environment variable overrides for
// cross-compilation and cluster-specific Chapel configurations.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use crate::manifest::Manifest;

/// Generate the build script from a manifest.
/// Writes to `output_dir/build.sh` (executable).
pub fn generate(manifest: &Manifest, output_dir: &Path) -> Result<()> {
    let name = &manifest.workload.name;
    let safe_name = name.replace('-', "_");

    let mut src = String::with_capacity(2048);

    writeln!(src, "#!/usr/bin/env bash")?;
    writeln!(src, "# SPDX-License-Identifier: PMPL-1.0-or-later")?;
    writeln!(
        src,
        "# Auto-generated by Chapeliser — build script for workload: {name}"
    )?;
    writeln!(src, "# Regenerate with: chapeliser generate")?;
    writeln!(src)?;
    writeln!(src, "set -euo pipefail")?;
    writeln!(src)?;

    // Environment variable overrides
    writeln!(
        src,
        "# Override these environment variables for your setup:"
    )?;
    writeln!(src, "#   ZIG        — path to zig compiler (default: zig)")?;
    writeln!(
        src,
        "#   CHPL       — path to Chapel compiler (default: chpl)"
    )?;
    writeln!(
        src,
        "#   USER_LIB   — path to user's compiled library (.a or .o)"
    )?;
    writeln!(src, "#   CHPL_FLAGS — extra Chapel compiler flags")?;
    writeln!(src, "ZIG=${{ZIG:-zig}}")?;
    writeln!(src, "CHPL=${{CHPL:-chpl}}")?;
    writeln!(src, "USER_LIB=${{USER_LIB:-}}")?;
    writeln!(src, "CHPL_FLAGS=${{CHPL_FLAGS:-}}")?;
    writeln!(src)?;

    writeln!(src, "echo \"=== Chapeliser Build: {name} ===\"")?;
    writeln!(src)?;

    // Step 1: Compile Zig FFI bridge
    writeln!(
        src,
        "# Step 1: Compile the Zig FFI bridge to a C-ABI object file"
    )?;
    writeln!(src, "echo \"[1/3] Compiling Zig FFI bridge...\"")?;
    writeln!(
        src,
        "$ZIG build-obj -O ReleaseFast zig/{safe_name}_ffi.zig -femit-bin={safe_name}_ffi.o"
    )?;
    writeln!(src)?;

    // Step 2: User code
    writeln!(src, "# Step 2: Link user's application code")?;
    writeln!(src, "echo \"[2/3] Checking user code...\"")?;
    writeln!(src, "if [ -z \"$USER_LIB\" ]; then")?;
    writeln!(
        src,
        "  echo \"  WARNING: USER_LIB not set. You must provide your compiled application.\""
    )?;
    writeln!(
        src,
        "  echo \"  For Rust: cargo build --release && export USER_LIB=target/release/lib{safe_name}.a\""
    )?;
    writeln!(
        src,
        "  echo \"  For C:    gcc -c -O2 your_code.c -o user_code.o && export USER_LIB=user_code.o\""
    )?;
    writeln!(
        src,
        "  echo \"  For Zig:  zig build-obj -O ReleaseFast your_code.zig && export USER_LIB=your_code.o\""
    )?;
    writeln!(src, "  exit 1")?;
    writeln!(src, "fi")?;
    writeln!(src)?;
    writeln!(src, "if [ ! -f \"$USER_LIB\" ]; then")?;
    writeln!(src, "  echo \"  ERROR: USER_LIB=$USER_LIB not found\"")?;
    writeln!(src, "  exit 1")?;
    writeln!(src, "fi")?;
    writeln!(src, "echo \"  Using: $USER_LIB\"")?;
    writeln!(src)?;

    // Step 3: Chapel compilation
    writeln!(src, "# Step 3: Compile the Chapel distributed wrapper")?;
    writeln!(src, "echo \"[3/3] Compiling Chapel wrapper...\"")?;

    // Build Chapel compile command with appropriate flags
    if manifest.resilience.checkpoint {
        writeln!(src, "# Checkpointing enabled — Chapel needs IO support")?;
    }

    let mut chpl_cmd = format!(
        "$CHPL --fast -I include/ chapel/{safe_name}_distributed.chpl {safe_name}_ffi.o \"$USER_LIB\""
    );

    // Add Chapel config from manifest
    if let Some(ref comm) = manifest.chapel.comm_layer {
        writeln!(src, "export CHPL_COMM={comm}")?;
    }

    for flag in &manifest.chapel.compiler_flags {
        chpl_cmd.push(' ');
        chpl_cmd.push_str(flag);
    }

    if manifest.chapel.gpu_enabled {
        chpl_cmd.push_str(" --set gpuEnabled=true");
    }

    chpl_cmd.push_str(" $CHPL_FLAGS");
    chpl_cmd.push_str(&format!(" -o {safe_name}_distributed"));

    writeln!(src, "{chpl_cmd}")?;
    writeln!(src)?;

    // Success message
    writeln!(
        src,
        "echo \"=== Build complete: ./{safe_name}_distributed ===\""
    )?;
    writeln!(
        src,
        "echo \"Run with: ./{safe_name}_distributed -nl <num_locales>\""
    )?;
    writeln!(src, "echo \"  --totalItems=N       override item count\"")?;
    writeln!(
        src,
        "echo \"  --maxItemBytes=N     override max buffer size\""
    )?;
    writeln!(
        src,
        "echo \"  --grainSize=N        override chunk grain size\""
    )?;
    writeln!(src, "echo \"  --maxRetries=N       override retry limit\"")?;
    writeln!(src, "echo \"  --enableCheckpoint   enable checkpointing\"")?;

    let out_path = output_dir.join("build.sh");
    fs::write(&out_path, &src)
        .with_context(|| format!("Failed to write build script: {}", out_path.display()))?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&out_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&out_path, perms)?;
    }

    println!("  Build script:   {}", out_path.display());
    Ok(())
}
