// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Code generation engine for Chapeliser.
//
// Orchestrates generation of four artifacts from a chapeliser.toml manifest:
//   1. Chapel wrapper (.chpl) — coforall distribution, locale management, gather
//   2. Zig FFI bridge (.zig) — C-ABI interop between Chapel runtime and user code
//   3. C headers (.h) — declares the functions the user must implement
//   4. Build script (build.sh) — compiles all artifacts into a distributed binary
//
// Each artifact is generated by its own submodule:
//   - chapel.rs — the core: produces compilable Chapel with real distribution logic
//   - zig.rs — thin bridge layer between Chapel extern procs and user functions
//   - header.rs — C header declaring the user's FFI contract
//   - build_script.rs — bash script for compiling everything together

mod build_script;
mod chapel;
mod header;
mod zig;

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::manifest::Manifest;

/// Generate all artifacts from a manifest: Chapel wrapper, Zig FFI, C headers,
/// and build script. Writes output to the specified directory.
pub fn generate_all(manifest: &Manifest, output_dir: &str) -> Result<()> {
    let out = Path::new(output_dir);
    fs::create_dir_all(out.join("chapel")).context("Failed to create chapel output directory")?;
    fs::create_dir_all(out.join("zig")).context("Failed to create zig output directory")?;
    fs::create_dir_all(out.join("include")).context("Failed to create include output directory")?;

    chapel::generate(manifest, &out.join("chapel"))?;
    zig::generate(manifest, &out.join("zig"))?;
    header::generate(manifest, &out.join("include"))?;
    build_script::generate(manifest, out)?;

    Ok(())
}

/// Build the generated artifacts. Requires `chpl` and `zig` on PATH.
pub fn build(manifest: &Manifest, release: bool) -> Result<()> {
    let safe_name = manifest.workload.name.replace('-', "_");
    println!("Building Chapelised workload: {}", manifest.workload.name);

    // Check for required tools
    let chpl_check = std::process::Command::new("chpl").arg("--version").output();
    if chpl_check.is_err() {
        anyhow::bail!(
            "Chapel compiler (chpl) not found on PATH.\n\
             Install Chapel: https://chapel-lang.org/download.html\n\
             Or use: chapeliser generate  (to generate files without building)"
        );
    }

    let zig_check = std::process::Command::new("zig").arg("version").output();
    if zig_check.is_err() {
        anyhow::bail!(
            "Zig compiler not found on PATH.\n\
             Install Zig: https://ziglang.org/download/\n\
             Or use: chapeliser generate  (to generate files without building)"
        );
    }

    // Run the generated build script, passing release mode via env var
    let build_dir = Path::new("generated/chapeliser");
    let mut cmd = std::process::Command::new("bash");
    cmd.arg(build_dir.join("build.sh")).current_dir(build_dir);

    // Pass --fast (release) or --no-optimize (debug) to Chapel via CHPL_FLAGS
    if release {
        cmd.env("CHPL_FLAGS", "--fast");
        println!("  Mode: release (--fast)");
    } else {
        cmd.env("CHPL_FLAGS", "--no-optimize");
        println!("  Mode: debug (--no-optimize)");
    }

    let status = cmd.status().context("Failed to run build script")?;

    if !status.success() {
        anyhow::bail!("Build failed with exit code: {:?}", status.code());
    }

    println!(
        "Build successful: generated/chapeliser/{}_distributed",
        safe_name
    );
    Ok(())
}

/// Run the Chapelised workload with the specified number of locales.
pub fn run(
    manifest: &Manifest,
    locales: u32,
    cluster: Option<&str>,
    args: &[String],
) -> Result<()> {
    let safe_name = manifest.workload.name.replace('-', "_");
    let binary = format!("generated/chapeliser/{}_distributed", safe_name);

    if !Path::new(&binary).exists() {
        anyhow::bail!(
            "Binary not found: {}. Run 'chapeliser build' first.",
            binary
        );
    }

    println!(
        "Running {} on {} locale(s)",
        manifest.workload.name, locales
    );

    let mut cmd = std::process::Command::new(&binary);
    cmd.arg(format!("-nl{}", locales));

    if let Some(cluster_file) = cluster {
        // Parse cluster.toml and set Chapel/GASNet environment variables.
        // Chapel uses CHPL_COMM + GASNet env vars for multi-node execution.
        let cluster_cfg = std::fs::read_to_string(cluster_file)
            .with_context(|| format!("Failed to read cluster config: {}", cluster_file))?;
        let cluster: toml::Value = toml::from_str(&cluster_cfg)
            .with_context(|| format!("Failed to parse cluster config: {}", cluster_file))?;

        // Set CHPL_COMM (required for multi-node)
        if let Some(comm) = cluster.get("comm").and_then(|v| v.as_str()) {
            cmd.env("CHPL_COMM", comm);
            println!("  CHPL_COMM={}", comm);
        } else {
            // Default to gasnet-udp for cluster execution
            cmd.env("CHPL_COMM", "gasnet");
            cmd.env("CHPL_COMM_SUBSTRATE", "udp");
            println!("  CHPL_COMM=gasnet (substrate=udp, default)");
        }

        // Set GASNET_SPAWNFN for how to launch on remote nodes
        if let Some(spawn) = cluster.get("spawn").and_then(|v| v.as_str()) {
            cmd.env("GASNET_SPAWNFN", spawn);
            println!("  GASNET_SPAWNFN={}", spawn);
        } else {
            cmd.env("GASNET_SPAWNFN", "S"); // SSH spawn
            println!("  GASNET_SPAWNFN=S (SSH, default)");
        }

        // Set SSH_SERVERS — comma-separated list of hostnames
        if let Some(servers) = cluster.get("servers").and_then(|v| v.as_array()) {
            let hosts: Vec<&str> = servers.iter().filter_map(|v| v.as_str()).collect();
            let hosts_str = hosts.join(",");
            cmd.env("SSH_SERVERS", &hosts_str);
            println!("  SSH_SERVERS={}", hosts_str);
        }

        // Optional: SSH key path
        if let Some(key) = cluster.get("ssh-key").and_then(|v| v.as_str()) {
            cmd.env("GASNET_SSH_OPTIONS", format!("-i {}", key));
        }

        // Optional: CHPL_RT_NUM_THREADS_PER_LOCALE
        if let Some(threads) = cluster
            .get("threads-per-locale")
            .and_then(|v| v.as_integer())
        {
            cmd.env("CHPL_RT_NUM_THREADS_PER_LOCALE", threads.to_string());
            println!("  Threads per locale: {}", threads);
        }
    }

    for arg in args {
        cmd.arg(arg);
    }

    let status = cmd.status().context("Failed to execute Chapel binary")?;

    if !status.success() {
        anyhow::bail!("Workload exited with code: {:?}", status.code());
    }

    Ok(())
}
