// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Zig FFI bridge generator for Chapeliser.
//
// Generates a Zig source file that bridges between Chapel's `extern proc` calls
// and the user's application code. The bridge:
//   - Exports C-ABI functions that Chapel calls (c_init, c_process_item, etc.)
//   - Delegates to user-provided symbols with workload-specific names
//   - Handles buffer management and error code translation
//
// The generated Zig is compiled to a .o/.a that Chapel links against.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use crate::manifest::Manifest;

/// Generate the Zig FFI bridge from a manifest.
/// Writes to `output_dir/zig/<name>_ffi.zig`.
pub fn generate(manifest: &Manifest, output_dir: &Path) -> Result<()> {
    let name = &manifest.workload.name;
    let safe_name = name.replace('-', "_");

    let mut src = String::with_capacity(4096);

    write_zig_header(&mut src, name)?;
    write_user_externs(&mut src, &safe_name)?;
    write_chapel_exports(&mut src, &safe_name, manifest)?;

    let out_path = output_dir.join(format!("{}_ffi.zig", safe_name));
    fs::write(&out_path, &src)
        .with_context(|| format!("Failed to write Zig FFI bridge: {}", out_path.display()))?;
    println!("  Zig FFI bridge: {}", out_path.display());

    Ok(())
}

/// File header and imports.
fn write_zig_header(src: &mut String, name: &str) -> Result<()> {
    writeln!(src, "// SPDX-License-Identifier: PMPL-1.0-or-later")?;
    writeln!(
        src,
        "// Auto-generated by Chapeliser — do not edit manually."
    )?;
    writeln!(src, "// Zig FFI bridge for workload: {name}")?;
    writeln!(src, "// Regenerate with: chapeliser generate")?;
    writeln!(src)?;
    writeln!(src, "const std = @import(\"std\");")?;
    writeln!(src)?;

    Ok(())
}

/// Declare the user-provided symbols that the bridge delegates to.
/// These are implemented by the user in their own code (Rust, C, Zig, etc.)
/// with C linkage and workload-specific names.
fn write_user_externs(src: &mut String, safe_name: &str) -> Result<()> {
    writeln!(
        src,
        "// ----------------------------------------------------------------"
    )?;
    writeln!(
        src,
        "// User-provided symbols (implement these in your application)"
    )?;
    writeln!(
        src,
        "// Link against your compiled code when building with Chapel."
    )?;
    writeln!(
        src,
        "// ----------------------------------------------------------------"
    )?;
    writeln!(src)?;

    // Lifecycle
    writeln!(src, "// Lifecycle")?;
    writeln!(src, "extern fn {safe_name}_init() callconv(.C) c_int;")?;
    writeln!(src, "extern fn {safe_name}_shutdown() callconv(.C) c_int;")?;
    writeln!(src)?;

    // Data I/O
    writeln!(src, "// Data I/O")?;
    writeln!(
        src,
        "extern fn {safe_name}_get_total_items() callconv(.C) c_int;"
    )?;
    writeln!(
        src,
        "extern fn {safe_name}_load_item(idx: c_int, buf: [*]u8, len: *usize) callconv(.C) c_int;"
    )?;
    writeln!(
        src,
        "extern fn {safe_name}_store_result(idx: c_int, buf: [*]const u8, len: usize) callconv(.C) c_int;"
    )?;
    writeln!(src)?;

    // Processing
    writeln!(src, "// Processing")?;
    writeln!(
        src,
        "extern fn {safe_name}_process_item(in_buf: [*]const u8, in_len: usize, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int;"
    )?;
    writeln!(
        src,
        "extern fn {safe_name}_process_chunk(items_buf: [*]const u8, item_count: c_int, item_offsets: [*]const c_int, item_sizes: [*]const c_int, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int;"
    )?;
    writeln!(src)?;

    // Reduction
    writeln!(src, "// Reduction")?;
    writeln!(
        src,
        "extern fn {safe_name}_reduce(a_buf: [*]const u8, a_len: usize, b_buf: [*]const u8, b_len: usize, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int;"
    )?;
    writeln!(src)?;

    // Match predicate (for 'first' gather)
    writeln!(src, "// Match predicate")?;
    writeln!(
        src,
        "extern fn {safe_name}_is_match(buf: [*]const u8, len: usize) callconv(.C) c_int;"
    )?;
    writeln!(src)?;

    // Key hash (for keyed partition)
    writeln!(src, "// Key hash")?;
    writeln!(
        src,
        "extern fn {safe_name}_key_hash(buf: [*]const u8, len: usize) callconv(.C) c_uint;"
    )?;
    writeln!(src)?;

    // Checkpoint
    writeln!(
        src,
        "// Checkpoint (optional — return -1 if not implemented)"
    )?;
    writeln!(
        src,
        "extern fn {safe_name}_checkpoint_save(buf: [*]const u8, len: usize, tag: [*:0]const u8) callconv(.C) c_int;"
    )?;
    writeln!(
        src,
        "extern fn {safe_name}_checkpoint_load(buf: [*]u8, len: *usize, tag: [*:0]const u8) callconv(.C) c_int;"
    )?;
    writeln!(src)?;

    Ok(())
}

/// Export the C-ABI functions that Chapel calls.
/// These simply delegate to the user's workload-specific functions.
fn write_chapel_exports(src: &mut String, safe_name: &str, _manifest: &Manifest) -> Result<()> {
    writeln!(
        src,
        "// ----------------------------------------------------------------"
    )?;
    writeln!(src, "// Chapel-facing C-ABI exports")?;
    writeln!(
        src,
        "// These are called by the generated Chapel code via `extern proc`."
    )?;
    writeln!(
        src,
        "// ----------------------------------------------------------------"
    )?;
    writeln!(src)?;

    // Each export simply delegates to the user's function.
    // This indirection allows multiple workloads to coexist in the same binary.

    let exports = [
        (
            "c_init",
            format!("{safe_name}_init"),
            "() callconv(.C) c_int",
        ),
        (
            "c_shutdown",
            format!("{safe_name}_shutdown"),
            "() callconv(.C) c_int",
        ),
        (
            "c_get_total_items",
            format!("{safe_name}_get_total_items"),
            "() callconv(.C) c_int",
        ),
    ];

    for (chapel_name, user_name, sig) in &exports {
        writeln!(src, "export fn {chapel_name}{sig} {{")?;
        writeln!(src, "    return {user_name}();")?;
        writeln!(src, "}}")?;
        writeln!(src)?;
    }

    // c_load_item
    writeln!(
        src,
        "export fn c_load_item(idx: c_int, buf: [*]u8, len: *usize) callconv(.C) c_int {{"
    )?;
    writeln!(src, "    return {safe_name}_load_item(idx, buf, len);")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_store_result
    writeln!(
        src,
        "export fn c_store_result(idx: c_int, buf: [*]const u8, len: usize) callconv(.C) c_int {{"
    )?;
    writeln!(src, "    return {safe_name}_store_result(idx, buf, len);")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_process_item
    writeln!(
        src,
        "export fn c_process_item(in_buf: [*]const u8, in_len: usize, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int {{"
    )?;
    writeln!(
        src,
        "    return {safe_name}_process_item(in_buf, in_len, out_buf, out_len);"
    )?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_process_chunk
    writeln!(
        src,
        "export fn c_process_chunk(items_buf: [*]const u8, item_count: c_int, item_offsets: [*]const c_int, item_sizes: [*]const c_int, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int {{"
    )?;
    writeln!(
        src,
        "    return {safe_name}_process_chunk(items_buf, item_count, item_offsets, item_sizes, out_buf, out_len);"
    )?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_reduce
    writeln!(
        src,
        "export fn c_reduce(a_buf: [*]const u8, a_len: usize, b_buf: [*]const u8, b_len: usize, out_buf: [*]u8, out_len: *usize) callconv(.C) c_int {{"
    )?;
    writeln!(
        src,
        "    return {safe_name}_reduce(a_buf, a_len, b_buf, b_len, out_buf, out_len);"
    )?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_is_match
    writeln!(
        src,
        "export fn c_is_match(buf: [*]const u8, len: usize) callconv(.C) c_int {{"
    )?;
    writeln!(src, "    return {safe_name}_is_match(buf, len);")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_key_hash
    writeln!(
        src,
        "export fn c_key_hash(buf: [*]const u8, len: usize) callconv(.C) c_uint {{"
    )?;
    writeln!(src, "    return {safe_name}_key_hash(buf, len);")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_checkpoint_save
    writeln!(
        src,
        "export fn c_checkpoint_save(buf: [*]const u8, len: usize, tag: [*:0]const u8) callconv(.C) c_int {{"
    )?;
    writeln!(
        src,
        "    return {safe_name}_checkpoint_save(buf, len, tag);"
    )?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    // c_checkpoint_load
    writeln!(
        src,
        "export fn c_checkpoint_load(buf: [*]u8, len: *usize, tag: [*:0]const u8) callconv(.C) c_int {{"
    )?;
    writeln!(
        src,
        "    return {safe_name}_checkpoint_load(buf, len, tag);"
    )?;
    writeln!(src, "}}")?;

    Ok(())
}
